package com.p3achb0t._runelite_interfaces

interface Actor : Entity {
    fun getDefaultHeight(): Int
    fun getFalse0(): Boolean
    fun getHealthBars(): IterableNodeDeque
    fun getHeightOffset(): Int
    fun getHitSplatCount(): Byte
    fun getHitSplatCycles(): IntArray
    fun getHitSplatTypes(): IntArray
    fun getHitSplatTypes2(): IntArray
    fun getHitSplatValues(): IntArray
    fun getHitSplatValues2(): IntArray
    fun getIdleSequence(): Int
    fun getIsAutoChatting(): Boolean
    fun getMovementFrame(): Int
    fun getMovementFrameCycle(): Int
    fun getMovementSequence(): Int
    fun getNpcCycle(): Int
    fun getOrientation(): Int
    fun getOverheadText(): String
    fun getOverheadTextColor(): Int
    fun getOverheadTextCyclesRemaining(): Int
    fun getOverheadTextEffect(): Int
    fun getPathLength(): Int
    fun getPathTraversed(): ByteArray
    fun getPathX(): IntArray
    fun getPathY(): IntArray
    fun getPlayerCycle(): Int
    fun getRunSequence(): Int
    fun getSequence(): Int
    fun getSequenceDelay(): Int
    fun getSequenceFrame(): Int
    fun getSequenceFrameCycle(): Int
    fun getSize(): Int
    fun getSpotAnimation(): Int
    fun getSpotAnimationFrame(): Int
    fun getSpotAnimationFrameCycle(): Int
    fun getTargetIndex(): Int
    fun getTurnLeftSequence(): Int
    fun getTurnRightSequence(): Int
    fun getWalkSequence(): Int
    fun getWalkTurnLeftSequence(): Int
    fun getWalkTurnRightSequence(): Int
    fun getWalkTurnSequence(): Int
    fun getX(): Int
    fun getY(): Int
    fun get__ay(): Boolean
    fun get__az(): Boolean
    fun get__ac(): Int
    fun get__bc(): Int
    fun get__be(): Int
    fun get__bf(): Int
    fun get__bh(): Int
    fun get__bj(): Int
    fun get__bt(): Int
    fun get__bv(): Int
    fun get__bw(): Int
    fun get__ch(): Int
    fun get__cj(): Int
    fun get__cm(): Int
    fun get__cq(): Int
    fun get__cr(): Int
    fun get__cv(): Int
}
