package com.p3achb0t._runelite_interfaces

interface Bzip2State {
    fun get__ag(): BooleanArray
    fun get__aq(): BooleanArray
    fun get__i(): Byte
    fun get__ac(): ByteArray
    fun get__aj(): ByteArray
    fun get__av(): ByteArray
    fun get__ay(): ByteArray
    fun get__g(): ByteArray
    fun get__x(): ByteArray
    fun get__ah(): Array<ByteArray>
    fun get__a(): Int
    fun get__ae(): Int
    fun get__c(): Int
    fun get__d(): Int
    fun get__e(): Int
    fun get__h(): Int
    fun get__j(): Int
    fun get__k(): Int
    fun get__l(): Int
    fun get__n(): Int
    fun get__s(): Int
    fun get__t(): Int
    fun get__v(): Int
    fun get__y(): Int
    fun get__z(): Int
    fun get__ab(): IntArray
    fun get__ar(): IntArray
    fun get__b(): IntArray
    fun get__r(): IntArray
    fun get__ak(): Array<IntArray>
    fun get__al(): Array<IntArray>
    fun get__aw(): Array<IntArray>
    fun get__f(): Int
    fun get__m(): Int
    fun get__o(): Int
    fun get__q(): Int
    fun get__u(): Int
    fun get__w(): Int
}
