package com.p3achb0t._runelite_interfaces

interface Client : GameShell {
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<Array<Byte>>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<Array<Byte>>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<Array<Byte>>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getEnumDefinition_cached(): EvictingDualNodeHashTable
    fun getEnumDefinition_indexCache(): AbstractIndexCache
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHealthBarDefinition_cached(): EvictingDualNodeHashTable
    fun getHealthBarDefinition_cachedSprites(): EvictingDualNodeHashTable
    fun getHitSplatDefinition_cached(): EvictingDualNodeHashTable
    fun getHitSplatDefinition_cachedFonts(): EvictingDualNodeHashTable
    fun getIndexCache_crc(): Any
    fun getIndexStoreActionHandler_lock(): Any
    fun getIndexStoreActionHandler_requestQueue(): NodeDeque
    fun getIndexStoreActionHandler_responseQueue(): NodeDeque
    fun getIndexStoreActionHandler_thread(): Any
    fun getIndexStore_buffer(): Array<Byte>
    fun getInstrument_delays(): Array<Int>
    fun getInstrument_noise(): Array<Int>
    fun getInstrument_phases(): Array<Int>
    fun getInstrument_pitchBaseSteps(): Array<Int>
    fun getInstrument_pitchSteps(): Array<Int>
    fun getInstrument_samples(): Array<Int>
    fun getInstrument_sine(): Array<Int>
    fun getInstrument_volumeSteps(): Array<Int>
    fun getInterpreter_arrayLengths(): Array<Int>
    fun getInterpreter_arrays(): Array<Array<Int>>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ScriptFrame>
    fun getInterpreter_intLocals(): Array<Int>
    fun getInterpreter_intStack(): Array<Int>
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getItemDefinition_cached(): EvictingDualNodeHashTable
    fun getItemDefinition_cachedModels(): EvictingDualNodeHashTable
    fun getItemDefinition_indexCache(): AbstractIndexCache
    fun getItemDefinition_modelIndexCache(): AbstractIndexCache
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): Array<Int>
    fun getKeyHandler_pressedKeys(): Array<Boolean>
    fun getKitDefinition_cached(): EvictingDualNodeHashTable
    fun getKitDefinition_indexCache(): AbstractIndexCache
    fun getLogin_isUsernameRemembered(): Boolean
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModelData_cosine(): Array<Int>
    fun getModelData_sine(): Array<Int>
    fun getModel_cosine(): Array<Int>
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): Array<Byte>
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): Array<Byte>
    fun getModel_sine(): Array<Int>
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_indexCaches(): Array<IndexCache>
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Buffer
    fun getNetCache_responseArchiveBuffer(): Buffer
    fun getNetCache_responseHeaderBuffer(): Buffer
    fun getNetCache_socket(): AbstractSocket
    fun getNpcDefinition_cached(): EvictingDualNodeHashTable
    fun getNpcDefinition_cachedModels(): EvictingDualNodeHashTable
    fun getNpcDefinition_indexCache(): AbstractIndexCache
    fun getNpcDefinition_modelIndexCache(): AbstractIndexCache
    fun getObjectDefinition_cached(): EvictingDualNodeHashTable
    fun getObjectDefinition_cachedModels(): EvictingDualNodeHashTable
    fun getObjectDefinition_indexCache(): AbstractIndexCache
    fun getObjectDefinition_isLowDetail(): Boolean
    fun getPacketBuffer_masks(): Array<Int>
    fun getParamKeyDefinition_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): Array<Int>
    fun getPlayers_orientations(): Array<Int>
    fun getPlayers_regions(): Array<Int>
    fun getPlayers_targetIndices(): Array<Int>
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): Array<Int>
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): Array<Int>
    fun getRasterizer3D_cosine(): Array<Int>
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): Array<Int>
    fun getRasterizer3D_sine(): Array<Int>
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): Array<Int>
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getScript_cached(): EvictingDualNodeHashTable
    fun getSequenceDefinition_cached(): EvictingDualNodeHashTable
    fun getSequenceDefinition_indexCache(): AbstractIndexCache
    fun getSkills_enabled(): Array<Boolean>
    fun getSkills_experienceTable(): Array<Int>
    fun getSpotAnimationDefinition_cached(): EvictingDualNodeHashTable
    fun getSpotAnimationDefinition_cachedModels(): EvictingDualNodeHashTable
    fun getSpotAnimationDefinition_indexCache(): AbstractIndexCache
    fun getSpotAnimationDefinition_modelIndexCache(): AbstractIndexCache
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): Array<Int>
    fun getTiles_heights(): Array<Array<Array<Int>>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<Array<Byte>>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnderlayDefinition_cached(): EvictingDualNodeHashTable
    fun getUnderlayDefinition_indexCache(): AbstractIndexCache
    fun getVarbitDefinition_cached(): EvictingDualNodeHashTable
    fun getVarbitDefinition_indexCache(): AbstractIndexCache
    fun getVarpDefinition_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): Array<Int>
    fun getVarps_masks(): Array<Int>
    fun getVarps_temp(): Array<Int>
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getWidget_cachedFonts(): EvictingDualNodeHashTable
    fun getWidget_cachedModels(): EvictingDualNodeHashTable
    fun getWidget_indexCache(): AbstractIndexCache
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapElement_cached(): Array<WorldMapElement>
    fun getWorldMapElement_cachedSprites(): EvictingDualNodeHashTable
    fun getWorldMapElement_count(): Int
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedWidget(): Widget
    fun getClickedWidgetParent(): Widget
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): Array<Int>
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDirectBufferUnavailable(): Boolean
    fun getDisplayFps(): Boolean
    fun getDragInventoryWidget(): Widget
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): Array<Int>
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameObjects(): Array<GameObject>
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGroundItems(): Array<Array<Array<NodeDeque>>>
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getIndexCache0(): IndexCache
    fun getIndexCache1(): IndexCache
    fun getIndexCache10(): IndexCache
    fun getIndexCache11(): IndexCache
    fun getIndexCache12(): IndexCache
    fun getIndexCache13(): IndexCache
    fun getIndexCache14(): IndexCache
    fun getIndexCache15(): IndexCache
    fun getIndexCache16(): IndexCache
    fun getIndexCache2(): IndexCache
    fun getIndexCache3(): IndexCache
    fun getIndexCache4(): IndexCache
    fun getIndexCache5(): IndexCache
    fun getIndexCache6(): IndexCache
    fun getIndexCache7(): IndexCache
    fun getIndexCache8(): IndexCache
    fun getIndexCache9(): IndexCache
    fun getIndexCacheLoaderIndex(): Int
    fun getIndexCacheLoaders(): Any
    fun getIndexStore255(): IndexStore
    fun getInstanceChunkTemplates(): Array<Array<Array<Int>>>
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingWidget(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5ConnectState(): Int
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLanguage(): Int
    fun getLevels(): Array<Int>
    fun getLoadedWidgetGroups(): Array<Boolean>
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): Array<Int>
    fun getMapIconYs(): Array<Int>
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): Array<Int>
    fun getMenuArguments1(): Array<Int>
    fun getMenuArguments2(): Array<Int>
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): Array<Int>
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): Array<Boolean>
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapOrientation(): Int
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): Array<Int>
    fun getModelViewportYs(): Array<Int>
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverWidgetIf1(): Widget
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackArchiveId(): Int
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): Array<Int>
    fun getNpcs(): Array<Npc>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): Array<Int>
    fun getOverheadTextColors(): Array<Int>
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): Array<Int>
    fun getOverheadTextEffects(): Array<Int>
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): Array<Int>
    fun getOverheadTextXs(): Array<Int>
    fun getOverheadTextYs(): Array<Int>
    fun getPacketBufferNodes(): Array<PacketBufferNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): Array<Int>
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): Array<Int>
    fun getRegionLandArchives(): Array<Array<Byte>>
    fun getRegionMapArchiveIds(): Array<Int>
    fun getRegionMapArchives(): Array<Array<Byte>>
    fun getRegions(): Array<Int>
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRights(): Int
    fun getRootWidgetCount(): Int
    fun getRootWidgetGroup(): Int
    fun getRootWidgetHeights(): Array<Int>
    fun getRootWidgetWidths(): Array<Int>
    fun getRootWidgetXs(): Array<Int>
    fun getRootWidgetYs(): Array<Int>
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScriptEvents(): NodeDeque
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedItemWidget(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): Array<Int>
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): SpriteIds
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MenuAction
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<Array<Int>>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidget(): Widget
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<Array<Boolean>>>>
    fun getVisibleTiles(): Array<Array<Boolean>>
    fun getWeight(): Int
    fun getWidgetClickMasks(): NodeHashTable
    fun getWidgetClickX(): Int
    fun getWidgetClickY(): Int
    fun getWidgetDragDuration(): Int
    fun getWidgetGroupParents(): NodeHashTable
    fun getWidgets(): Array<Array<Widget>>
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<Array<Int>>
    fun get__f_m(): AbstractIndexCache
    fun get__w_qs(): Int
    fun get__o_m(): AbstractIndexCache
    fun get__u_n(): Boolean
    fun get__g_f(): Any
    fun get__g_o(): Any
    fun get__g_q(): Any
    fun get__g_w(): Any
    fun get__g_z(): Int
    fun get__x_rg(): Int
    fun get__d_gz(): Sprite
    fun get__n_n(): Widget
    fun get__i_af(): Int
    fun get__i_x(): Array<Int>
    fun get__z_si(): Long
    fun get__s_fi(): Int
    fun get__s_dq(): IndexCache
    fun get__t_i(): Widget
    fun get__y_sn(): Int
    fun get__y_p(): Array<Int>
    fun get__h_n(): Array<Int>
    fun get__h_e(): IndexedSprite
    fun get__h_f(): WorldMapSectionType
    fun get__h_m(): WorldMapSectionType
    fun get__h_q(): WorldMapSectionType
    fun get__h_w(): WorldMapSectionType
    fun get__b_by(): String
    fun get__p_go(): Int
    fun get__aq_k(): AbstractIndexCache
    fun get__aj_e(): Int
    fun get__av_o(): DemotingHashTable
    fun get__ar_l(): Boolean
    fun get__ar_qw(): Int
    fun get__ar_bd(): Array<Sprite>
    fun get__ay_u(): Array<Array<Array<Byte>>>
    fun get__ah_l(): Array<Int>
    fun get__ak_qj(): Int
    fun get__ap_w(): Array<IndexedSprite>
    fun get__as_ey(): Int
    fun get__an_cl(): Int
    fun get__an_cp(): Array<Int>
    fun get__an_cg(): Array<Char>
    fun get__an_cc(): Int
    fun get__an_ch(): Int
    fun get__an_ct(): Int
    fun get__an_cw(): Int
    fun get__an_cz(): Int
    fun get__an_ra(): Int
    fun get__an_cf(): Array<Int>
    fun get__an_cq(): Array<Int>
    fun get__an_i(): IndexedSprite
    fun get__an_x(): Array<IndexedSprite>
    fun get__ao_s(): Array<String>
    fun get__ao_gk(): Int
    fun get__af_m(): Any
    fun get__af_f(): String
    fun get__ba_aw(): Int
    fun get__ba_d(): Int
    fun get__ba_e(): Int
    fun get__ba_l(): Int
    fun get__ba_q(): Int
    fun get__ba_s(): Int
    fun get__ba_a(): Array<Long>
    fun get__ba_j(): Array<Long>
    fun get__bb_hz(): Int
    fun get__bs_nb(): Int
    fun get__bq_l(): Array<Array<Array<Byte>>>
    fun get__bq_w(): Array<Array<Array<Byte>>>
    fun get__bq_p(): Int
    fun get__bq_v(): Int
    fun get__bq_a(): Array<Array<Array<Int>>>
    fun get__bq_b(): Array<Int>
    fun get__bq_c(): Array<Int>
    fun get__bq_h(): Array<Int>
    fun get__bq_r(): Array<Int>
    fun get__bq_t(): Array<Int>
    fun get__bq_y(): Array<Int>
    fun get__bk_g(): Array<Int>
    fun get__bd_x(): Array<Array<Short>>
    fun get__bd_er(): Int
    fun get__bd_u(): IndexedSprite
    fun get__bc_dm(): IndexCache
    fun get__bo_ar(): Any
    fun get__bx_o(): Int
    fun get__by_hb(): Int
    fun get__bu_hy(): Int
    fun get__bm_i(): Array<Int>
    fun get__client_il(): Int
    fun get__client_ss(): Int
    fun get__client_sj(): OwnWorldComparator
    fun get__client_ai(): Boolean
    fun get__client_bl(): Boolean
    fun get__client_cw(): Boolean
    fun get__client_fh(): Boolean
    fun get__client_hh(): Boolean
    fun get__client_ij(): Boolean
    fun get__client_is(): Boolean
    fun get__client_jl(): Boolean
    fun get__client_mn(): Boolean
    fun get__client_nn(): Boolean
    fun get__client_nt(): Boolean
    fun get__client_qq(): Boolean
    fun get__client_kv(): Array<Boolean>
    fun get__client_od(): Array<Boolean>
    fun get__client_oq(): Array<Boolean>
    fun get__client_ot(): Array<Boolean>
    fun get__client_rh(): Array<Boolean>
    fun get__client_ev(): Array<Byte>
    fun get__client_ru(): PlayerAppearance
    fun get__client_md(): Widget
    fun get__client_mo(): Widget
    fun get__client_cn(): Int
    fun get__client_cq(): Int
    fun get__client_dp(): Int
    fun get__client_ej(): Int
    fun get__client_el(): Int
    fun get__client_eo(): Int
    fun get__client_ex(): Int
    fun get__client_fd(): Int
    fun get__client_fe(): Int
    fun get__client_fk(): Int
    fun get__client_fn(): Int
    fun get__client_fw(): Int
    fun get__client_gh(): Int
    fun get__client_gp(): Int
    fun get__client_gy(): Int
    fun get__client_hc(): Int
    fun get__client_hd(): Int
    fun get__client_hg(): Int
    fun get__client_hi(): Int
    fun get__client_hj(): Int
    fun get__client_hk(): Int
    fun get__client_hn(): Int
    fun get__client_ho(): Int
    fun get__client_hr(): Int
    fun get__client_ht(): Int
    fun get__client_hu(): Int
    fun get__client_hv(): Int
    fun get__client_hw(): Int
    fun get__client_hx(): Int
    fun get__client_ie(): Int
    fun get__client_if(): Int
    fun get__client_ik(): Int
    fun get__client_in(): Int
    fun get__client_iy(): Int
    fun get__client_ja(): Int
    fun get__client_jc(): Int
    fun get__client_je(): Int
    fun get__client_jo(): Int
    fun get__client_ju(): Int
    fun get__client_jz(): Int
    fun get__client_ke(): Int
    fun get__client_ku(): Int
    fun get__client_ky(): Int
    fun get__client_lb(): Int
    fun get__client_lc(): Int
    fun get__client_ln(): Int
    fun get__client_lq(): Int
    fun get__client_ls(): Int
    fun get__client_mb(): Int
    fun get__client_mf(): Int
    fun get__client_mh(): Int
    fun get__client_ms(): Int
    fun get__client_na(): Int
    fun get__client_nc(): Int
    fun get__client_nd(): Int
    fun get__client_ng(): Int
    fun get__client_nh(): Int
    fun get__client_ni(): Int
    fun get__client_nk(): Int
    fun get__client_nl(): Int
    fun get__client_np(): Int
    fun get__client_nq(): Int
    fun get__client_ns(): Int
    fun get__client_nv(): Int
    fun get__client_nw(): Int
    fun get__client_nx(): Int
    fun get__client_oo(): Int
    fun get__client_pb(): Int
    fun get__client_ph(): Int
    fun get__client_pl(): Int
    fun get__client_pm(): Int
    fun get__client_qc(): Int
    fun get__client_qf(): Int
    fun get__client_qp(): Int
    fun get__client_qy(): Int
    fun get__client_sd(): Int
    fun get__client_sl(): Int
    fun get__client_sx(): Int
    fun get__client_fg(): Array<Int>
    fun get__client_kd(): Array<Int>
    fun get__client_kn(): Array<Int>
    fun get__client_nf(): Array<Int>
    fun get__client_nr(): Array<Int>
    fun get__client_nz(): Array<Int>
    fun get__client_pn(): Array<Int>
    fun get__client_pq(): Array<Int>
    fun get__client_pv(): Array<Int>
    fun get__client_qd(): Array<Int>
    fun get__client_qk(): Array<Int>
    fun get__client_qn(): Array<Int>
    fun get__client_rd(): Array<Int>
    fun get__client_rj(): Array<Int>
    fun get__client_rk(): Array<Int>
    fun get__client_rl(): Array<Int>
    fun get__client_th(): Array<Int>
    fun get__client_tp(): Array<Int>
    fun get__client_pz(): String
    fun get__client_kh(): NodeDeque
    fun get__client_oc(): NodeDeque
    fun get__client_oh(): NodeDeque
    fun get__client_ch(): Long
    fun get__client_oa(): Long
    fun get__client_pp(): Long
    fun get__client_pu(): Array<Long>
    fun get__client_rb(): Short
    fun get__client_re(): Short
    fun get__client_ri(): Short
    fun get__client_rm(): Short
    fun get__client_rp(): Short
    fun get__client_rs(): Short
    fun get__client_rv(): Short
    fun get__client_rw(): Short
    fun get__client_gd(): Array<Int>
    fun get__bt_g(): Int
    fun get__bt_e(): Array<Int>
    fun get__bt_l(): Array<Int>
    fun get__bf_m(): Int
    fun get__bv_s(): Boolean
    fun get__bv_t(): Boolean
    fun get__bv_y(): Int
    fun get__bv_r(): Double
    fun get__bv_z(): Array<String>
    fun get__bw_d(): Int
    fun get__bw_k(): IndexedSprite
    fun get__ce_o(): Any
    fun get__ce_u(): Any
    fun get__cy_d(): Array<Int>
    fun get__cm_e(): Int
    fun get__cm_f(): Any
    fun get__cm_m(): Any
    fun get__cj_ay(): String
    fun get__cj_bo(): Array<IndexedSprite>
    fun get__cj_sp(): Array<Short>
    fun get__cu_aa(): Boolean
    fun get__cu_ax(): Boolean
    fun get__cu_ba(): Boolean
    fun get__cu_bk(): Boolean
    fun get__cu_f(): Boolean
    fun get__cu_ac(): Int
    fun get__cu_aj(): Int
    fun get__cu_aw(): Int
    fun get__cu_bb(): Int
    fun get__cu_bj(): Int
    fun get__cu_bl(): Int
    fun get__cu_br(): Int
    fun get__cu_q(): Int
    fun get__cu_y(): Int
    fun get__cu_ai(): String
    fun get__cu_bq(): String
    fun get__cu_bs(): String
    fun get__cu_g(): Sprite
    fun get__cu_bi(): Long
    fun get__cu_bz(): Long
    fun get__cu_d(): IndexedSprite
    fun get__cu_o(): IndexedSprite
    fun get__cn_bu(): IndexedSprite
    fun get__cq_q(): Array<Byte>
    fun get__cq_w(): Array<Byte>
    fun get__cq_a(): Buffer
    fun get__cq_o(): Array<Buffer>
    fun get__cq_l(): Int
    fun get__cq_n(): Int
    fun get__cq_e(): Array<Int>
    fun get__cq_i(): Array<Int>
    fun get__cd_s(): Boolean
    fun get__cd_z(): Array<Boolean>
    fun get__cd_g(): Array<Byte>
    fun get__cd_ag(): Array<Float>
    fun get__cd_aj(): Array<Float>
    fun get__cd_aq(): Array<Float>
    fun get__cd_c(): Array<Float>
    fun get__cd_p(): Array<Float>
    fun get__cd_r(): Array<Float>
    fun get__cd_v(): Array<Float>
    fun get__cd_d(): Int
    fun get__cd_e(): Int
    fun get__cd_l(): Int
    fun get__cd_x(): Int
    fun get__cd_ar(): Array<Int>
    fun get__cd_av(): Array<Int>
    fun get__cd_j(): Array<Int>
    fun get__ca_k(): Array<Boolean>
    fun get__ca_d(): Array<Int>
    fun get__ca_x(): Array<Int>
    fun get__ca_f(): Array<Float>
    fun get__ca_m(): Array<Int>
    fun get__di_l(): Float
    fun get__di_u(): Array<Array<Float>>
    fun get__di_e(): Int
    fun get__di_g(): Array<Array<Int>>
    fun get__dk_lm(): Widget
    fun get__dk_o(): Int
    fun get__dr_ao(): Int
    fun get__dw_ab(): Int
    fun get__dw_al(): Array<Int>
    fun get__dw_aw(): Array<Int>
    fun get__dv_j(): Array<Int>
    fun get__dv_s(): Array<Int>
    fun get__dv_t(): Array<Int>
    fun get__dv_y(): Array<Int>
    fun get__dv_z(): Array<Int>
    fun get__dv_b(): Array<Array<Int>>
    fun get__dv_h(): Array<Array<Int>>
    fun get__dz_f(): Array<Int>
    fun get__dz_m(): Array<Int>
    fun get__dz_q(): Array<Int>
    fun get__dz_w(): Array<Int>
    fun get__du_bx(): Boolean
    fun get__du_ad(): Array<Boolean>
    fun get__du_at(): Array<Boolean>
    fun get__du_aa(): Array<Int>
    fun get__du_af(): Array<Int>
    fun get__du_am(): Array<Int>
    fun get__du_an(): Array<Int>
    fun get__du_au(): Array<Int>
    fun get__du_az(): Array<Int>
    fun get__du_ba(): Array<Int>
    fun get__du_bb(): Array<Int>
    fun get__du_bj(): Array<Int>
    fun get__du_bk(): Array<Int>
    fun get__du_bn(): Array<Int>
    fun get__du_bq(): Array<Int>
    fun get__du_br(): Array<Int>
    fun get__du_bs(): Array<Int>
    fun get__du_ai(): Array<Array<Int>>
    fun get__du_ax(): Array<Array<Int>>
    fun get__dm_g(): Int
    fun get__dm_k(): Int
    fun get__dm_l(): Int
    fun get__dm_u(): Int
    fun get__dq_pe(): Boolean
    fun get__dq_rq(): Int
    fun get__et_w(): Boolean
    fun get__et_f(): Boolean
    fun get__et_m(): Boolean
    fun get__et_p(): Array<Int>
    fun get__et_r(): Array<Int>
    fun get__eb_ah(): Bounds
    fun get__ek_x(): Int
    fun get__em_ab(): Boolean
    fun get__em_ac(): Boolean
    fun get__em_a(): Int
    fun get__em_ad(): Int
    fun get__em_aa(): Array<Int>
    fun get__em_af(): Array<Int>
    fun get__em_ai(): Array<Int>
    fun get__em_ao(): Array<Int>
    fun get__em_au(): Array<Int>
    fun get__em_ax(): Array<Int>
    fun get__em_ba(): Array<Int>
    fun get__ej_jv(): Widget
    fun get__el_x(): Int
    fun get__el_gm(): Sprite
    fun get__en_bc(): Array<IndexedSprite>
    fun get__eh_fy(): Int
    fun get__eo_u(): Int
    fun get__eo_ak(): Bounds
    fun get__ey_bx(): Array<IndexedSprite>
    fun get__fw_nm(): Int
    fun get__fg_jh(): Widget
    fun get__fh_x(): AbstractIndexCache
    fun get__fx_w(): Int
    fun get__fs_o(): Any
    fun get__fs_au(): Int
    fun get__fo_m(): Boolean
    fun get__fo_f(): Any
    fun get__fo_ro(): Int
    fun get__fo_q(): Any
    fun get__fb_bm(): IndexedSprite
    fun get__fi_e(): Array<Int>
    fun get__fi_l(): Array<Int>
    fun get__fi_q(): Array<Array<Int>>
    fun get__fi_w(): Array<Array<Int>>
    fun get__fe_e(): Array<Array<Array<Byte>>>
    fun get__ge_a(): ServerPacket
    fun get__ge_aa(): ServerPacket
    fun get__ge_ab(): ServerPacket
    fun get__ge_ac(): ServerPacket
    fun get__ge_ad(): ServerPacket
    fun get__ge_ae(): ServerPacket
    fun get__ge_af(): ServerPacket
    fun get__ge_ag(): ServerPacket
    fun get__ge_ah(): ServerPacket
    fun get__ge_ai(): ServerPacket
    fun get__ge_aj(): ServerPacket
    fun get__ge_ak(): ServerPacket
    fun get__ge_al(): ServerPacket
    fun get__ge_am(): ServerPacket
    fun get__ge_an(): ServerPacket
    fun get__ge_ao(): ServerPacket
    fun get__ge_ap(): ServerPacket
    fun get__ge_aq(): ServerPacket
    fun get__ge_ar(): ServerPacket
    fun get__ge_as(): ServerPacket
    fun get__ge_at(): ServerPacket
    fun get__ge_au(): ServerPacket
    fun get__ge_av(): ServerPacket
    fun get__ge_aw(): ServerPacket
    fun get__ge_ax(): ServerPacket
    fun get__ge_ay(): ServerPacket
    fun get__ge_az(): ServerPacket
    fun get__ge_b(): ServerPacket
    fun get__ge_ba(): ServerPacket
    fun get__ge_bb(): ServerPacket
    fun get__ge_bc(): ServerPacket
    fun get__ge_bd(): ServerPacket
    fun get__ge_be(): ServerPacket
    fun get__ge_bf(): ServerPacket
    fun get__ge_bg(): ServerPacket
    fun get__ge_bh(): ServerPacket
    fun get__ge_bi(): ServerPacket
    fun get__ge_bj(): ServerPacket
    fun get__ge_bk(): ServerPacket
    fun get__ge_bl(): ServerPacket
    fun get__ge_bm(): ServerPacket
    fun get__ge_bn(): ServerPacket
    fun get__ge_bo(): ServerPacket
    fun get__ge_bp(): ServerPacket
    fun get__ge_bq(): ServerPacket
    fun get__ge_br(): ServerPacket
    fun get__ge_bs(): ServerPacket
    fun get__ge_bt(): ServerPacket
    fun get__ge_bu(): ServerPacket
    fun get__ge_bv(): ServerPacket
    fun get__ge_bw(): ServerPacket
    fun get__ge_bx(): ServerPacket
    fun get__ge_by(): ServerPacket
    fun get__ge_bz(): ServerPacket
    fun get__ge_c(): ServerPacket
    fun get__ge_ce(): ServerPacket
    fun get__ge_cj(): ServerPacket
    fun get__ge_cm(): ServerPacket
    fun get__ge_cr(): ServerPacket
    fun get__ge_cs(): ServerPacket
    fun get__ge_cv(): ServerPacket
    fun get__ge_cy(): ServerPacket
    fun get__ge_d(): ServerPacket
    fun get__ge_e(): ServerPacket
    fun get__ge_f(): ServerPacket
    fun get__ge_g(): ServerPacket
    fun get__ge_h(): ServerPacket
    fun get__ge_i(): ServerPacket
    fun get__ge_j(): ServerPacket
    fun get__ge_k(): ServerPacket
    fun get__ge_l(): ServerPacket
    fun get__ge_m(): ServerPacket
    fun get__ge_n(): ServerPacket
    fun get__ge_o(): ServerPacket
    fun get__ge_p(): ServerPacket
    fun get__ge_q(): ServerPacket
    fun get__ge_r(): ServerPacket
    fun get__ge_s(): ServerPacket
    fun get__ge_t(): ServerPacket
    fun get__ge_u(): ServerPacket
    fun get__ge_v(): ServerPacket
    fun get__ge_w(): ServerPacket
    fun get__ge_x(): ServerPacket
    fun get__ge_y(): ServerPacket
    fun get__ge_z(): ServerPacket
    fun get__gs_a(): ClientPacket
    fun get__gs_aa(): ClientPacket
    fun get__gs_ab(): ClientPacket
    fun get__gs_ac(): ClientPacket
    fun get__gs_ad(): ClientPacket
    fun get__gs_ae(): ClientPacket
    fun get__gs_af(): ClientPacket
    fun get__gs_ag(): ClientPacket
    fun get__gs_ah(): ClientPacket
    fun get__gs_ai(): ClientPacket
    fun get__gs_aj(): ClientPacket
    fun get__gs_ak(): ClientPacket
    fun get__gs_al(): ClientPacket
    fun get__gs_an(): ClientPacket
    fun get__gs_ao(): ClientPacket
    fun get__gs_ap(): ClientPacket
    fun get__gs_aq(): ClientPacket
    fun get__gs_ar(): ClientPacket
    fun get__gs_as(): ClientPacket
    fun get__gs_at(): ClientPacket
    fun get__gs_au(): ClientPacket
    fun get__gs_av(): ClientPacket
    fun get__gs_aw(): ClientPacket
    fun get__gs_ax(): ClientPacket
    fun get__gs_ay(): ClientPacket
    fun get__gs_az(): ClientPacket
    fun get__gs_b(): ClientPacket
    fun get__gs_ba(): ClientPacket
    fun get__gs_bb(): ClientPacket
    fun get__gs_bc(): ClientPacket
    fun get__gs_bd(): ClientPacket
    fun get__gs_be(): ClientPacket
    fun get__gs_bf(): ClientPacket
    fun get__gs_bg(): ClientPacket
    fun get__gs_bh(): ClientPacket
    fun get__gs_bi(): ClientPacket
    fun get__gs_bj(): ClientPacket
    fun get__gs_bk(): ClientPacket
    fun get__gs_bl(): ClientPacket
    fun get__gs_bm(): ClientPacket
    fun get__gs_bn(): ClientPacket
    fun get__gs_bo(): ClientPacket
    fun get__gs_bp(): ClientPacket
    fun get__gs_bq(): ClientPacket
    fun get__gs_br(): ClientPacket
    fun get__gs_bs(): ClientPacket
    fun get__gs_bt(): ClientPacket
    fun get__gs_bu(): ClientPacket
    fun get__gs_bv(): ClientPacket
    fun get__gs_bw(): ClientPacket
    fun get__gs_bx(): ClientPacket
    fun get__gs_by(): ClientPacket
    fun get__gs_bz(): ClientPacket
    fun get__gs_c(): ClientPacket
    fun get__gs_cb(): ClientPacket
    fun get__gs_cc(): ClientPacket
    fun get__gs_ce(): ClientPacket
    fun get__gs_cf(): ClientPacket
    fun get__gs_cg(): ClientPacket
    fun get__gs_ch(): ClientPacket
    fun get__gs_cj(): ClientPacket
    fun get__gs_ck(): ClientPacket
    fun get__gs_cl(): ClientPacket
    fun get__gs_cm(): ClientPacket
    fun get__gs_cn(): ClientPacket
    fun get__gs_cp(): ClientPacket
    fun get__gs_cq(): ClientPacket
    fun get__gs_cr(): ClientPacket
    fun get__gs_cs(): ClientPacket
    fun get__gs_ct(): ClientPacket
    fun get__gs_cu(): ClientPacket
    fun get__gs_cv(): ClientPacket
    fun get__gs_cw(): ClientPacket
    fun get__gs_cy(): ClientPacket
    fun get__gs_cz(): ClientPacket
    fun get__gs_d(): ClientPacket
    fun get__gs_e(): ClientPacket
    fun get__gs_f(): ClientPacket
    fun get__gs_g(): ClientPacket
    fun get__gs_h(): ClientPacket
    fun get__gs_i(): ClientPacket
    fun get__gs_j(): ClientPacket
    fun get__gs_k(): ClientPacket
    fun get__gs_l(): ClientPacket
    fun get__gs_m(): ClientPacket
    fun get__gs_n(): ClientPacket
    fun get__gs_o(): ClientPacket
    fun get__gs_p(): ClientPacket
    fun get__gs_q(): ClientPacket
    fun get__gs_r(): ClientPacket
    fun get__gs_s(): ClientPacket
    fun get__gs_t(): ClientPacket
    fun get__gs_u(): ClientPacket
    fun get__gs_v(): ClientPacket
    fun get__gs_w(): ClientPacket
    fun get__gs_x(): ClientPacket
    fun get__gs_y(): ClientPacket
    fun get__gs_z(): ClientPacket
    fun get__gs_qh(): Int
    fun get__gs_am(): ClientPacket
    fun get__gs_ci(): ClientPacket
    fun get__gl_m(): LoginPacket
    fun get__gl_q(): LoginPacket
    fun get__gl_w(): LoginPacket
    fun get__gl_f(): LoginPacket
    fun get__gl_o(): LoginPacket
    fun get__gl_g(): Array<LoginPacket>
    fun get__gg_u(): Int
    fun get__gd_e(): Array<Array<Int>>
    fun get__go_ck(): Char
    fun get__gr_q(): Array<Int>
    fun get__gr_o(): Array<Long>
    fun get__gi_g(): Array<Int>
    fun get__gx_n(): Font
    fun get__gx_d(): Array<Int>
    fun get__gx_x(): Array<Int>
    fun get__gu_et(): IndexCache
    fun get__hx_z(): Int
    fun get__hg_q(): Any
    fun get__hg_f(): Array<String>
    fun get__hg_m(): Array<Array<String>>
    fun get__hd_fc(): Long
    fun get__hf_o(): Int
    fun get__hf_f(): AbstractIndexCache
    fun get__hf_q(): AbstractIndexCache
    fun get__hf_u(): AbstractIndexCache
    fun get__hf_k(): Array<Int>
    fun get__hs_x(): Array<Byte>
    fun get__hq_qg(): Int
    fun get__hv_h(): Int
    fun get__hi_g(): Array<Short>
    fun get__hi_d(): Array<Int>
    fun get__ht_m(): Array<Short>
    fun get__ht_q(): Array<Short>
    fun get__ht_f(): Array<Array<Short>>
    fun get__ht_w(): Array<Array<Short>>
    fun get__hj_e(): Array<Short>
    fun get__ho_j(): Boolean
    fun get__ho_d(): AbstractIndexCache
    fun get__ho_n(): EvictingDualNodeHashTable
    fun get__ho_z(): EvictingDualNodeHashTable
    fun get__hz_l(): Array<Array<Short>>
    fun get__hy_az(): Boolean
    fun get__hb_sg(): Int
    fun get__hb_av(): Any
    fun get__hc_ef(): Array<Int>
    fun get__id_aa(): String
    fun get__id_ad(): String
    fun get__id_ae(): String
    fun get__id_af(): String
    fun get__id_ai(): String
    fun get__id_am(): String
    fun get__id_an(): String
    fun get__id_ao(): String
    fun get__id_ap(): String
    fun get__id_as(): String
    fun get__id_at(): String
    fun get__id_au(): String
    fun get__id_ax(): String
    fun get__id_az(): String
    fun get__id_ba(): String
    fun get__id_bb(): String
    fun get__id_bc(): String
    fun get__id_bd(): String
    fun get__id_be(): String
    fun get__id_bf(): String
    fun get__id_bg(): String
    fun get__id_bh(): String
    fun get__id_bi(): String
    fun get__id_bj(): String
    fun get__id_bk(): String
    fun get__id_bl(): String
    fun get__id_bm(): String
    fun get__id_bn(): String
    fun get__id_bo(): String
    fun get__id_bp(): String
    fun get__id_bq(): String
    fun get__id_br(): String
    fun get__id_bs(): String
    fun get__id_bt(): String
    fun get__id_bu(): String
    fun get__id_bv(): String
    fun get__id_bw(): String
    fun get__id_bx(): String
    fun get__id_by(): String
    fun get__id_bz(): String
    fun get__id_ca(): String
    fun get__id_cb(): String
    fun get__id_cc(): String
    fun get__id_cd(): String
    fun get__id_ce(): String
    fun get__id_cf(): String
    fun get__id_cg(): String
    fun get__id_ch(): String
    fun get__id_ci(): String
    fun get__id_cj(): String
    fun get__id_ck(): String
    fun get__id_cl(): String
    fun get__id_cm(): String
    fun get__id_cn(): String
    fun get__id_co(): String
    fun get__id_cp(): String
    fun get__id_cq(): String
    fun get__id_cr(): String
    fun get__id_cs(): String
    fun get__id_ct(): String
    fun get__id_cu(): String
    fun get__id_cv(): String
    fun get__id_cw(): String
    fun get__id_cx(): String
    fun get__id_cy(): String
    fun get__id_cz(): String
    fun get__id_d(): String
    fun get__id_da(): String
    fun get__id_db(): String
    fun get__id_dc(): String
    fun get__id_dd(): String
    fun get__id_de(): String
    fun get__id_df(): String
    fun get__id_dg(): String
    fun get__id_di(): String
    fun get__id_dj(): String
    fun get__id_dk(): String
    fun get__id_dl(): String
    fun get__id_dm(): String
    fun get__id_dn(): String
    fun get__id_do(): String
    fun get__id_dp(): String
    fun get__id_dq(): String
    fun get__id_dr(): String
    fun get__id_ds(): String
    fun get__id_dt(): String
    fun get__id_du(): String
    fun get__id_dv(): String
    fun get__id_dx(): String
    fun get__id_dy(): String
    fun get__id_dz(): String
    fun get__id_eb(): String
    fun get__id_ec(): String
    fun get__id_ed(): String
    fun get__id_ee(): String
    fun get__id_ef(): String
    fun get__id_eh(): String
    fun get__id_ei(): String
    fun get__id_ej(): String
    fun get__id_ek(): String
    fun get__id_el(): String
    fun get__id_em(): String
    fun get__id_en(): String
    fun get__id_eo(): String
    fun get__id_eq(): String
    fun get__id_er(): String
    fun get__id_et(): String
    fun get__id_eu(): String
    fun get__id_ev(): String
    fun get__id_ew(): String
    fun get__id_ex(): String
    fun get__id_ey(): String
    fun get__id_fa(): String
    fun get__id_fb(): String
    fun get__id_ff(): String
    fun get__id_fk(): String
    fun get__id_fm(): String
    fun get__id_fn(): String
    fun get__id_fs(): String
    fun get__id_fv(): String
    fun get__id_fx(): String
    fun get__id_fz(): String
    fun get__id_ga(): String
    fun get__id_gb(): String
    fun get__id_gc(): String
    fun get__id_gd(): String
    fun get__id_ge(): String
    fun get__id_gf(): String
    fun get__id_gg(): String
    fun get__id_gh(): String
    fun get__id_gi(): String
    fun get__id_gj(): String
    fun get__id_gk(): String
    fun get__id_gl(): String
    fun get__id_gm(): String
    fun get__id_gn(): String
    fun get__id_go(): String
    fun get__id_gp(): String
    fun get__id_gq(): String
    fun get__id_gr(): String
    fun get__id_gs(): String
    fun get__id_gt(): String
    fun get__id_gu(): String
    fun get__id_gv(): String
    fun get__id_gw(): String
    fun get__id_gx(): String
    fun get__id_gy(): String
    fun get__id_gz(): String
    fun get__id_ha(): String
    fun get__id_hb(): String
    fun get__id_hc(): String
    fun get__id_hd(): String
    fun get__id_hf(): String
    fun get__id_hg(): String
    fun get__id_hh(): String
    fun get__id_hk(): String
    fun get__id_hm(): String
    fun get__id_hn(): String
    fun get__id_hr(): String
    fun get__id_hs(): String
    fun get__id_hx(): String
    fun get__id_hy(): String
    fun get__id_ia(): String
    fun get__id_ib(): String
    fun get__id_ic(): String
    fun get__id_id(): String
    fun get__id_ig(): String
    fun get__id_ih(): String
    fun get__id_ii(): String
    fun get__id_ik(): String
    fun get__id_im(): String
    fun get__id_io(): String
    fun get__id_ip(): String
    fun get__id_iq(): String
    fun get__id_ir(): String
    fun get__id_it(): String
    fun get__id_iu(): String
    fun get__id_iv(): String
    fun get__id_iw(): String
    fun get__id_ix(): String
    fun get__id_ja(): String
    fun get__id_jb(): String
    fun get__id_jc(): String
    fun get__id_jd(): String
    fun get__id_je(): String
    fun get__id_jf(): String
    fun get__id_jg(): String
    fun get__id_jh(): String
    fun get__id_ji(): String
    fun get__id_jj(): String
    fun get__id_jk(): String
    fun get__id_jl(): String
    fun get__id_jm(): String
    fun get__id_jn(): String
    fun get__id_jo(): String
    fun get__id_jp(): String
    fun get__id_jq(): String
    fun get__id_jr(): String
    fun get__id_js(): String
    fun get__id_jt(): String
    fun get__id_ju(): String
    fun get__id_jv(): String
    fun get__id_jw(): String
    fun get__id_jx(): String
    fun get__id_jy(): String
    fun get__id_jz(): String
    fun get__id_kd(): String
    fun get__id_ke(): String
    fun get__id_kf(): String
    fun get__id_kg(): String
    fun get__id_kj(): String
    fun get__id_km(): String
    fun get__id_kp(): String
    fun get__id_ks(): String
    fun get__id_kv(): String
    fun get__id_ky(): String
    fun get__id_l(): String
    fun get__id_x(): String
    fun get__id_ab(): String
    fun get__ij_ak(): Any
    fun get__iy_f(): ServerBuild
    fun get__iy_m(): ServerBuild
    fun get__iy_q(): ServerBuild
    fun get__iy_w(): ServerBuild
    fun get__iy_lo(): Int
    fun get__is_u(): StudioGame
    fun get__is_f(): StudioGame
    fun get__is_m(): StudioGame
    fun get__is_o(): StudioGame
    fun get__is_q(): StudioGame
    fun get__is_w(): StudioGame
    fun get__ik_cn(): Int
    fun get__ik_rt(): Int
    fun get__ir_bu(): Int
    fun get__ir_s(): Int
    fun get__iv_q(): Int
    fun get__iq_b(): Byte
    fun get__iq_f(): Int
    fun get__iq_j(): Int
    fun get__iq_q(): Long
    fun get__iu_n(): Int
    fun get__iu_e(): Array<Int>
    fun get__ib_f(): EvictingDualNodeHashTable
    fun get__ix_f(): Int
    fun get__ix_m(): AbstractIndexCache
    fun get__ic_m(): AbstractIndexCache
    fun get__iw_f(): EvictingDualNodeHashTable
    fun get__iw_m(): AbstractIndexCache
    fun get__im_q(): Int
    fun get__im_f(): AbstractIndexCache
    fun get__ii_f(): AbstractIndexCache
    fun get__ii_m(): AbstractIndexCache
    fun get__ia_u(): Array<Int>
    fun get__jb_m(): AbstractIndexCache
    fun get__jq_f(): EvictingDualNodeHashTable
    fun get__jq_m(): AbstractIndexCache
    fun get__jm_o(): EvictingDualNodeHashTable
    fun get__jm_f(): AbstractIndexCache
    fun get__jm_m(): AbstractIndexCache
    fun get__jm_q(): AbstractIndexCache
    fun get__jr_o(): EvictingDualNodeHashTable
    fun get__jr_l(): Array<ModelData>
    fun get__jr_u(): EvictingDualNodeHashTable
    fun get__jr_q(): AbstractIndexCache
    fun get__jf_f(): EvictingDualNodeHashTable
    fun get__jf_m(): AbstractIndexCache
    fun get__jh_o(): EvictingDualNodeHashTable
    fun get__jh_f(): AbstractIndexCache
    fun get__jh_q(): AbstractIndexCache
    fun get__jn_by(): IndexedSprite
    fun get__jx_ne(): Array<Widget>
    fun get__ji_i(): ClientParameter
    fun get__ji_n(): ClientParameter
    fun get__ji_fp(): AbstractSocket
    fun get__ji_a(): ClientParameter
    fun get__ji_d(): ClientParameter
    fun get__ji_e(): ClientParameter
    fun get__ji_f(): ClientParameter
    fun get__ji_g(): ClientParameter
    fun get__ji_j(): ClientParameter
    fun get__ji_k(): ClientParameter
    fun get__ji_l(): ClientParameter
    fun get__ji_m(): ClientParameter
    fun get__ji_o(): ClientParameter
    fun get__ji_q(): ClientParameter
    fun get__ji_s(): ClientParameter
    fun get__ji_t(): ClientParameter
    fun get__ji_u(): ClientParameter
    fun get__ji_w(): ClientParameter
    fun get__ji_x(): ClientParameter
    fun get__ji_z(): ClientParameter
    fun get__ks_at(): String
    fun get__kn_x(): UrlRequest
    fun get__kz_o(): Array<Array<Array<Byte>>>
    fun get__kz_l(): Sprite
    fun get__kb_q(): Array<Char>
    fun get__kb_w(): Array<Char>
    fun get__kc_m(): Array<Char>
    fun get__kc_g(): Array<Array<Array<Byte>>>
    fun get__kc_f(): Array<Char>
    fun get__kc_q(): Array<Char>
    fun get__kc_w(): Array<Int>
    fun get__kw_n(): IndexedSprite
    fun get__ka_e(): Int
    fun get__lp_ca(): Boolean
    fun get__lj_m(): RectangleMode
    fun get__lj_f(): RectangleMode
    fun get__lj_q(): RectangleMode
    fun get__lr_e(): Array<Array<Byte>>
    fun get__lr_f(): Int
    fun get__lr_m(): Int
    fun get__lr_q(): Int
    fun get__lr_l(): Array<Int>
    fun get__lr_o(): Array<Int>
    fun get__lr_w(): Array<Int>
    fun get__lx_e(): LoginType
    fun get__lx_m(): LoginType
    fun get__lx_f(): LoginType
    fun get__lx_g(): LoginType
    fun get__lx_l(): LoginType
    fun get__lx_o(): LoginType
    fun get__lx_q(): LoginType
    fun get__lx_u(): LoginType
    fun get__lx_w(): LoginType
}
