package com.p3achb0t._runelite_interfaces

interface ItemDefinition : DualNode {
    fun getAmbient(): Int
    fun getContrast(): Int
    fun getFemaleHeadModel(): Int
    fun getFemaleHeadModel2(): Int
    fun getFemaleModel(): Int
    fun getFemaleModel1(): Int
    fun getFemaleModel2(): Int
    fun getFemaleOffset(): Int
    fun getGroundActions(): Array<String>
    fun getId(): Int
    fun getInt1(): Int
    fun getInventoryActions(): Array<String>
    fun getIsMembersOnly(): Boolean
    fun getIsStackable(): Int
    fun getIsTradable(): Boolean
    fun getMaleHeadModel(): Int
    fun getMaleHeadModel2(): Int
    fun getMaleModel(): Int
    fun getMaleModel1(): Int
    fun getMaleModel2(): Int
    fun getMaleOffset(): Int
    fun getName(): String
    fun getNote(): Int
    fun getNoteTemplate(): Int
    fun getNotedId(): Int
    fun getOffsetX2d(): Int
    fun getOffsetY2d(): Int
    fun getParams(): IterableNodeHashTable
    fun getPlaceholder(): Int
    fun getPlaceholderTemplate(): Int
    fun getPrice(): Int
    fun getRecolorFrom(): Array<Short>
    fun getRecolorTo(): Array<Short>
    fun getResizeX(): Int
    fun getResizeY(): Int
    fun getResizeZ(): Int
    fun getRetextureFrom(): Array<Short>
    fun getRetextureTo(): Array<Short>
    fun getShiftClickIndex0(): Int
    fun getUnnotedId(): Int
    fun getXan2d(): Int
    fun getYan2d(): Int
    fun getZan2d(): Int
    fun getZoom2d(): Int
    fun get__a(): Int
    fun get__au(): Array<Int>
    fun get__az(): Array<Int>
}
