package com.p3achb0t._runelite_interfaces

interface WorldMap {
    fun getCacheLoader(): WorldMapIndexCacheLoader
    fun getCurrentMapArea0(): WorldMapArea
    fun getElementsDisabled(): Boolean
    fun getEnabledCategories(): Any
    fun getEnabledElements(): Any
    fun getFlashingElements(): Any
    fun getFont(): Font
    fun getFonts(): Any
    fun getIconIterator(): Any
    fun getMainMapArea(): WorldMapArea
    fun getMapAreas(): Any
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMouseCoord(): TileLocation
    fun getPerpetualFlash0(): Boolean
    fun getSprite(): Sprite
    fun getWorldMapManager(): WorldMapManager
    fun getZoom(): Float
    fun getZoomTarget(): Float
    fun get__t(): WorldMapArea
    fun get__an(): Boolean
    fun get__ab(): Int
    fun get__ac(): Int
    fun get__ad(): Int
    fun get__ae(): Int
    fun get__aj(): Int
    fun get__al(): Int
    fun get__am(): Int
    fun get__aq(): Int
    fun get__ar(): Int
    fun get__as(): Int
    fun get__at(): Int
    fun get__av(): Int
    fun get__aw(): Int
    fun get__ay(): Int
    fun get__b(): Int
    fun get__ba(): Int
    fun get__bm(): Int
    fun get__bu(): Int
    fun get__bx(): Int
    fun get__by(): Int
    fun get__c(): Int
    fun get__p(): Int
    fun get__r(): Int
    fun get__e(): AbstractIndexCache
    fun get__g(): AbstractIndexCache
    fun get__l(): AbstractIndexCache
    fun get__af(): Any
    fun get__ax(): Any
    fun get__bk(): Any
    fun get__bq(): Any
    fun get__ap(): Long
    fun get__bs(): IntArray
    fun get__bc(): Boolean
}
