package com.p3achb0t._runestar_interfaces

interface Actor : Entity {
    fun getDefaultHeight(): Int
    fun getFalse0(): Boolean
    fun getHeadbars(): IterableNodeDeque
    fun getHeightOffset(): Int
    fun getHitmarkCount(): Byte
    fun getHitmarkCycles(): IntArray
    fun getHitmarkTypes(): IntArray
    fun getHitmarkTypes2(): IntArray
    fun getHitmarkValues(): IntArray
    fun getHitmarkValues2(): IntArray
    fun getIsAutoChatting(): Boolean
    fun getMovementFrame(): Int
    fun getMovementFrameCycle(): Int
    fun getMovementSequence(): Int
    fun getNpcCycle(): Int
    fun getOrientation(): Int
    fun getOverheadText(): String
    fun getOverheadTextColor(): Int
    fun getOverheadTextCyclesRemaining(): Int
    fun getOverheadTextEffect(): Int
    fun getPathLength(): Int
    fun getPathTraversed(): ByteArray
    fun getPathX(): IntArray
    fun getPathY(): IntArray
    fun getPlayerCycle(): Int
    fun getReadySequence(): Int
    fun getRunSequence(): Int
    fun getSequence(): Int
    fun getSequenceDelay(): Int
    fun getSequenceFrame(): Int
    fun getSequenceFrameCycle(): Int
    fun getSize(): Int
    fun getSpotAnimation(): Int
    fun getSpotAnimationFrame(): Int
    fun getSpotAnimationFrameCycle(): Int
    fun getTargetIndex(): Int
    fun getTurnLeftSequence(): Int
    fun getTurnRightSequence(): Int
    fun getWalkBackSequence(): Int
    fun getWalkLeftSequence(): Int
    fun getWalkRightSequence(): Int
    fun getWalkSequence(): Int
    fun getX(): Int
    fun getY(): Int
    fun get__an(): Boolean
    fun get__aw(): Boolean
    fun get__ao(): Int
    fun get__bc(): Int
    fun get__bh(): Int
    fun get__bk(): Int
    fun get__bm(): Int
    fun get__bp(): Int
    fun get__bs(): Int
    fun get__bw(): Int
    fun get__bz(): Int
    fun get__cd(): Int
    fun get__ch(): Int
    fun get__cj(): Int
    fun get__cm(): Int
    fun get__cn(): Int
    fun get__co(): Int
}
