package com.p3achb0t._runestar_interfaces

interface Bzip2State {
	fun get__al(): BooleanArray
	fun get__av(): BooleanArray
	fun get__r(): Byte
	fun get__ag(): ByteArray
	fun get__ar(): ByteArray
	fun get__as(): ByteArray
	fun get__aw(): ByteArray
	fun get__b(): ByteArray
	fun get__f(): ByteArray
	fun get__ax(): Array<ByteArray>
	fun get__a(): Int
	fun get__at(): Int
	fun get__c(): Int
	fun get__g(): Int
	fun get__h(): Int
	fun get__i(): Int
	fun get__j(): Int
	fun get__m(): Int
	fun get__n(): Int
	fun get__t(): Int
	fun get__u(): Int
	fun get__v(): Int
	fun get__x(): Int
	fun get__y(): Int
	fun get__z(): Int
	fun get__ad(): IntArray
	fun get__aj(): IntArray
	fun get__d(): IntArray
	fun get__o(): IntArray
	fun get__ae(): Array<IntArray>
	fun get__ao(): Array<IntArray>
	fun get__az(): Array<IntArray>
	fun get__e(): Int
	fun get__k(): Int
	fun get__l(): Int
	fun get__p(): Int
	fun get__q(): Int
	fun get__w(): Int
}
