package com.p3achb0t._runestar_interfaces

interface Client : GameShell {
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getEnumType_archive(): AbstractArchive
    fun getEnumType_cached(): EvictingDualNodeHashTable
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_isUsernameRemembered(): Boolean
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__b_p(): Int
    fun get__z_nw(): Array<Component>
    fun get__p_lj(): Component
    fun get__h_b(): Any
    fun get__h_f(): Any
    fun get__h_g(): Any
    fun get__h_z(): Any
    fun get__h_h(): Int
    fun get__x_ew(): Int
    fun get__o_he(): Int
    fun get__o_sn(): Int
    fun get__e_dd(): Archive
    fun get__e_br(): Int
    fun get__s_bi(): String
    fun get__t_b(): WorldMapSectionType
    fun get__t_f(): WorldMapSectionType
    fun get__t_g(): WorldMapSectionType
    fun get__t_u(): WorldMapSectionType
    fun get__l_d(): Int
    fun get__l_nk(): Int
    fun get__ad_h(): IntArray
    fun get__am_n(): Array<Array<IntArray>>
    fun get__ai_z(): DemotingHashTable
    fun get__ag_z(): Int
    fun get__ao_po(): Boolean
    fun get__aa_ey(): Archive
    fun get__aa_ef(): Int
    fun get__aa_qk(): Int
    fun get__ab_rg(): Int
    fun get__ar_by(): String
    fun get__aq_lv(): Int
    fun get__az_ax(): Int
    fun get__az_gk(): Int
    fun get__az_bf(): Array<IndexedSprite>
    fun get__az_gq(): Sprite
    fun get__ae_br(): IndexedSprite
    fun get__ae_bm(): Array<Sprite>
    fun get__an_ca(): Int
    fun get__an_ce(): Int
    fun get__an_cf(): Int
    fun get__an_ci(): Int
    fun get__an_cp(): Int
    fun get__an_cq(): Int
    fun get__an_cc(): IntArray
    fun get__an_cj(): IntArray
    fun get__an_cu(): Array<Char>
    fun get__an_cs(): IntArray
    fun get__au_cn(): Int
    fun get__au_rq(): Int
    fun get__ah_u(): Any
    fun get__ah_f(): String
    fun get__ah_y(): Array<Array<ByteArray>>
    fun get__ah_jz(): Component
    fun get__ah_ag(): Any
    fun get__bo_h(): Int
    fun get__bo_a(): Array<Long>
    fun get__bo_r(): Array<Long>
    fun get__bo_ab(): Int
    fun get__bo_b(): Int
    fun get__bo_i(): Int
    fun get__bo_k(): Int
    fun get__bo_ai(): Any
    fun get__bu_g(): Array<Array<ByteArray>>
    fun get__bu_h(): Array<Array<ByteArray>>
    fun get__bu_p(): Array<Array<ByteArray>>
    fun get__bu_z(): Array<Array<ByteArray>>
    fun get__bu_j(): Int
    fun get__bu_l(): Int
    fun get__bu_i(): IntArray
    fun get__bu_k(): IntArray
    fun get__bu_x(): IntArray
    fun get__bu_d(): IntArray
    fun get__bu_m(): IntArray
    fun get__bu_q(): IntArray
    fun get__bu_s(): IntArray
    fun get__bu_t(): IntArray
    fun get__bu_v(): IntArray
    fun get__bj_y(): Array<ShortArray>
    fun get__bm_bq(): Array<IndexedSprite>
    fun get__bq_eg(): Archive
    fun get__bf_k(): IndexedSprite
    fun get__br_e(): IntArray
    fun get__bb_o(): Int
    fun get__bb_sp(): Long
    fun get__bw_i(): UrlRequest
    fun get__bw_qx(): Int
    fun get__bw_t(): Int
    fun get__bw_aa(): Bounds
    fun get__client_si(): Int
    fun get__client_ah(): Boolean
    fun get__client_bb(): Boolean
    fun get__client_cq(): Boolean
    fun get__client_fi(): Boolean
    fun get__client_hm(): Boolean
    fun get__client_ia(): Boolean
    fun get__client_ib(): Boolean
    fun get__client_jq(): Boolean
    fun get__client_ne(): Boolean
    fun get__client_nm(): Boolean
    fun get__client_qt(): Boolean
    fun get__client_kk(): BooleanArray
    fun get__client_oa(): BooleanArray
    fun get__client_ob(): BooleanArray
    fun get__client_ov(): BooleanArray
    fun get__client_re(): BooleanArray
    fun get__client_sh(): OwnWorldComparator
    fun get__client_ei(): ByteArray
    fun get__client_rk(): PlayerAppearance
    fun get__client_mg(): Component
    fun get__client_mj(): Component
    fun get__client_cn(): Int
    fun get__client_cy(): Int
    fun get__client_dj(): Int
    fun get__client_dp(): Int
    fun get__client_ea(): Int
    fun get__client_ee(): Int
    fun get__client_eu(): Int
    fun get__client_fb(): Int
    fun get__client_fl(): Int
    fun get__client_ft(): Int
    fun get__client_fw(): Int
    fun get__client_fz(): Int
    fun get__client_gj(): Int
    fun get__client_gl(): Int
    fun get__client_gm(): Int
    fun get__client_ha(): Int
    fun get__client_hf(): Int
    fun get__client_hg(): Int
    fun get__client_hi(): Int
    fun get__client_hn(): Int
    fun get__client_hp(): Int
    fun get__client_hq(): Int
    fun get__client_hr(): Int
    fun get__client_hu(): Int
    fun get__client_hw(): Int
    fun get__client_hx(): Int
    fun get__client_hy(): Int
    fun get__client_ic(): Int
    fun get__client_if(): Int
    fun get__client_ik(): Int
    fun get__client_im(): Int
    fun get__client_ir(): Int
    fun get__client_is(): Int
    fun get__client_jc(): Int
    fun get__client_je(): Int
    fun get__client_jl(): Int
    fun get__client_jn(): Int
    fun get__client_js(): Int
    fun get__client_jy(): Int
    fun get__client_ka(): Int
    fun get__client_kb(): Int
    fun get__client_kw(): Int
    fun get__client_ld(): Int
    fun get__client_lf(): Int
    fun get__client_lg(): Int
    fun get__client_lo(): Int
    fun get__client_lr(): Int
    fun get__client_mf(): Int
    fun get__client_mk(): Int
    fun get__client_mn(): Int
    fun get__client_mx(): Int
    fun get__client_nb(): Int
    fun get__client_nc(): Int
    fun get__client_nd(): Int
    fun get__client_ng(): Int
    fun get__client_nh(): Int
    fun get__client_ni(): Int
    fun get__client_nl(): Int
    fun get__client_no(): Int
    fun get__client_nq(): Int
    fun get__client_nr(): Int
    fun get__client_nt(): Int
    fun get__client_nx(): Int
    fun get__client_ny(): Int
    fun get__client_nz(): Int
    fun get__client_ok(): Int
    fun get__client_pb(): Int
    fun get__client_pg(): Int
    fun get__client_pk(): Int
    fun get__client_pp(): Int
    fun get__client_qb(): Int
    fun get__client_qj(): Int
    fun get__client_qq(): Int
    fun get__client_qr(): Int
    fun get__client_sf(): Int
    fun get__client_sm(): Int
    fun get__client_su(): Int
    fun get__client_fj(): IntArray
    fun get__client_kf(): IntArray
    fun get__client_kp(): IntArray
    fun get__client_na(): IntArray
    fun get__client_nf(): IntArray
    fun get__client_nu(): IntArray
    fun get__client_pa(): IntArray
    fun get__client_pl(): IntArray
    fun get__client_pt(): IntArray
    fun get__client_qa(): IntArray
    fun get__client_qd(): IntArray
    fun get__client_qv(): IntArray
    fun get__client_ra(): IntArray
    fun get__client_ri(): IntArray
    fun get__client_rs(): IntArray
    fun get__client_rx(): IntArray
    fun get__client_tv(): IntArray
    fun get__client_tx(): IntArray
    fun get__client_ph(): String
    fun get__client_kz(): NodeDeque
    fun get__client_oo(): NodeDeque
    fun get__client_oq(): NodeDeque
    fun get__client_cj(): Long
    fun get__client_os(): Long
    fun get__client_pv(): Long
    fun get__client_pu(): Array<Long>
    fun get__client_rb(): Short
    fun get__client_rd(): Short
    fun get__client_rf(): Short
    fun get__client_rn(): Short
    fun get__client_ru(): Short
    fun get__client_rv(): Short
    fun get__client_rw(): Short
    fun get__client_rz(): Short
    fun get__client_ga(): IntArray
    fun get__be_r(): Int
    fun get__be_qu(): Int
    fun get__bp_h(): Int
    fun get__bp_w(): IntArray
    fun get__bp_y(): IntArray
    fun get__bs_u(): Int
    fun get__bs_ak(): String
    fun get__bh_a(): Boolean
    fun get__bh_d(): Boolean
    fun get__bh_e(): Component
    fun get__bh_s(): Int
    fun get__bh_q(): Double
    fun get__bh_r(): Array<String>
    fun get__bk_by(): Array<IndexedSprite>
    fun get__cm_ay(): Int
    fun get__cv_hz(): Int
    fun get__cv_p(): Any
    fun get__cv_z(): Any
    fun get__cl_w(): Int
    fun get__cl_ho(): Int
    fun get__ch_f(): Any
    fun get__ch_u(): Any
    fun get__cr_as(): Boolean
    fun get__cr_au(): Boolean
    fun get__cr_bj(): Boolean
    fun get__cr_bo(): Boolean
    fun get__cr_f(): Boolean
    fun get__cr_ai(): Int
    fun get__cr_ar(): Int
    fun get__cr_aw(): Int
    fun get__cr_b(): Int
    fun get__cr_be(): Int
    fun get__cr_bg(): Int
    fun get__cr_bw(): Int
    fun get__cr_bx(): Int
    fun get__cr_s(): Int
    fun get__cr_w(): Array<IntArray>
    fun get__cr_bd(): String
    fun get__cr_bu(): String
    fun get__cr_p(): IndexedSprite
    fun get__cr_x(): IndexedSprite
    fun get__cr_z(): IndexedSprite
    fun get__cr_i(): Array<IndexedSprite>
    fun get__cr_bl(): Long
    fun get__cr_bp(): Long
    fun get__cy_rh(): Int
    fun get__cn_ac(): String
    fun get__cn_b(): ByteArray
    fun get__cn_g(): ByteArray
    fun get__cn_o(): Int
    fun get__cn_y(): Int
    fun get__cn_e(): IntArray
    fun get__cn_w(): IntArray
    fun get__cn_n(): Packet
    fun get__cn_z(): Array<Packet>
    fun get__ct_r(): BooleanArray
    fun get__ct_ad(): Array<Float>
    fun get__ct_af(): Array<Float>
    fun get__ct_am(): Array<Float>
    fun get__ct_j(): Array<Float>
    fun get__ct_l(): Array<Float>
    fun get__ct_q(): Array<Float>
    fun get__ct_v(): Array<Float>
    fun get__ct_ag(): IntArray
    fun get__ct_ai(): IntArray
    fun get__ct_c(): IntArray
    fun get__dw_x(): BooleanArray
    fun get__dw_i(): IntArray
    fun get__dw_k(): IntArray
    fun get__dw_f(): Array<Float>
    fun get__dw_u(): IntArray
    fun get__de_fc(): AbstractSocket
    fun get__dk_fd(): Int
    fun get__dn_w(): IndexedSprite
    fun get__dh_y(): Float
    fun get__dh_p(): Array<Array<Float>>
    fun get__dh_w(): Int
    fun get__dh_h(): Array<IntArray>
    fun get__db_an(): Boolean
    fun get__da_i(): Array<ShortArray>
    fun get__dq_av(): Int
    fun get__dq_ab(): IntArray
    fun get__dq_ar(): IntArray
    fun get__do_a(): IntArray
    fun get__do_c(): IntArray
    fun get__do_d(): IntArray
    fun get__do_r(): IntArray
    fun get__do_s(): IntArray
    fun get__do_m(): Array<IntArray>
    fun get__do_t(): Array<IntArray>
    fun get__dg_b(): IntArray
    fun get__dg_f(): IntArray
    fun get__dg_g(): IntArray
    fun get__dg_u(): IntArray
    fun get__df_bf(): Boolean
    fun get__df_ac(): BooleanArray
    fun get__df_az(): BooleanArray
    fun get__df_aj(): IntArray
    fun get__df_al(): IntArray
    fun get__df_an(): IntArray
    fun get__df_ap(): IntArray
    fun get__df_as(): IntArray
    fun get__df_ax(): IntArray
    fun get__df_bd(): IntArray
    fun get__df_bg(): IntArray
    fun get__df_bi(): IntArray
    fun get__df_bn(): IntArray
    fun get__df_bo(): IntArray
    fun get__df_bu(): IntArray
    fun get__df_bw(): IntArray
    fun get__df_bx(): IntArray
    fun get__df_ah(): Array<IntArray>
    fun get__df_au(): Array<IntArray>
    fun get__dd_w(): Int
    fun get__dd_y(): Int
    fun get__eg_g(): Boolean
    fun get__eg_f(): Boolean
    fun get__eg_u(): Boolean
    fun get__eg_l(): IntArray
    fun get__eg_q(): IntArray
    fun get__ey_ns(): Int
    fun get__ec_w(): IntArray
    fun get__el_ao(): Boolean
    fun get__el_av(): Boolean
    fun get__el_az(): Int
    fun get__el_n(): Int
    fun get__el_ah(): IntArray
    fun get__el_al(): IntArray
    fun get__el_as(): IntArray
    fun get__el_au(): IntArray
    fun get__el_ax(): IntArray
    fun get__el_ay(): IntArray
    fun get__el_bi(): IntArray
    fun get__er_k(): Int
    fun get__eh_qf(): Int
    fun get__ew_ez(): Int
    fun get__ew_g(): IntArray
    fun get__eb_dy(): Archive
    fun get__eb_b(): Int
    fun get__ed_st(): Int
    fun get__fl_qg(): Int
    fun get__fj_rm(): Int
    fun get__fs_ct(): Boolean
    fun get__fr_u(): Boolean
    fun get__fr_f(): Any
    fun get__fr_b(): Any
    fun get__fh_ff(): Int
    fun get__fy_p(): Int
    fun get__fy_z(): Int
    fun get__fy_w(): IntArray
    fun get__fy_y(): IntArray
    fun get__fy_b(): Array<IntArray>
    fun get__fy_g(): Array<IntArray>
    fun get__fg_fv(): Long
    fun get__gm_a(): ServerProt
    fun get__gm_aa(): ServerProt
    fun get__gm_ab(): ServerProt
    fun get__gm_ac(): ServerProt
    fun get__gm_ad(): ServerProt
    fun get__gm_ae(): ServerProt
    fun get__gm_af(): ServerProt
    fun get__gm_ag(): ServerProt
    fun get__gm_ah(): ServerProt
    fun get__gm_ai(): ServerProt
    fun get__gm_aj(): ServerProt
    fun get__gm_ak(): ServerProt
    fun get__gm_al(): ServerProt
    fun get__gm_am(): ServerProt
    fun get__gm_an(): ServerProt
    fun get__gm_ao(): ServerProt
    fun get__gm_ap(): ServerProt
    fun get__gm_aq(): ServerProt
    fun get__gm_ar(): ServerProt
    fun get__gm_as(): ServerProt
    fun get__gm_at(): ServerProt
    fun get__gm_au(): ServerProt
    fun get__gm_av(): ServerProt
    fun get__gm_aw(): ServerProt
    fun get__gm_ax(): ServerProt
    fun get__gm_ay(): ServerProt
    fun get__gm_az(): ServerProt
    fun get__gm_b(): ServerProt
    fun get__gm_ba(): ServerProt
    fun get__gm_bb(): ServerProt
    fun get__gm_bc(): ServerProt
    fun get__gm_bd(): ServerProt
    fun get__gm_be(): ServerProt
    fun get__gm_bf(): ServerProt
    fun get__gm_bg(): ServerProt
    fun get__gm_bh(): ServerProt
    fun get__gm_bi(): ServerProt
    fun get__gm_bj(): ServerProt
    fun get__gm_bk(): ServerProt
    fun get__gm_bl(): ServerProt
    fun get__gm_bm(): ServerProt
    fun get__gm_bn(): ServerProt
    fun get__gm_bo(): ServerProt
    fun get__gm_bp(): ServerProt
    fun get__gm_bq(): ServerProt
    fun get__gm_br(): ServerProt
    fun get__gm_bs(): ServerProt
    fun get__gm_bt(): ServerProt
    fun get__gm_bu(): ServerProt
    fun get__gm_bv(): ServerProt
    fun get__gm_bw(): ServerProt
    fun get__gm_bx(): ServerProt
    fun get__gm_by(): ServerProt
    fun get__gm_bz(): ServerProt
    fun get__gm_c(): ServerProt
    fun get__gm_cd(): ServerProt
    fun get__gm_cg(): ServerProt
    fun get__gm_ch(): ServerProt
    fun get__gm_cl(): ServerProt
    fun get__gm_cm(): ServerProt
    fun get__gm_co(): ServerProt
    fun get__gm_cr(): ServerProt
    fun get__gm_cv(): ServerProt
    fun get__gm_d(): ServerProt
    fun get__gm_e(): ServerProt
    fun get__gm_f(): ServerProt
    fun get__gm_g(): ServerProt
    fun get__gm_h(): ServerProt
    fun get__gm_i(): ServerProt
    fun get__gm_j(): ServerProt
    fun get__gm_k(): ServerProt
    fun get__gm_l(): ServerProt
    fun get__gm_m(): ServerProt
    fun get__gm_n(): ServerProt
    fun get__gm_o(): ServerProt
    fun get__gm_p(): ServerProt
    fun get__gm_q(): ServerProt
    fun get__gm_r(): ServerProt
    fun get__gm_s(): ServerProt
    fun get__gm_t(): ServerProt
    fun get__gm_u(): ServerProt
    fun get__gm_v(): ServerProt
    fun get__gm_w(): ServerProt
    fun get__gm_x(): ServerProt
    fun get__gm_y(): ServerProt
    fun get__gm_z(): ServerProt
    fun get__gj_a(): ClientProt
    fun get__gj_aa(): ClientProt
    fun get__gj_ab(): ClientProt
    fun get__gj_ac(): ClientProt
    fun get__gj_ad(): ClientProt
    fun get__gj_ae(): ClientProt
    fun get__gj_af(): ClientProt
    fun get__gj_ag(): ClientProt
    fun get__gj_ah(): ClientProt
    fun get__gj_ai(): ClientProt
    fun get__gj_aj(): ClientProt
    fun get__gj_ak(): ClientProt
    fun get__gj_al(): ClientProt
    fun get__gj_am(): ClientProt
    fun get__gj_an(): ClientProt
    fun get__gj_ao(): ClientProt
    fun get__gj_ap(): ClientProt
    fun get__gj_aq(): ClientProt
    fun get__gj_ar(): ClientProt
    fun get__gj_as(): ClientProt
    fun get__gj_at(): ClientProt
    fun get__gj_av(): ClientProt
    fun get__gj_ax(): ClientProt
    fun get__gj_ay(): ClientProt
    fun get__gj_az(): ClientProt
    fun get__gj_b(): ClientProt
    fun get__gj_ba(): ClientProt
    fun get__gj_bb(): ClientProt
    fun get__gj_bc(): ClientProt
    fun get__gj_bd(): ClientProt
    fun get__gj_be(): ClientProt
    fun get__gj_bf(): ClientProt
    fun get__gj_bg(): ClientProt
    fun get__gj_bh(): ClientProt
    fun get__gj_bi(): ClientProt
    fun get__gj_bj(): ClientProt
    fun get__gj_bk(): ClientProt
    fun get__gj_bl(): ClientProt
    fun get__gj_bm(): ClientProt
    fun get__gj_bn(): ClientProt
    fun get__gj_bo(): ClientProt
    fun get__gj_bp(): ClientProt
    fun get__gj_bq(): ClientProt
    fun get__gj_bs(): ClientProt
    fun get__gj_bt(): ClientProt
    fun get__gj_bu(): ClientProt
    fun get__gj_bv(): ClientProt
    fun get__gj_bw(): ClientProt
    fun get__gj_bx(): ClientProt
    fun get__gj_by(): ClientProt
    fun get__gj_bz(): ClientProt
    fun get__gj_c(): ClientProt
    fun get__gj_ca(): ClientProt
    fun get__gj_cb(): ClientProt
    fun get__gj_cc(): ClientProt
    fun get__gj_cd(): ClientProt
    fun get__gj_ce(): ClientProt
    fun get__gj_cf(): ClientProt
    fun get__gj_cg(): ClientProt
    fun get__gj_ch(): ClientProt
    fun get__gj_ci(): ClientProt
    fun get__gj_cj(): ClientProt
    fun get__gj_ck(): ClientProt
    fun get__gj_cl(): ClientProt
    fun get__gj_cm(): ClientProt
    fun get__gj_cn(): ClientProt
    fun get__gj_co(): ClientProt
    fun get__gj_cp(): ClientProt
    fun get__gj_cq(): ClientProt
    fun get__gj_cr(): ClientProt
    fun get__gj_cs(): ClientProt
    fun get__gj_cu(): ClientProt
    fun get__gj_cv(): ClientProt
    fun get__gj_cx(): ClientProt
    fun get__gj_cy(): ClientProt
    fun get__gj_d(): ClientProt
    fun get__gj_e(): ClientProt
    fun get__gj_f(): ClientProt
    fun get__gj_g(): ClientProt
    fun get__gj_h(): ClientProt
    fun get__gj_i(): ClientProt
    fun get__gj_j(): ClientProt
    fun get__gj_k(): ClientProt
    fun get__gj_l(): ClientProt
    fun get__gj_m(): ClientProt
    fun get__gj_n(): ClientProt
    fun get__gj_o(): ClientProt
    fun get__gj_p(): ClientProt
    fun get__gj_q(): ClientProt
    fun get__gj_r(): ClientProt
    fun get__gj_s(): ClientProt
    fun get__gj_t(): ClientProt
    fun get__gj_u(): ClientProt
    fun get__gj_v(): ClientProt
    fun get__gj_w(): ClientProt
    fun get__gj_x(): ClientProt
    fun get__gj_y(): ClientProt
    fun get__gj_z(): ClientProt
    fun get__gj_au(): ClientProt
    fun get__gj_aw(): ClientProt
    fun get__gj_br(): ClientProt
    fun get__gn_b(): LoginProt
    fun get__gn_g(): LoginProt
    fun get__gn_u(): LoginProt
    fun get__gn_f(): LoginProt
    fun get__gn_z(): LoginProt
    fun get__gn_h(): Array<LoginProt>
    fun get__gs_ab(): Bounds
    fun get__gx_p(): Int
    fun get__gh_o(): Component
    fun get__gh_u(): IntArray
    fun get__gb_x(): Int
    fun get__go_ah(): Int
    fun get__gq_b(): AbstractArchive
    fun get__gq_f(): AbstractArchive
    fun get__gq_p(): AbstractArchive
    fun get__gq_u(): AbstractArchive
    fun get__gq_w(): Int
    fun get__gq_z(): Int
    fun get__gg_i(): ByteArray
    fun get__gv_so(): ShortArray
    fun get__gp_h(): Sprite
    fun get__gf_b(): Any
    fun get__gf_f(): Array<String>
    fun get__gf_u(): Array<Array<String>>
    fun get__hm_o(): IndexedSprite
    fun get__hx_c(): Int
    fun get__hd_h(): ShortArray
    fun get__hd_w(): ShortArray
    fun get__hd_eo(): IntArray
    fun get__hd_k(): IntArray
    fun get__hc_b(): ShortArray
    fun get__hc_u(): ShortArray
    fun get__hc_f(): Array<ShortArray>
    fun get__hc_g(): Array<ShortArray>
    fun get__hv_y(): IntArray
    fun get__hv_z(): IntArray
    fun get__hl_c(): Boolean
    fun get__hl_k(): AbstractArchive
    fun get__hl_x(): AbstractArchive
    fun get__hl_o(): EvictingDualNodeHashTable
    fun get__hl_r(): EvictingDualNodeHashTable
    fun get__hk_ba(): IndexedSprite
    fun get__hw_u(): AbstractArchive
    fun get__hy_ac(): String
    fun get__hy_ae(): String
    fun get__hy_ah(): String
    fun get__hy_aj(): String
    fun get__hy_al(): String
    fun get__hy_an(): String
    fun get__hy_ap(): String
    fun get__hy_aq(): String
    fun get__hy_as(): String
    fun get__hy_at(): String
    fun get__hy_au(): String
    fun get__hy_ax(): String
    fun get__hy_ay(): String
    fun get__hy_az(): String
    fun get__hy_ba(): String
    fun get__hy_bb(): String
    fun get__hy_bc(): String
    fun get__hy_bd(): String
    fun get__hy_be(): String
    fun get__hy_bf(): String
    fun get__hy_bg(): String
    fun get__hy_bh(): String
    fun get__hy_bi(): String
    fun get__hy_bj(): String
    fun get__hy_bk(): String
    fun get__hy_bl(): String
    fun get__hy_bm(): String
    fun get__hy_bn(): String
    fun get__hy_bo(): String
    fun get__hy_bp(): String
    fun get__hy_bq(): String
    fun get__hy_br(): String
    fun get__hy_bs(): String
    fun get__hy_bt(): String
    fun get__hy_bu(): String
    fun get__hy_bv(): String
    fun get__hy_bw(): String
    fun get__hy_bx(): String
    fun get__hy_by(): String
    fun get__hy_bz(): String
    fun get__hy_ca(): String
    fun get__hy_cb(): String
    fun get__hy_cc(): String
    fun get__hy_cd(): String
    fun get__hy_ce(): String
    fun get__hy_cf(): String
    fun get__hy_cg(): String
    fun get__hy_ch(): String
    fun get__hy_ci(): String
    fun get__hy_cj(): String
    fun get__hy_ck(): String
    fun get__hy_cl(): String
    fun get__hy_cm(): String
    fun get__hy_cn(): String
    fun get__hy_co(): String
    fun get__hy_cp(): String
    fun get__hy_cq(): String
    fun get__hy_cr(): String
    fun get__hy_cs(): String
    fun get__hy_ct(): String
    fun get__hy_cu(): String
    fun get__hy_cv(): String
    fun get__hy_cw(): String
    fun get__hy_cx(): String
    fun get__hy_cy(): String
    fun get__hy_cz(): String
    fun get__hy_da(): String
    fun get__hy_db(): String
    fun get__hy_dc(): String
    fun get__hy_dd(): String
    fun get__hy_de(): String
    fun get__hy_df(): String
    fun get__hy_dg(): String
    fun get__hy_dh(): String
    fun get__hy_di(): String
    fun get__hy_dj(): String
    fun get__hy_dk(): String
    fun get__hy_dl(): String
    fun get__hy_dm(): String
    fun get__hy_dn(): String
    fun get__hy_do(): String
    fun get__hy_dp(): String
    fun get__hy_dr(): String
    fun get__hy_ds(): String
    fun get__hy_dt(): String
    fun get__hy_du(): String
    fun get__hy_dw(): String
    fun get__hy_dx(): String
    fun get__hy_dy(): String
    fun get__hy_dz(): String
    fun get__hy_ea(): String
    fun get__hy_ec(): String
    fun get__hy_ee(): String
    fun get__hy_ef(): String
    fun get__hy_eg(): String
    fun get__hy_eh(): String
    fun get__hy_ei(): String
    fun get__hy_ej(): String
    fun get__hy_ek(): String
    fun get__hy_el(): String
    fun get__hy_em(): String
    fun get__hy_eo(): String
    fun get__hy_ep(): String
    fun get__hy_er(): String
    fun get__hy_et(): String
    fun get__hy_eu(): String
    fun get__hy_ev(): String
    fun get__hy_ew(): String
    fun get__hy_ex(): String
    fun get__hy_ey(): String
    fun get__hy_ez(): String
    fun get__hy_fb(): String
    fun get__hy_fg(): String
    fun get__hy_fk(): String
    fun get__hy_fn(): String
    fun get__hy_fo(): String
    fun get__hy_fr(): String
    fun get__hy_fs(): String
    fun get__hy_fu(): String
    fun get__hy_fw(): String
    fun get__hy_fy(): String
    fun get__hy_ga(): String
    fun get__hy_gb(): String
    fun get__hy_gc(): String
    fun get__hy_gd(): String
    fun get__hy_ge(): String
    fun get__hy_gf(): String
    fun get__hy_gg(): String
    fun get__hy_gh(): String
    fun get__hy_gi(): String
    fun get__hy_gj(): String
    fun get__hy_gk(): String
    fun get__hy_gl(): String
    fun get__hy_gm(): String
    fun get__hy_gn(): String
    fun get__hy_go(): String
    fun get__hy_gp(): String
    fun get__hy_gq(): String
    fun get__hy_gr(): String
    fun get__hy_gs(): String
    fun get__hy_gt(): String
    fun get__hy_gu(): String
    fun get__hy_gv(): String
    fun get__hy_gw(): String
    fun get__hy_gx(): String
    fun get__hy_gy(): String
    fun get__hy_gz(): String
    fun get__hy_ha(): String
    fun get__hy_hc(): String
    fun get__hy_hd(): String
    fun get__hy_he(): String
    fun get__hy_hf(): String
    fun get__hy_hg(): String
    fun get__hy_hi(): String
    fun get__hy_hl(): String
    fun get__hy_hm(): String
    fun get__hy_hn(): String
    fun get__hy_ho(): String
    fun get__hy_hr(): String
    fun get__hy_hv(): String
    fun get__hy_hx(): String
    fun get__hy_i(): String
    fun get__hy_ib(): String
    fun get__hy_id(): String
    fun get__hy_if(): String
    fun get__hy_ih(): String
    fun get__hy_ii(): String
    fun get__hy_ij(): String
    fun get__hy_ik(): String
    fun get__hy_il(): String
    fun get__hy_im(): String
    fun get__hy_in(): String
    fun get__hy_ip(): String
    fun get__hy_iq(): String
    fun get__hy_is(): String
    fun get__hy_it(): String
    fun get__hy_iu(): String
    fun get__hy_iw(): String
    fun get__hy_ix(): String
    fun get__hy_iy(): String
    fun get__hy_ja(): String
    fun get__hy_jb(): String
    fun get__hy_jc(): String
    fun get__hy_jd(): String
    fun get__hy_je(): String
    fun get__hy_jf(): String
    fun get__hy_jg(): String
    fun get__hy_jh(): String
    fun get__hy_ji(): String
    fun get__hy_jj(): String
    fun get__hy_jk(): String
    fun get__hy_jl(): String
    fun get__hy_jm(): String
    fun get__hy_jn(): String
    fun get__hy_jo(): String
    fun get__hy_jp(): String
    fun get__hy_jq(): String
    fun get__hy_jr(): String
    fun get__hy_js(): String
    fun get__hy_jt(): String
    fun get__hy_ju(): String
    fun get__hy_jv(): String
    fun get__hy_jw(): String
    fun get__hy_jx(): String
    fun get__hy_jy(): String
    fun get__hy_jz(): String
    fun get__hy_k(): String
    fun get__hy_ka(): String
    fun get__hy_kf(): String
    fun get__hy_kg(): String
    fun get__hy_kh(): String
    fun get__hy_kj(): String
    fun get__hy_kk(): String
    fun get__hy_kl(): String
    fun get__hy_km(): String
    fun get__hy_ko(): String
    fun get__hy_kp(): String
    fun get__hy_kr(): String
    fun get__hy_ks(): String
    fun get__hy_kw(): String
    fun get__hy_kx(): String
    fun get__hy_ky(): String
    fun get__hy_kz(): String
    fun get__hy_y(): String
    fun get__hy_av(): String
    fun get__hu_gz(): Sprite
    fun get__hp_gy(): Int
    fun get__hz_b(): ServerBuild
    fun get__hz_f(): ServerBuild
    fun get__hz_g(): ServerBuild
    fun get__hz_u(): ServerBuild
    fun get__he_p(): StudioGame
    fun get__he_b(): StudioGame
    fun get__he_f(): StudioGame
    fun get__he_g(): StudioGame
    fun get__he_u(): StudioGame
    fun get__he_z(): StudioGame
    fun get__hf_a(): Int
    fun get__ic_b(): Int
    fun get__im_o(): Boolean
    fun get__im_m(): Byte
    fun get__im_c(): Int
    fun get__im_f(): Int
    fun get__im_b(): Long
    fun get__it_u(): AbstractArchive
    fun get__it_f(): EvictingDualNodeHashTable
    fun get__ib_u(): AbstractArchive
    fun get__ib_f(): Int
    fun get__ia_u(): AbstractArchive
    fun get__ia_f(): EvictingDualNodeHashTable
    fun get__ia_h(): IntArray
    fun get__ig_u(): AbstractArchive
    fun get__ig_f(): EvictingDualNodeHashTable
    fun get__ie_b(): Int
    fun get__ie_f(): AbstractArchive
    fun get__ie_bb(): IndexedSprite
    fun get__iz_u(): AbstractArchive
    fun get__iz_f(): AbstractArchive
    fun get__io_u(): AbstractArchive
    fun get__id_f(): EvictingDualNodeHashTable
    fun get__id_u(): AbstractArchive
    fun get__id_e(): IndexedSprite
    fun get__id_g(): Array<IndexedSprite>
    fun get__ix_z(): EvictingDualNodeHashTable
    fun get__ix_b(): AbstractArchive
    fun get__ix_f(): AbstractArchive
    fun get__ix_u(): AbstractArchive
    fun get__il_y(): Array<UnlitModel>
    fun get__il_p(): EvictingDualNodeHashTable
    fun get__iu_y(): Boolean
    fun get__ii_u(): AbstractArchive
    fun get__ii_f(): EvictingDualNodeHashTable
    fun get__ii_jk(): Component
    fun get__iy_z(): EvictingDualNodeHashTable
    fun get__iy_b(): AbstractArchive
    fun get__iy_f(): AbstractArchive
    fun get__ji_a(): Array<String>
    fun get__jh_aa(): Any
    fun get__jf_i(): AbstractArchive
    fun get__jf_rc(): Int
    fun get__kh_i(): Int
    fun get__kh_f(): Array<Long>
    fun get__km_b(): Array<Char>
    fun get__km_f(): Array<Char>
    fun get__km_u(): Array<Char>
    fun get__km_g(): IntArray
    fun get__kw_o(): IntArray
    fun get__kp_cy(): Char
    fun get__kg_y(): IntArray
    fun get__kg_i(): Array<Long>
    fun get__kv_w(): Array<Array<ByteArray>>
    fun get__lq_z(): Any
    fun get__ls_y(): Sprite
    fun get__lz_u(): RectangleMode
    fun get__lz_w(): Array<ByteArray>
    fun get__lz_l(): IntArray
    fun get__lz_b(): RectangleMode
    fun get__lz_f(): RectangleMode
    fun get__lt_f(): Int
    fun get__lt_u(): Int
    fun get__lt_p(): IntArray
    fun get__lt_y(): IntArray
    fun get__lc_i(): Int
    fun get__lc_o(): Font
    fun get__lv_i(): IntArray
    fun get__lv_k(): IntArray
    fun get__lg_u(): LoginType
    fun get__lg_w(): LoginType
    fun get__lg_b(): LoginType
    fun get__lg_f(): LoginType
    fun get__lg_g(): LoginType
    fun get__lg_h(): LoginType
    fun get__lg_p(): LoginType
    fun get__lg_y(): LoginType
    fun get__lg_z(): LoginType
    fun get__mf_b(): Array<Char>
    fun get__mf_g(): Array<Char>
    fun get__mr_g(): Int
}
