package com.p3achb0t._runestar_interfaces

interface Client : GameShell {
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getEnumType_archive(): AbstractArchive
    fun getEnumType_cached(): EvictingDualNodeHashTable
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_isUsernameRemembered(): Boolean
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getVarbit(id: Int): Int
    fun doAction(ActionParam: Int, widgetID: Int, menuAction: Int, id: Int, menuOption: String, menuTarget: String, mouseX: Int, mouseY: Int)
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__y_fk(): Long
    fun get__w_gz(): Int
    fun get__e_i(): Any
    fun get__e_p(): Any
    fun get__e_w(): Any
    fun get__e_y(): Any
    fun get__e_nn(): Int
    fun get__x_bs(): IndexedSprite
    fun get__a_fh(): Int
    fun get__a_gv(): Sprite
    fun get__d_o(): IndexedSprite
    fun get__c_y(): Int
    fun get__o_ef(): Archive
    fun get__o_i(): Any
    fun get__s_v(): Boolean
    fun get__s_w(): Array<Array<ByteArray>>
    fun get__s_lx(): Component
    fun get__l_qb(): Int
    fun get__z_hi(): Int
    fun get__z_f(): WorldMapSectionType
    fun get__z_i(): WorldMapSectionType
    fun get__z_w(): WorldMapSectionType
    fun get__z_y(): WorldMapSectionType
    fun get__h_dm(): Archive
    fun get__h_qa(): Int
    fun get__q_ei(): Int
    fun get__q_lt(): Int
    fun get__av_ak(): Any
    fun get__av_j(): Array<String>
    fun get__as_p(): DemotingHashTable
    fun get__ak_b(): Int
    fun get__ak_t(): Int
    fun get__ak_d(): Array<IndexedSprite>
    fun get__aq_x(): Array<ShortArray>
    fun get__ao_by(): Array<IndexedSprite>
    fun get__an_a(): Int
    fun get__ar_jp(): Component
    fun get__ar_hq(): Int
    fun get__ac_d(): Int
    fun get__ac_gm(): Sprite
    fun get__aj_ce(): Int
    fun get__aj_cl(): Int
    fun get__aj_cm(): Int
    fun get__aj_cu(): Int
    fun get__aj_cy(): Int
    fun get__aj_cz(): Int
    fun get__aj_ck(): IntArray
    fun get__aj_cr(): IntArray
    fun get__aj_cg(): Array<Char>
    fun get__aj_sz(): Int
    fun get__aj_ct(): IntArray
    fun get__ax_aq(): String
    fun get__af_qn(): Int
    fun get__am_f(): Any
    fun get__am_i(): String
    fun get__bj_ax(): Boolean
    fun get__bj_ag(): String
    fun get__bj_an(): Int
    fun get__bj_c(): Int
    fun get__bj_d(): Int
    fun get__bj_n(): Int
    fun get__bj_o(): Int
    fun get__bj_p(): Int
    fun get__bj_j(): Array<Long>
    fun get__bj_l(): Array<Long>
    fun get__bw_eo(): Int
    fun get__bw_bo(): IndexedSprite
    fun get__bk_x(): Sprite
    fun get__bl_b(): Array<Array<ByteArray>>
    fun get__bl_e(): Array<Array<ByteArray>>
    fun get__bl_p(): Array<Array<ByteArray>>
    fun get__bl_x(): Array<Array<ByteArray>>
    fun get__bl_q(): Int
    fun get__bl_r(): Int
    fun get__bl_v(): IntArray
    fun get__bl_s(): Array<Array<IntArray>>
    fun get__bl_g(): IntArray
    fun get__bl_h(): IntArray
    fun get__bl_m(): IntArray
    fun get__bl_n(): IntArray
    fun get__bl_u(): IntArray
    fun get__bl_z(): IntArray
    fun get__bx_a(): Array<IntArray>
    fun get__bo_bo(): Int
    fun get__bs_bz(): Array<IndexedSprite>
    fun get__bb_rs(): Int
    fun get__bb_eu(): IntArray
    fun get__client_ia(): Int
    fun get__client_sc(): Int
    fun get__client_sw(): OwnWorldComparator
    fun get__client_ab(): Boolean
    fun get__client_ba(): Boolean
    fun get__client_ce(): Boolean
    fun get__client_fy(): Boolean
    fun get__client_hu(): Boolean
    fun get__client_ip(): Boolean
    fun get__client_ir(): Boolean
    fun get__client_jm(): Boolean
    fun get__client_nh(): Boolean
    fun get__client_ni(): Boolean
    fun get__client_qt(): Boolean
    fun get__client_km(): BooleanArray
    fun get__client_ok(): BooleanArray
    fun get__client_on(): BooleanArray
    fun get__client_os(): BooleanArray
    fun get__client_rj(): BooleanArray
    fun get__client_ea(): ByteArray
    fun get__client_mv(): Component
    fun get__client_mw(): Component
    fun get__client_rh(): PlayerAppearance
    fun get__client_cn(): Int
    fun get__client_cx(): Int
    fun get__client_di(): Int
    fun get__client_dr(): Int
    fun get__client_ep(): Int
    fun get__client_er(): Int
    fun get__client_es(): Int
    fun get__client_ff(): Int
    fun get__client_fi(): Int
    fun get__client_fj(): Int
    fun get__client_fn(): Int
    fun get__client_fz(): Int
    fun get__client_ga(): Int
    fun get__client_gt(): Int
    fun get__client_gw(): Int
    fun get__client_hd(): Int
    fun get__client_he(): Int
    fun get__client_hf(): Int
    fun get__client_hj(): Int
    fun get__client_hk(): Int
    fun get__client_hl(): Int
    fun get__client_hm(): Int
    fun get__client_ho(): Int
    fun get__client_ht(): Int
    fun get__client_hw(): Int
    fun get__client_hy(): Int
    fun get__client_hz(): Int
    fun get__client_ic(): Int
    fun get__client_ie(): Int
    fun get__client_ih(): Int
    fun get__client_il(): Int
    fun get__client_im(): Int
    fun get__client_jb(): Int
    fun get__client_jd(): Int
    fun get__client_jh(): Int
    fun get__client_jn(): Int
    fun get__client_jq(): Int
    fun get__client_jx(): Int
    fun get__client_kb(): Int
    fun get__client_kf(): Int
    fun get__client_kk(): Int
    fun get__client_ld(): Int
    fun get__client_ll(): Int
    fun get__client_lm(): Int
    fun get__client_ln(): Int
    fun get__client_lr(): Int
    fun get__client_mj(): Int
    fun get__client_ml(): Int
    fun get__client_mr(): Int
    fun get__client_ms(): Int
    fun get__client_na(): Int
    fun get__client_nc(): Int
    fun get__client_ng(): Int
    fun get__client_nk(): Int
    fun get__client_nm(): Int
    fun get__client_no(): Int
    fun get__client_nq(): Int
    fun get__client_ns(): Int
    fun get__client_nt(): Int
    fun get__client_nu(): Int
    fun get__client_nv(): Int
    fun get__client_nw(): Int
    fun get__client_ny(): Int
    fun get__client_nz(): Int
    fun get__client_ov(): Int
    fun get__client_ph(): Int
    fun get__client_pk(): Int
    fun get__client_pp(): Int
    fun get__client_pr(): Int
    fun get__client_qc(): Int
    fun get__client_qh(): Int
    fun get__client_qk(): Int
    fun get__client_ql(): Int
    fun get__client_ra(): Int
    fun get__client_sm(): Int
    fun get__client_sr(): Int
    fun get__client_sv(): Int
    fun get__client_fe(): IntArray
    fun get__client_ki(): IntArray
    fun get__client_ks(): IntArray
    fun get__client_ne(): IntArray
    fun get__client_np(): IntArray
    fun get__client_nr(): IntArray
    fun get__client_pa(): IntArray
    fun get__client_pe(): IntArray
    fun get__client_pq(): IntArray
    fun get__client_qj(): IntArray
    fun get__client_qw(): IntArray
    fun get__client_qz(): IntArray
    fun get__client_rc(): IntArray
    fun get__client_re(): IntArray
    fun get__client_rw(): IntArray
    fun get__client_ry(): IntArray
    fun get__client_tb(): IntArray
    fun get__client_tr(): IntArray
    fun get__client_pc(): String
    fun get__client_kh(): NodeDeque
    fun get__client_of(): NodeDeque
    fun get__client_oy(): NodeDeque
    fun get__client_ck(): Long
    fun get__client_oa(): Long
    fun get__client_ps(): Long
    fun get__client_po(): Array<Long>
    fun get__client_rb(): Short
    fun get__client_rd(): Short
    fun get__client_ri(): Short
    fun get__client_rl(): Short
    fun get__client_rn(): Short
    fun get__client_ro(): Short
    fun get__client_rt(): Short
    fun get__client_rx(): Short
    fun get__client_gi(): IntArray
    fun get__be_e(): Int
    fun get__be_a(): IntArray
    fun get__be_x(): IntArray
    fun get__bf_f(): Int
    fun get__bt_j(): Boolean
    fun get__bt_n(): Boolean
    fun get__bt_u(): Int
    fun get__bt_x(): IntArray
    fun get__bt_g(): Double
    fun get__bt_l(): Array<String>
    fun get__cd_rm(): Int
    fun get__cd_bj(): String
    fun get__cd_b(): Any
    fun get__cd_p(): Any
    fun get__cj_nd(): Int
    fun get__cq_ap(): Int
    fun get__cq_c(): IntArray
    fun get__cb_f(): Any
    fun get__cb_i(): Any
    fun get__cs_ai(): Boolean
    fun get__cs_am(): Boolean
    fun get__cs_bg(): Boolean
    fun get__cs_bx(): Boolean
    fun get__cs_i(): Boolean
    fun get__cs_d(): UrlRequest
    fun get__cs_ah(): Int
    fun get__cs_ar(): Int
    fun get__cs_as(): Int
    fun get__cs_bb(): Int
    fun get__cs_bh(): Int
    fun get__cs_bn(): Int
    fun get__cs_bw(): Int
    fun get__cs_u(): Int
    fun get__cs_y(): Int
    fun get__cs_bk(): String
    fun get__cs_bl(): String
    fun get__cs_a(): IndexedSprite
    fun get__cs_b(): IndexedSprite
    fun get__cs_k(): IndexedSprite
    fun get__cs_p(): IndexedSprite
    fun get__cs_v(): IndexedSprite
    fun get__cs_w(): Array<IndexedSprite>
    fun get__cs_be(): Long
    fun get__cs_bu(): Long
    fun get__ch_pu(): Boolean
    fun get__cx_w(): ByteArray
    fun get__cx_y(): ByteArray
    fun get__cx_v(): Int
    fun get__cx_x(): Int
    fun get__cx_a(): IntArray
    fun get__cx_k(): IntArray
    fun get__cx_s(): Packet
    fun get__cx_p(): Array<Packet>
    fun get__ck_k(): IntArray
    fun get__cu_z(): Int
    fun get__ci_l(): BooleanArray
    fun get__ci_aa(): Array<Float>
    fun get__ci_av(): Array<Float>
    fun get__ci_aw(): Array<Float>
    fun get__ci_g(): Array<Float>
    fun get__ci_m(): Array<Float>
    fun get__ci_q(): Array<Float>
    fun get__ci_r(): Array<Float>
    fun get__ci_ak(): IntArray
    fun get__ci_as(): IntArray
    fun get__ci_t(): IntArray
    fun get__cv_o(): BooleanArray
    fun get__cv_c(): IntArray
    fun get__cv_d(): IntArray
    fun get__cv_i(): Array<Float>
    fun get__cv_f(): IntArray
    fun get__dk_r(): IntArray
    fun get__dh_x(): Float
    fun get__dh_b(): Array<Array<Float>>
    fun get__dh_a(): Int
    fun get__dh_e(): Array<IntArray>
    fun get__dn_v(): Font
    fun get__dc_cn(): Char
    fun get__dc_so(): Long
    fun get__dd_az(): Int
    fun get__dd_an(): IntArray
    fun get__dd_ar(): IntArray
    fun get__dv_j(): IntArray
    fun get__dv_l(): IntArray
    fun get__dv_n(): IntArray
    fun get__dv_t(): IntArray
    fun get__dv_u(): IntArray
    fun get__dv_h(): Array<IntArray>
    fun get__dv_z(): Array<IntArray>
    fun get__dj_f(): IntArray
    fun get__dj_i(): IntArray
    fun get__dj_w(): IntArray
    fun get__dj_y(): IntArray
    fun get__dw_bz(): Boolean
    fun get__dw_ac(): BooleanArray
    fun get__dw_ag(): BooleanArray
    fun get__dw_ad(): IntArray
    fun get__dw_aj(): IntArray
    fun get__dw_am(): IntArray
    fun get__dw_ap(): IntArray
    fun get__dw_at(): IntArray
    fun get__dw_ax(): IntArray
    fun get__dw_bb(): IntArray
    fun get__dw_bg(): IntArray
    fun get__dw_bj(): IntArray
    fun get__dw_bk(): IntArray
    fun get__dw_bl(): IntArray
    fun get__dw_bn(): IntArray
    fun get__dw_bq(): IntArray
    fun get__dw_bw(): IntArray
    fun get__dw_ab(): Array<IntArray>
    fun get__dw_ai(): Array<IntArray>
    fun get__dz_c(): Int
    fun get__dz_e(): Int
    fun get__dz_p(): Int
    fun get__dz_x(): Int
    fun get__dm_cx(): Int
    fun get__dm_l(): Int
    fun get__dm_fq(): AbstractSocket
    fun get__et_w(): Boolean
    fun get__et_f(): Boolean
    fun get__et_i(): Boolean
    fun get__et_g(): IntArray
    fun get__et_r(): IntArray
    fun get__ej_au(): Boolean
    fun get__ej_az(): Boolean
    fun get__ej_ac(): Int
    fun get__ej_s(): Int
    fun get__ej_ab(): IntArray
    fun get__ej_af(): IntArray
    fun get__ej_ai(): IntArray
    fun get__ej_am(): IntArray
    fun get__ej_ap(): IntArray
    fun get__ej_at(): IntArray
    fun get__ej_bj(): IntArray
    fun get__er_c(): AbstractArchive
    fun get__ex_d(): IntArray
    fun get__ex_e(): Sprite
    fun get__eg_et(): Archive
    fun get__eh_bm(): String
    fun get__eu_k(): Component
    fun get__fy_o(): AbstractArchive
    fun get__fr_p(): Any
    fun get__fg_f(): Boolean
    fun get__fg_y(): Any
    fun get__fa_as(): Any
    fun get__fp_d(): Array<ShortArray>
    fun get__ft_b(): Int
    fun get__ft_a(): IntArray
    fun get__ft_x(): IntArray
    fun get__ft_w(): Array<IntArray>
    fun get__ft_y(): Array<IntArray>
    fun get__fw_a(): ServerProt
    fun get__fw_aa(): ServerProt
    fun get__fw_ab(): ServerProt
    fun get__fw_ac(): ServerProt
    fun get__fw_ad(): ServerProt
    fun get__fw_ae(): ServerProt
    fun get__fw_af(): ServerProt
    fun get__fw_ag(): ServerProt
    fun get__fw_ah(): ServerProt
    fun get__fw_ai(): ServerProt
    fun get__fw_aj(): ServerProt
    fun get__fw_ak(): ServerProt
    fun get__fw_al(): ServerProt
    fun get__fw_am(): ServerProt
    fun get__fw_an(): ServerProt
    fun get__fw_ao(): ServerProt
    fun get__fw_ap(): ServerProt
    fun get__fw_aq(): ServerProt
    fun get__fw_ar(): ServerProt
    fun get__fw_as(): ServerProt
    fun get__fw_at(): ServerProt
    fun get__fw_au(): ServerProt
    fun get__fw_av(): ServerProt
    fun get__fw_aw(): ServerProt
    fun get__fw_ax(): ServerProt
    fun get__fw_ay(): ServerProt
    fun get__fw_az(): ServerProt
    fun get__fw_b(): ServerProt
    fun get__fw_ba(): ServerProt
    fun get__fw_bb(): ServerProt
    fun get__fw_bc(): ServerProt
    fun get__fw_bd(): ServerProt
    fun get__fw_be(): ServerProt
    fun get__fw_bf(): ServerProt
    fun get__fw_bg(): ServerProt
    fun get__fw_bh(): ServerProt
    fun get__fw_bi(): ServerProt
    fun get__fw_bj(): ServerProt
    fun get__fw_bk(): ServerProt
    fun get__fw_bl(): ServerProt
    fun get__fw_bm(): ServerProt
    fun get__fw_bn(): ServerProt
    fun get__fw_bo(): ServerProt
    fun get__fw_bp(): ServerProt
    fun get__fw_bq(): ServerProt
    fun get__fw_br(): ServerProt
    fun get__fw_bs(): ServerProt
    fun get__fw_bt(): ServerProt
    fun get__fw_bu(): ServerProt
    fun get__fw_bv(): ServerProt
    fun get__fw_bw(): ServerProt
    fun get__fw_bx(): ServerProt
    fun get__fw_by(): ServerProt
    fun get__fw_bz(): ServerProt
    fun get__fw_c(): ServerProt
    fun get__fw_cb(): ServerProt
    fun get__fw_cd(): ServerProt
    fun get__fw_cf(): ServerProt
    fun get__fw_cj(): ServerProt
    fun get__fw_co(): ServerProt
    fun get__fw_cp(): ServerProt
    fun get__fw_cq(): ServerProt
    fun get__fw_cs(): ServerProt
    fun get__fw_d(): ServerProt
    fun get__fw_e(): ServerProt
    fun get__fw_f(): ServerProt
    fun get__fw_g(): ServerProt
    fun get__fw_h(): ServerProt
    fun get__fw_i(): ServerProt
    fun get__fw_j(): ServerProt
    fun get__fw_k(): ServerProt
    fun get__fw_l(): ServerProt
    fun get__fw_m(): ServerProt
    fun get__fw_n(): ServerProt
    fun get__fw_o(): ServerProt
    fun get__fw_p(): ServerProt
    fun get__fw_q(): ServerProt
    fun get__fw_r(): ServerProt
    fun get__fw_s(): ServerProt
    fun get__fw_t(): ServerProt
    fun get__fw_u(): ServerProt
    fun get__fw_v(): ServerProt
    fun get__fw_w(): ServerProt
    fun get__fw_x(): ServerProt
    fun get__fw_y(): ServerProt
    fun get__fw_z(): ServerProt
    fun get__fh_a(): ClientProt
    fun get__fh_aa(): ClientProt
    fun get__fh_ab(): ClientProt
    fun get__fh_ac(): ClientProt
    fun get__fh_ad(): ClientProt
    fun get__fh_ae(): ClientProt
    fun get__fh_af(): ClientProt
    fun get__fh_ag(): ClientProt
    fun get__fh_ah(): ClientProt
    fun get__fh_ai(): ClientProt
    fun get__fh_aj(): ClientProt
    fun get__fh_ak(): ClientProt
    fun get__fh_al(): ClientProt
    fun get__fh_am(): ClientProt
    fun get__fh_an(): ClientProt
    fun get__fh_ao(): ClientProt
    fun get__fh_ap(): ClientProt
    fun get__fh_aq(): ClientProt
    fun get__fh_ar(): ClientProt
    fun get__fh_as(): ClientProt
    fun get__fh_at(): ClientProt
    fun get__fh_au(): ClientProt
    fun get__fh_av(): ClientProt
    fun get__fh_aw(): ClientProt
    fun get__fh_ax(): ClientProt
    fun get__fh_ay(): ClientProt
    fun get__fh_az(): ClientProt
    fun get__fh_b(): ClientProt
    fun get__fh_ba(): ClientProt
    fun get__fh_bb(): ClientProt
    fun get__fh_bc(): ClientProt
    fun get__fh_bd(): ClientProt
    fun get__fh_be(): ClientProt
    fun get__fh_bf(): ClientProt
    fun get__fh_bg(): ClientProt
    fun get__fh_bh(): ClientProt
    fun get__fh_bi(): ClientProt
    fun get__fh_bj(): ClientProt
    fun get__fh_bk(): ClientProt
    fun get__fh_bl(): ClientProt
    fun get__fh_bm(): ClientProt
    fun get__fh_bn(): ClientProt
    fun get__fh_bo(): ClientProt
    fun get__fh_bp(): ClientProt
    fun get__fh_bq(): ClientProt
    fun get__fh_br(): ClientProt
    fun get__fh_bs(): ClientProt
    fun get__fh_bt(): ClientProt
    fun get__fh_bu(): ClientProt
    fun get__fh_bw(): ClientProt
    fun get__fh_bx(): ClientProt
    fun get__fh_by(): ClientProt
    fun get__fh_bz(): ClientProt
    fun get__fh_c(): ClientProt
    fun get__fh_ca(): ClientProt
    fun get__fh_cb(): ClientProt
    fun get__fh_cd(): ClientProt
    fun get__fh_ce(): ClientProt
    fun get__fh_cf(): ClientProt
    fun get__fh_cg(): ClientProt
    fun get__fh_ch(): ClientProt
    fun get__fh_ci(): ClientProt
    fun get__fh_cj(): ClientProt
    fun get__fh_ck(): ClientProt
    fun get__fh_cl(): ClientProt
    fun get__fh_cm(): ClientProt
    fun get__fh_cn(): ClientProt
    fun get__fh_co(): ClientProt
    fun get__fh_cp(): ClientProt
    fun get__fh_cq(): ClientProt
    fun get__fh_cr(): ClientProt
    fun get__fh_cs(): ClientProt
    fun get__fh_ct(): ClientProt
    fun get__fh_cu(): ClientProt
    fun get__fh_cx(): ClientProt
    fun get__fh_cy(): ClientProt
    fun get__fh_cz(): ClientProt
    fun get__fh_d(): ClientProt
    fun get__fh_e(): ClientProt
    fun get__fh_f(): ClientProt
    fun get__fh_h(): ClientProt
    fun get__fh_i(): ClientProt
    fun get__fh_j(): ClientProt
    fun get__fh_k(): ClientProt
    fun get__fh_l(): ClientProt
    fun get__fh_m(): ClientProt
    fun get__fh_n(): ClientProt
    fun get__fh_p(): ClientProt
    fun get__fh_q(): ClientProt
    fun get__fh_r(): ClientProt
    fun get__fh_s(): ClientProt
    fun get__fh_t(): ClientProt
    fun get__fh_u(): ClientProt
    fun get__fh_v(): ClientProt
    fun get__fh_w(): ClientProt
    fun get__fh_x(): ClientProt
    fun get__fh_y(): ClientProt
    fun get__fh_z(): ClientProt
    fun get__fh_nf(): Array<Component>
    fun get__fh_bv(): ClientProt
    fun get__fh_g(): ClientProt
    fun get__fh_o(): ClientProt
    fun get__fm_f(): LoginProt
    fun get__fm_w(): LoginProt
    fun get__fm_y(): LoginProt
    fun get__fm_i(): LoginProt
    fun get__fm_p(): LoginProt
    fun get__fm_e(): Array<LoginProt>
    fun get__fz_b(): Int
    fun get__fz_rf(): Int
    fun get__fz_o(): IntArray
    fun get__gf_sb(): Int
    fun get__gf_f(): IntArray
    fun get__gf_ao(): Any
    fun get__gs_hr(): Int
    fun get__gb_ji(): Component
    fun get__gt_dz(): Archive
    fun get__gv_f(): AbstractArchive
    fun get__gv_i(): AbstractArchive
    fun get__gv_y(): AbstractArchive
    fun get__gv_p(): Int
    fun get__gv_v(): Component
    fun get__gv_a(): Int
    fun get__gv_an(): Bounds
    fun get__gr_d(): ByteArray
    fun get__gp_v(): Int
    fun get__gg_y(): AbstractArchive
    fun get__hd_y(): Any
    fun get__hd_bc(): Array<Sprite>
    fun get__hd_i(): Array<String>
    fun get__hd_f(): Array<Array<String>>
    fun get__ht_b(): AbstractArchive
    fun get__hh_e(): ShortArray
    fun get__hh_ge(): Int
    fun get__hh_c(): IntArray
    fun get__hn_f(): ShortArray
    fun get__hn_y(): ShortArray
    fun get__hn_i(): Array<ShortArray>
    fun get__hn_w(): Array<ShortArray>
    fun get__ha_t(): Boolean
    fun get__ha_l(): EvictingDualNodeHashTable
    fun get__ha_v(): EvictingDualNodeHashTable
    fun get__ha_d(): AbstractArchive
    fun get__hg_c(): IndexedSprite
    fun get__hm_ab(): String
    fun get__hm_ac(): String
    fun get__hm_ad(): String
    fun get__hm_ae(): String
    fun get__hm_af(): String
    fun get__hm_ag(): String
    fun get__hm_ai(): String
    fun get__hm_aj(): String
    fun get__hm_al(): String
    fun get__hm_am(): String
    fun get__hm_ap(): String
    fun get__hm_at(): String
    fun get__hm_ax(): String
    fun get__hm_ay(): String
    fun get__hm_ba(): String
    fun get__hm_bb(): String
    fun get__hm_bc(): String
    fun get__hm_bd(): String
    fun get__hm_be(): String
    fun get__hm_bf(): String
    fun get__hm_bg(): String
    fun get__hm_bh(): String
    fun get__hm_bi(): String
    fun get__hm_bj(): String
    fun get__hm_bk(): String
    fun get__hm_bl(): String
    fun get__hm_bm(): String
    fun get__hm_bn(): String
    fun get__hm_bo(): String
    fun get__hm_bp(): String
    fun get__hm_bq(): String
    fun get__hm_br(): String
    fun get__hm_bs(): String
    fun get__hm_bt(): String
    fun get__hm_bu(): String
    fun get__hm_bv(): String
    fun get__hm_bw(): String
    fun get__hm_bx(): String
    fun get__hm_by(): String
    fun get__hm_bz(): String
    fun get__hm_c(): String
    fun get__hm_ca(): String
    fun get__hm_cb(): String
    fun get__hm_cc(): String
    fun get__hm_cd(): String
    fun get__hm_ce(): String
    fun get__hm_cf(): String
    fun get__hm_cg(): String
    fun get__hm_ch(): String
    fun get__hm_ci(): String
    fun get__hm_cj(): String
    fun get__hm_ck(): String
    fun get__hm_cl(): String
    fun get__hm_cm(): String
    fun get__hm_cn(): String
    fun get__hm_co(): String
    fun get__hm_cp(): String
    fun get__hm_cq(): String
    fun get__hm_cr(): String
    fun get__hm_cs(): String
    fun get__hm_ct(): String
    fun get__hm_cu(): String
    fun get__hm_cv(): String
    fun get__hm_cw(): String
    fun get__hm_cx(): String
    fun get__hm_cy(): String
    fun get__hm_cz(): String
    fun get__hm_d(): String
    fun get__hm_da(): String
    fun get__hm_db(): String
    fun get__hm_dc(): String
    fun get__hm_de(): String
    fun get__hm_df(): String
    fun get__hm_dg(): String
    fun get__hm_dh(): String
    fun get__hm_di(): String
    fun get__hm_dj(): String
    fun get__hm_dk(): String
    fun get__hm_dl(): String
    fun get__hm_dm(): String
    fun get__hm_dn(): String
    fun get__hm_do(): String
    fun get__hm_dp(): String
    fun get__hm_dr(): String
    fun get__hm_ds(): String
    fun get__hm_dt(): String
    fun get__hm_du(): String
    fun get__hm_dv(): String
    fun get__hm_dw(): String
    fun get__hm_dx(): String
    fun get__hm_dy(): String
    fun get__hm_dz(): String
    fun get__hm_ea(): String
    fun get__hm_ec(): String
    fun get__hm_ee(): String
    fun get__hm_ef(): String
    fun get__hm_eg(): String
    fun get__hm_eh(): String
    fun get__hm_ei(): String
    fun get__hm_ej(): String
    fun get__hm_ek(): String
    fun get__hm_el(): String
    fun get__hm_en(): String
    fun get__hm_eo(): String
    fun get__hm_ep(): String
    fun get__hm_eq(): String
    fun get__hm_er(): String
    fun get__hm_es(): String
    fun get__hm_et(): String
    fun get__hm_eu(): String
    fun get__hm_ev(): String
    fun get__hm_ew(): String
    fun get__hm_ex(): String
    fun get__hm_fb(): String
    fun get__hm_fg(): String
    fun get__hm_fj(): String
    fun get__hm_fl(): String
    fun get__hm_fr(): String
    fun get__hm_fs(): String
    fun get__hm_ft(): String
    fun get__hm_fu(): String
    fun get__hm_fx(): String
    fun get__hm_fz(): String
    fun get__hm_ga(): String
    fun get__hm_gb(): String
    fun get__hm_gc(): String
    fun get__hm_gd(): String
    fun get__hm_ge(): String
    fun get__hm_gf(): String
    fun get__hm_gg(): String
    fun get__hm_gh(): String
    fun get__hm_gi(): String
    fun get__hm_gj(): String
    fun get__hm_gk(): String
    fun get__hm_gl(): String
    fun get__hm_gm(): String
    fun get__hm_gn(): String
    fun get__hm_go(): String
    fun get__hm_gp(): String
    fun get__hm_gq(): String
    fun get__hm_gr(): String
    fun get__hm_gs(): String
    fun get__hm_gt(): String
    fun get__hm_gu(): String
    fun get__hm_gv(): String
    fun get__hm_gw(): String
    fun get__hm_gx(): String
    fun get__hm_gy(): String
    fun get__hm_gz(): String
    fun get__hm_ha(): String
    fun get__hm_hd(): String
    fun get__hm_he(): String
    fun get__hm_hh(): String
    fun get__hm_hj(): String
    fun get__hm_hn(): String
    fun get__hm_ho(): String
    fun get__hm_hq(): String
    fun get__hm_hr(): String
    fun get__hm_ht(): String
    fun get__hm_hu(): String
    fun get__hm_hx(): String
    fun get__hm_hy(): String
    fun get__hm_hz(): String
    fun get__hm_ia(): String
    fun get__hm_ib(): String
    fun get__hm_ic(): String
    fun get__hm_id(): String
    fun get__hm_ie(): String
    fun get__hm_if(): String
    fun get__hm_ig(): String
    fun get__hm_ii(): String
    fun get__hm_ik(): String
    fun get__hm_im(): String
    fun get__hm_in(): String
    fun get__hm_ip(): String
    fun get__hm_iq(): String
    fun get__hm_is(): String
    fun get__hm_it(): String
    fun get__hm_iv(): String
    fun get__hm_iw(): String
    fun get__hm_iz(): String
    fun get__hm_ja(): String
    fun get__hm_jb(): String
    fun get__hm_jc(): String
    fun get__hm_jd(): String
    fun get__hm_je(): String
    fun get__hm_jf(): String
    fun get__hm_jg(): String
    fun get__hm_jh(): String
    fun get__hm_ji(): String
    fun get__hm_jj(): String
    fun get__hm_jk(): String
    fun get__hm_jl(): String
    fun get__hm_jm(): String
    fun get__hm_jn(): String
    fun get__hm_jo(): String
    fun get__hm_jp(): String
    fun get__hm_jq(): String
    fun get__hm_jr(): String
    fun get__hm_js(): String
    fun get__hm_jt(): String
    fun get__hm_ju(): String
    fun get__hm_jv(): String
    fun get__hm_jw(): String
    fun get__hm_jx(): String
    fun get__hm_jy(): String
    fun get__hm_jz(): String
    fun get__hm_ka(): String
    fun get__hm_kd(): String
    fun get__hm_ke(): String
    fun get__hm_kf(): String
    fun get__hm_kh(): String
    fun get__hm_ki(): String
    fun get__hm_kk(): String
    fun get__hm_kl(): String
    fun get__hm_km(): String
    fun get__hm_kn(): String
    fun get__hm_ko(): String
    fun get__hm_kq(): String
    fun get__hm_kr(): String
    fun get__hm_ks(): String
    fun get__hm_kt(): String
    fun get__hm_kv(): String
    fun get__hm_x(): String
    fun get__hm_az(): String
    fun get__hi_f(): ServerBuild
    fun get__hi_i(): ServerBuild
    fun get__hi_w(): ServerBuild
    fun get__hi_y(): ServerBuild
    fun get__hq_b(): StudioGame
    fun get__hq_f(): StudioGame
    fun get__hq_i(): StudioGame
    fun get__hq_p(): StudioGame
    fun get__hq_w(): StudioGame
    fun get__hq_y(): StudioGame
    fun get__ho_cv(): Boolean
    fun get__hz_j(): Int
    fun get__ih_y(): Int
    fun get__ie_h(): Byte
    fun get__ie_i(): Int
    fun get__ie_t(): Int
    fun get__ie_y(): Long
    fun get__ic_a(): IntArray
    fun get__ip_i(): EvictingDualNodeHashTable
    fun get__ip_f(): AbstractArchive
    fun get__im_i(): Int
    fun get__im_f(): AbstractArchive
    fun get__it_f(): AbstractArchive
    fun get__ir_f(): AbstractArchive
    fun get__ir_i(): EvictingDualNodeHashTable
    fun get__il_bm(): Array<IndexedSprite>
    fun get__iy_i(): EvictingDualNodeHashTable
    fun get__iy_f(): AbstractArchive
    fun get__ix_i(): AbstractArchive
    fun get__io_f(): AbstractArchive
    fun get__io_i(): AbstractArchive
    fun get__iu_o(): Int
    fun get__ij_f(): AbstractArchive
    fun get__ij_d(): Int
    fun get__is_i(): EvictingDualNodeHashTable
    fun get__is_f(): AbstractArchive
    fun get__id_p(): EvictingDualNodeHashTable
    fun get__id_f(): AbstractArchive
    fun get__id_i(): AbstractArchive
    fun get__id_qv(): Int
    fun get__ig_x(): Array<UnlitModel>
    fun get__ig_b(): EvictingDualNodeHashTable
    fun get__ii_a(): Int
    fun get__ii_x(): Boolean
    fun get__ib_i(): EvictingDualNodeHashTable
    fun get__ib_f(): AbstractArchive
    fun get__iv_i(): AbstractArchive
    fun get__iv_y(): AbstractArchive
    fun get__iv_p(): EvictingDualNodeHashTable
    fun get__iv_qi(): Int
    fun get__jn_ab(): Int
    fun get__jh_ao(): Bounds
    fun get__jz_p(): Int
    fun get__jz_x(): IntArray
    fun get__jp_sf(): ShortArray
    fun get__jd_ex(): Int
    fun get__jd_fm(): Int
    fun get__ju_af(): Int
    fun get__jb_ba(): IndexedSprite
    fun get__je_rq(): Int
    fun get__ke_i(): Array<Long>
    fun get__kr_f(): Array<Char>
    fun get__kr_i(): Array<Char>
    fun get__kr_y(): Array<Char>
    fun get__kr_w(): IntArray
    fun get__kf_a(): Array<ByteArray>
    fun get__kq_x(): IntArray
    fun get__kq_d(): Array<Long>
    fun get__kj_a(): Array<Array<ByteArray>>
    fun get__kj_e(): IntArray
    fun get__lf_b(): IntArray
    fun get__lg_f(): RectangleMode
    fun get__lg_i(): RectangleMode
    fun get__lg_y(): RectangleMode
    fun get__lz_f(): Int
    fun get__lz_i(): Int
    fun get__lz_y(): Int
    fun get__lz_e(): IntArray
    fun get__lz_p(): IntArray
    fun get__lz_w(): IntArray
    fun get__lq_a(): ShortArray
    fun get__lt_c(): IntArray
    fun get__lt_d(): IntArray
    fun get__ll_a(): LoginType
    fun get__ll_f(): LoginType
    fun get__ll_b(): LoginType
    fun get__ll_e(): LoginType
    fun get__ll_i(): LoginType
    fun get__ll_p(): LoginType
    fun get__ll_w(): LoginType
    fun get__ll_x(): LoginType
    fun get__ll_y(): LoginType
    fun get__mj_w(): Array<Char>
    fun get__mj_y(): Array<Char>
    fun get__mg_w(): Int
}
