package com.p3achb0t._runestar_interfaces

interface Client : GameShell {
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getEnumType_archive(): AbstractArchive
    fun getEnumType_cached(): EvictingDualNodeHashTable
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getVarbit(id: Int): Int
    fun doAction(actionParam: Int, widgetID: Int, menuAction: Int, id: Int, menuOption: String, menuTarget: String, mouseX: Int, mouseY: Int, dummy: Int=0)
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__d_cx(): Int
    fun get__d_t(): IndexedSprite
    fun get__w_t(): Array<ByteArray>
    fun get__w_rv(): Int
    fun get__w_s(): IndexedSprite
    fun get__z_eu(): Int
    fun get__z_ml(): Int
    fun get__t_g(): Int
    fun get__h_rb(): Int
    fun get__g_d(): Any
    fun get__g_k(): Any
    fun get__g_m(): Any
    fun get__g_w(): Any
    fun get__g_nl(): Array<Component>
    fun get__g_er(): Int
    fun get__i_e(): Int
    fun get__i_bt(): Array<IndexedSprite>
    fun get__a_gy(): Int
    fun get__r_u(): Component
    fun get__r_gp(): Sprite
    fun get__o_e(): IntArray
    fun get__j_s(): Int
    fun get__y_y(): IntArray
    fun get__y_br(): String
    fun get__f_et(): Archive
    fun get__ae_ad(): Int
    fun get__ae_p(): IndexedSprite
    fun get__ap_d(): WorldMapSectionType
    fun get__ap_k(): WorldMapSectionType
    fun get__ap_m(): WorldMapSectionType
    fun get__ap_x(): WorldMapSectionType
    fun get__ar_rt(): Int
    fun get__al_no(): Int
    fun get__al_bh(): Array<IndexedSprite>
    fun get__as_al(): Any
    fun get__au_q(): ShortArray
    fun get__ao_w(): DemotingHashTable
    fun get__av_jh(): Component
    fun get__ak_al(): Bounds
    fun get__ax_sq(): Int
    fun get__az_aq(): String
    fun get__ag_sr(): ShortArray
    fun get__aw_n(): Font
    fun get__aw_h(): Array<Array<IntArray>>
    fun get__bf_ef(): Int
    fun get__bo_ca(): Int
    fun get__bo_cf(): Int
    fun get__bo_ci(): Int
    fun get__bo_cj(): Int
    fun get__bo_cp(): Int
    fun get__bo_cz(): Int
    fun get__bo_cn(): IntArray
    fun get__bo_ct(): IntArray
    fun get__bo_cb(): Array<Char>
    fun get__bo_cy(): IntArray
    fun get__be_x(): AbstractArchive
    fun get__bt_x(): Any
    fun get__bt_m(): String
    fun get__bt_g(): Int
    fun get__br_aj(): Boolean
    fun get__br_h(): Array<Long>
    fun get__br_i(): Array<Long>
    fun get__br_as(): Int
    fun get__br_d(): Int
    fun get__br_e(): Int
    fun get__br_s(): Int
    fun get__bq_ge(): Int
    fun get__ba_d(): Array<Array<ByteArray>>
    fun get__ba_q(): Array<Array<ByteArray>>
    fun get__ba_v(): Array<Array<ByteArray>>
    fun get__ba_f(): Int
    fun get__ba_y(): Int
    fun get__ba_n(): IntArray
    fun get__ba_t(): Array<IntArray>
    fun get__ba_b(): IntArray
    fun get__ba_c(): IntArray
    fun get__ba_j(): IntArray
    fun get__ba_l(): IntArray
    fun get__ba_o(): IntArray
    fun get__ba_r(): IntArray
    fun get__bs_bq(): IndexedSprite
    fun get__bp_gx(): Int
    fun get__bp_bg(): Array<Sprite>
    fun get__by_at(): String
    fun get__bl_n(): Boolean
    fun get__bl_v(): IndexedSprite
    fun get__eg(): Packet
    fun get__client_su(): Int
    fun get__client_sk(): OwnWorldComparator
    fun get__client_aw(): Boolean
    fun get__client_bv(): Boolean
    fun get__client_cy(): Boolean
    fun get__client_ez(): Boolean
    fun get__client_ft(): Boolean
    fun get__client_hb(): Boolean
    fun get__client_in(): Boolean
    fun get__client_iq(): Boolean
    fun get__client_jf(): Boolean
    fun get__client_na(): Boolean
    fun get__client_ns(): Boolean
    fun get__client_qn(): Boolean
    fun get__client_kf(): BooleanArray
    fun get__client_oa(): BooleanArray
    fun get__client_ok(): BooleanArray
    fun get__client_ou(): BooleanArray
    fun get__client_rq(): BooleanArray
    fun get__client_fk(): ByteArray
    fun get__client_md(): Component
    fun get__client_ni(): Component
    fun get__client_so(): PlayerAppearance
    fun get__client_ci(): Int
    fun get__client_cz(): Int
    fun get__client_db(): Int
    fun get__client_dm(): Int
    fun get__client_ec(): Int
    fun get__client_en(): Int
    fun get__client_ev(): Int
    fun get__client_fi(): Int
    fun get__client_fu(): Int
    fun get__client_ga(): Int
    fun get__client_gj(): Int
    fun get__client_gt(): Int
    fun get__client_gu(): Int
    fun get__client_gw(): Int
    fun get__client_gz(): Int
    fun get__client_ha(): Int
    fun get__client_hd(): Int
    fun get__client_hi(): Int
    fun get__client_hl(): Int
    fun get__client_ho(): Int
    fun get__client_hq(): Int
    fun get__client_hr(): Int
    fun get__client_hv(): Int
    fun get__client_hw(): Int
    fun get__client_hx(): Int
    fun get__client_ia(): Int
    fun get__client_ie(): Int
    fun get__client_ig(): Int
    fun get__client_ih(): Int
    fun get__client_ii(): Int
    fun get__client_ik(): Int
    fun get__client_ip(): Int
    fun get__client_ir(): Int
    fun get__client_iv(): Int
    fun get__client_ja(): Int
    fun get__client_jg(): Int
    fun get__client_jk(): Int
    fun get__client_jp(): Int
    fun get__client_jt(): Int
    fun get__client_kk(): Int
    fun get__client_kn(): Int
    fun get__client_kt(): Int
    fun get__client_le(): Int
    fun get__client_lk(): Int
    fun get__client_lp(): Int
    fun get__client_lu(): Int
    fun get__client_me(): Int
    fun get__client_mj(): Int
    fun get__client_mk(): Int
    fun get__client_mp(): Int
    fun get__client_mv(): Int
    fun get__client_mw(): Int
    fun get__client_nh(): Int
    fun get__client_nj(): Int
    fun get__client_nk(): Int
    fun get__client_nt(): Int
    fun get__client_nu(): Int
    fun get__client_nv(): Int
    fun get__client_nx(): Int
    fun get__client_ny(): Int
    fun get__client_oe(): Int
    fun get__client_oh(): Int
    fun get__client_oi(): Int
    fun get__client_om(): Int
    fun get__client_oo(): Int
    fun get__client_or(): Int
    fun get__client_os(): Int
    fun get__client_pa(): Int
    fun get__client_ph(): Int
    fun get__client_pu(): Int
    fun get__client_pz(): Int
    fun get__client_qc(): Int
    fun get__client_qv(): Int
    fun get__client_qy(): Int
    fun get__client_qz(): Int
    fun get__client_rj(): Int
    fun get__client_se(): Int
    fun get__client_sn(): Int
    fun get__client_sv(): Int
    fun get__client_fv(): IntArray
    fun get__client_kg(): IntArray
    fun get__client_kq(): IntArray
    fun get__client_nb(): IntArray
    fun get__client_nm(): IntArray
    fun get__client_nr(): IntArray
    fun get__client_pi(): IntArray
    fun get__client_pk(): IntArray
    fun get__client_pw(): IntArray
    fun get__client_qf(): IntArray
    fun get__client_qm(): IntArray
    fun get__client_qp(): IntArray
    fun get__client_rp(): IntArray
    fun get__client_rs(): IntArray
    fun get__client_ru(): IntArray
    fun get__client_rz(): IntArray
    fun get__client_tj(): IntArray
    fun get__client_tk(): IntArray
    fun get__client_pt(): String
    fun get__client_kp(): NodeDeque
    fun get__client_of(): NodeDeque
    fun get__client_ox(): NodeDeque
    fun get__client_cb(): Long
    fun get__client_od(): Long
    fun get__client_pe(): Long
    fun get__client_pp(): Array<Long>
    fun get__client_ra(): Short
    fun get__client_rd(): Short
    fun get__client_rg(): Short
    fun get__client_rk(): Short
    fun get__client_rm(): Short
    fun get__client_rn(): Short
    fun get__client_rr(): Short
    fun get__client_rw(): Short
    fun get__client_gl(): IntArray
    fun get__ch_q(): Int
    fun get__ch_t(): IntArray
    fun get__ch_z(): IntArray
    fun get__cr_ap(): Any
    fun get__cq_a(): Int
    fun get__cq_x(): Int
    fun get__co_u(): IntArray
    fun get__cu_a(): Boolean
    fun get__cu_b(): Boolean
    fun get__cu_n(): Component
    fun get__cu_l(): Int
    fun get__cu_j(): Double
    fun get__cu_g(): Array<String>
    fun get__cs_aw(): Int
    fun get__cg_rf(): Int
    fun get__cx_v(): Any
    fun get__cx_w(): Any
    fun get__ci_eh(): Archive
    fun get__cz_k(): AbstractArchive
    fun get__cz_w(): Any
    fun get__cz_ba(): IndexedSprite
    fun get__cz_m(): Any
    fun get__cz_x(): Any
    fun get__cb_e(): Int
    fun get__cb_n(): Int
    fun get__cy_ag(): Boolean
    fun get__cy_ah(): Boolean
    fun get__cy_bc(): Boolean
    fun get__cy_be(): Boolean
    fun get__cy_m(): Boolean
    fun get__cy_af(): Int
    fun get__cy_am(): Int
    fun get__cy_ap(): Int
    fun get__cy_bo(): Int
    fun get__cy_bs(): Int
    fun get__cy_bx(): Int
    fun get__cy_bz(): Int
    fun get__cy_k(): Int
    fun get__cy_l(): Int
    fun get__cy_bd(): String
    fun get__cy_bk(): String
    fun get__cy_q(): Sprite
    fun get__cy_n(): IndexedSprite
    fun get__cy_u(): IndexedSprite
    fun get__cy_d(): Array<IndexedSprite>
    fun get__cy_bb(): Long
    fun get__cy_bm(): Long
    fun get__cj_d(): ByteArray
    fun get__cj_k(): ByteArray
    fun get__cj_n(): Int
    fun get__cj_rh(): Int
    fun get__cj_z(): Int
    fun get__cj_t(): IntArray
    fun get__cj_u(): IntArray
    fun get__cj_h(): Packet
    fun get__cj_w(): Array<Packet>
    fun get__cl_go(): Sprite
    fun get__cl_fc(): Long
    fun get__dv_r(): Int
    fun get__dd_ew(): IntArray
    fun get__dl_g(): BooleanArray
    fun get__dl_ae(): Array<Float>
    fun get__dl_ai(): Array<Float>
    fun get__dl_an(): Array<Float>
    fun get__dl_c(): Array<Float>
    fun get__dl_f(): Array<Float>
    fun get__dl_j(): Array<Float>
    fun get__dl_y(): Array<Float>
    fun get__dl_ab(): IntArray
    fun get__dl_ap(): IntArray
    fun get__dl_i(): IntArray
    fun get__db_p(): BooleanArray
    fun get__db_e(): IntArray
    fun get__db_s(): IntArray
    fun get__db_m(): Array<Float>
    fun get__db_x(): IntArray
    fun get__dh_ij(): Int
    fun get__dh_e(): AbstractArchive
    fun get__dk_z(): Array<Array<ByteArray>>
    fun get__dc_z(): Float
    fun get__dc_v(): Array<Array<Float>>
    fun get__dc_t(): Int
    fun get__dc_q(): Array<IntArray>
    fun get__di_rl(): Int
    fun get__di_sy(): Int
    fun get__ea_au(): Int
    fun get__ea_am(): IntArray
    fun get__ea_as(): IntArray
    fun get__ex_a(): IntArray
    fun get__ex_b(): IntArray
    fun get__ex_g(): IntArray
    fun get__ex_i(): IntArray
    fun get__ex_l(): IntArray
    fun get__ex_o(): Array<IntArray>
    fun get__ex_r(): Array<IntArray>
    fun get__eh_d(): IntArray
    fun get__eh_k(): IntArray
    fun get__eh_m(): IntArray
    fun get__eh_x(): IntArray
    fun get__el_bh(): Boolean
    fun get__el_aq(): BooleanArray
    fun get__el_av(): BooleanArray
    fun get__el_ac(): IntArray
    fun get__el_ag(): IntArray
    fun get__el_aj(): IntArray
    fun get__el_ax(): IntArray
    fun get__el_ay(): IntArray
    fun get__el_az(): IntArray
    fun get__el_bc(): IntArray
    fun get__el_bd(): IntArray
    fun get__el_bf(): IntArray
    fun get__el_bk(): IntArray
    fun get__el_bo(): IntArray
    fun get__el_bu(): IntArray
    fun get__el_bx(): IntArray
    fun get__el_bz(): IntArray
    fun get__el_ah(): Array<IntArray>
    fun get__el_aw(): Array<IntArray>
    fun get__ei_p(): Int
    fun get__ei_w(): Int
    fun get__ei_z(): Int
    fun get__en_z(): Array<ShortArray>
    fun get__ec_d(): Boolean
    fun get__ec_m(): Boolean
    fun get__ec_x(): Boolean
    fun get__ec_j(): IntArray
    fun get__ec_y(): IntArray
    fun get__ev_sl(): Long
    fun get__ej_ar(): Boolean
    fun get__ej_au(): Boolean
    fun get__ej_av(): Int
    fun get__ej_h(): Int
    fun get__ej_ac(): IntArray
    fun get__ej_ad(): IntArray
    fun get__ej_ag(): IntArray
    fun get__ej_ah(): IntArray
    fun get__ej_aw(): IntArray
    fun get__ej_ay(): IntArray
    fun get__ej_bf(): IntArray
    fun get__ed_t(): Int
    fun get__ed_w(): IndexedSprite
    fun get__ey_fx(): AbstractSocket
    fun get__fd_eo(): Archive
    fun get__fx_s(): IntArray
    fun get__fu_z(): Boolean
    fun get__fz_em(): Int
    fun get__fz_bf(): String
    fun get__fe_x(): Boolean
    fun get__fe_m(): Any
    fun get__fe_k(): Any
    fun get__fb_t(): Int
    fun get__gg_v(): Int
    fun get__gg_t(): IntArray
    fun get__gg_z(): IntArray
    fun get__gg_d(): Array<IntArray>
    fun get__gg_k(): Array<IntArray>
    fun get__gx_jz(): Component
    fun get__gv_a(): ServerProt
    fun get__gv_aa(): ServerProt
    fun get__gv_ab(): ServerProt
    fun get__gv_ac(): ServerProt
    fun get__gv_ad(): ServerProt
    fun get__gv_ae(): ServerProt
    fun get__gv_af(): ServerProt
    fun get__gv_ag(): ServerProt
    fun get__gv_ah(): ServerProt
    fun get__gv_ai(): ServerProt
    fun get__gv_aj(): ServerProt
    fun get__gv_ak(): ServerProt
    fun get__gv_al(): ServerProt
    fun get__gv_am(): ServerProt
    fun get__gv_an(): ServerProt
    fun get__gv_ao(): ServerProt
    fun get__gv_ap(): ServerProt
    fun get__gv_aq(): ServerProt
    fun get__gv_ar(): ServerProt
    fun get__gv_as(): ServerProt
    fun get__gv_at(): ServerProt
    fun get__gv_au(): ServerProt
    fun get__gv_av(): ServerProt
    fun get__gv_aw(): ServerProt
    fun get__gv_ax(): ServerProt
    fun get__gv_ay(): ServerProt
    fun get__gv_az(): ServerProt
    fun get__gv_b(): ServerProt
    fun get__gv_ba(): ServerProt
    fun get__gv_bb(): ServerProt
    fun get__gv_bc(): ServerProt
    fun get__gv_bd(): ServerProt
    fun get__gv_be(): ServerProt
    fun get__gv_bf(): ServerProt
    fun get__gv_bg(): ServerProt
    fun get__gv_bh(): ServerProt
    fun get__gv_bi(): ServerProt
    fun get__gv_bj(): ServerProt
    fun get__gv_bk(): ServerProt
    fun get__gv_bl(): ServerProt
    fun get__gv_bm(): ServerProt
    fun get__gv_bn(): ServerProt
    fun get__gv_bo(): ServerProt
    fun get__gv_bp(): ServerProt
    fun get__gv_bq(): ServerProt
    fun get__gv_br(): ServerProt
    fun get__gv_bs(): ServerProt
    fun get__gv_bt(): ServerProt
    fun get__gv_bu(): ServerProt
    fun get__gv_bv(): ServerProt
    fun get__gv_bw(): ServerProt
    fun get__gv_bx(): ServerProt
    fun get__gv_by(): ServerProt
    fun get__gv_bz(): ServerProt
    fun get__gv_c(): ServerProt
    fun get__gv_cc(): ServerProt
    fun get__gv_ch(): ServerProt
    fun get__gv_cm(): ServerProt
    fun get__gv_co(): ServerProt
    fun get__gv_cq(): ServerProt
    fun get__gv_cr(): ServerProt
    fun get__gv_cu(): ServerProt
    fun get__gv_cw(): ServerProt
    fun get__gv_d(): ServerProt
    fun get__gv_e(): ServerProt
    fun get__gv_f(): ServerProt
    fun get__gv_g(): ServerProt
    fun get__gv_h(): ServerProt
    fun get__gv_i(): ServerProt
    fun get__gv_j(): ServerProt
    fun get__gv_k(): ServerProt
    fun get__gv_l(): ServerProt
    fun get__gv_m(): ServerProt
    fun get__gv_n(): ServerProt
    fun get__gv_o(): ServerProt
    fun get__gv_p(): ServerProt
    fun get__gv_q(): ServerProt
    fun get__gv_r(): ServerProt
    fun get__gv_s(): ServerProt
    fun get__gv_t(): ServerProt
    fun get__gv_u(): ServerProt
    fun get__gv_v(): ServerProt
    fun get__gv_w(): ServerProt
    fun get__gv_x(): ServerProt
    fun get__gv_y(): ServerProt
    fun get__gv_z(): ServerProt
    fun get__gv_ic(): Int
    fun get__gn_a(): ClientProt
    fun get__gn_aa(): ClientProt
    fun get__gn_ab(): ClientProt
    fun get__gn_ac(): ClientProt
    fun get__gn_ad(): ClientProt
    fun get__gn_ae(): ClientProt
    fun get__gn_af(): ClientProt
    fun get__gn_ag(): ClientProt
    fun get__gn_ah(): ClientProt
    fun get__gn_ai(): ClientProt
    fun get__gn_aj(): ClientProt
    fun get__gn_ak(): ClientProt
    fun get__gn_al(): ClientProt
    fun get__gn_am(): ClientProt
    fun get__gn_an(): ClientProt
    fun get__gn_ao(): ClientProt
    fun get__gn_ap(): ClientProt
    fun get__gn_aq(): ClientProt
    fun get__gn_ar(): ClientProt
    fun get__gn_as(): ClientProt
    fun get__gn_at(): ClientProt
    fun get__gn_au(): ClientProt
    fun get__gn_av(): ClientProt
    fun get__gn_aw(): ClientProt
    fun get__gn_ax(): ClientProt
    fun get__gn_ay(): ClientProt
    fun get__gn_az(): ClientProt
    fun get__gn_b(): ClientProt
    fun get__gn_ba(): ClientProt
    fun get__gn_bb(): ClientProt
    fun get__gn_bc(): ClientProt
    fun get__gn_bd(): ClientProt
    fun get__gn_be(): ClientProt
    fun get__gn_bf(): ClientProt
    fun get__gn_bg(): ClientProt
    fun get__gn_bh(): ClientProt
    fun get__gn_bi(): ClientProt
    fun get__gn_bj(): ClientProt
    fun get__gn_bk(): ClientProt
    fun get__gn_bl(): ClientProt
    fun get__gn_bm(): ClientProt
    fun get__gn_bn(): ClientProt
    fun get__gn_bo(): ClientProt
    fun get__gn_bp(): ClientProt
    fun get__gn_bq(): ClientProt
    fun get__gn_br(): ClientProt
    fun get__gn_bs(): ClientProt
    fun get__gn_bt(): ClientProt
    fun get__gn_bu(): ClientProt
    fun get__gn_bw(): ClientProt
    fun get__gn_bx(): ClientProt
    fun get__gn_by(): ClientProt
    fun get__gn_bz(): ClientProt
    fun get__gn_c(): ClientProt
    fun get__gn_ca(): ClientProt
    fun get__gn_cb(): ClientProt
    fun get__gn_cc(): ClientProt
    fun get__gn_cd(): ClientProt
    fun get__gn_cf(): ClientProt
    fun get__gn_cg(): ClientProt
    fun get__gn_ch(): ClientProt
    fun get__gn_ci(): ClientProt
    fun get__gn_cj(): ClientProt
    fun get__gn_cm(): ClientProt
    fun get__gn_cn(): ClientProt
    fun get__gn_cp(): ClientProt
    fun get__gn_cq(): ClientProt
    fun get__gn_cr(): ClientProt
    fun get__gn_cs(): ClientProt
    fun get__gn_ct(): ClientProt
    fun get__gn_cu(): ClientProt
    fun get__gn_cw(): ClientProt
    fun get__gn_cx(): ClientProt
    fun get__gn_cy(): ClientProt
    fun get__gn_cz(): ClientProt
    fun get__gn_d(): ClientProt
    fun get__gn_e(): ClientProt
    fun get__gn_f(): ClientProt
    fun get__gn_g(): ClientProt
    fun get__gn_h(): ClientProt
    fun get__gn_i(): ClientProt
    fun get__gn_j(): ClientProt
    fun get__gn_k(): ClientProt
    fun get__gn_l(): ClientProt
    fun get__gn_m(): ClientProt
    fun get__gn_n(): ClientProt
    fun get__gn_o(): ClientProt
    fun get__gn_p(): ClientProt
    fun get__gn_q(): ClientProt
    fun get__gn_r(): ClientProt
    fun get__gn_s(): ClientProt
    fun get__gn_t(): ClientProt
    fun get__gn_u(): ClientProt
    fun get__gn_v(): ClientProt
    fun get__gn_w(): ClientProt
    fun get__gn_x(): ClientProt
    fun get__gn_y(): ClientProt
    fun get__gn_z(): ClientProt
    fun get__gn_bv(): ClientProt
    fun get__gn_ck(): ClientProt
    fun get__gn_co(): ClientProt
    fun get__gb_d(): LoginProt
    fun get__gb_k(): LoginProt
    fun get__gb_w(): LoginProt
    fun get__gb_x(): LoginProt
    fun get__gb_e(): UrlRequest
    fun get__gb_m(): LoginProt
    fun get__gb_v(): LoginProt
    fun get__gb_z(): Array<LoginProt>
    fun get__gq_v(): Int
    fun get__gs_x(): IntArray
    fun get__gl_lr(): Component
    fun get__gr_w(): Int
    fun get__gr_k(): AbstractArchive
    fun get__gr_m(): AbstractArchive
    fun get__gr_v(): AbstractArchive
    fun get__hc_e(): ByteArray
    fun get__hs_as(): Bounds
    fun get__hl_z(): Sprite
    fun get__hq_k(): Any
    fun get__hq_m(): Array<String>
    fun get__hq_x(): Array<Array<String>>
    fun get__hw_dd(): Boolean
    fun get__hd_t(): Int
    fun get__hd_ac(): Int
    fun get__ht_s(): AbstractArchive
    fun get__hj_cd(): Char
    fun get__hj_w(): Int
    fun get__hk_t(): ShortArray
    fun get__hk_e(): Array<ShortArray>
    fun get__hk_s(): IntArray
    fun get__hm_k(): ShortArray
    fun get__hm_x(): ShortArray
    fun get__hm_d(): Array<ShortArray>
    fun get__hm_m(): Array<ShortArray>
    fun get__he_i(): Boolean
    fun get__he_g(): EvictingDualNodeHashTable
    fun get__he_n(): EvictingDualNodeHashTable
    fun get__he_p(): AbstractArchive
    fun get__hx_aa(): String
    fun get__hx_ac(): String
    fun get__hx_ad(): String
    fun get__hx_ag(): String
    fun get__hx_ah(): String
    fun get__hx_aj(): String
    fun get__hx_ak(): String
    fun get__hx_ao(): String
    fun get__hx_aq(): String
    fun get__hx_av(): String
    fun get__hx_aw(): String
    fun get__hx_ax(): String
    fun get__hx_ay(): String
    fun get__hx_az(): String
    fun get__hx_ba(): String
    fun get__hx_bb(): String
    fun get__hx_bc(): String
    fun get__hx_bd(): String
    fun get__hx_be(): String
    fun get__hx_bf(): String
    fun get__hx_bg(): String
    fun get__hx_bh(): String
    fun get__hx_bi(): String
    fun get__hx_bj(): String
    fun get__hx_bk(): String
    fun get__hx_bl(): String
    fun get__hx_bm(): String
    fun get__hx_bn(): String
    fun get__hx_bo(): String
    fun get__hx_bp(): String
    fun get__hx_bq(): String
    fun get__hx_br(): String
    fun get__hx_bs(): String
    fun get__hx_bt(): String
    fun get__hx_bu(): String
    fun get__hx_bv(): String
    fun get__hx_bw(): String
    fun get__hx_bx(): String
    fun get__hx_by(): String
    fun get__hx_bz(): String
    fun get__hx_ca(): String
    fun get__hx_cb(): String
    fun get__hx_cc(): String
    fun get__hx_cd(): String
    fun get__hx_ce(): String
    fun get__hx_cf(): String
    fun get__hx_cg(): String
    fun get__hx_ch(): String
    fun get__hx_ci(): String
    fun get__hx_cj(): String
    fun get__hx_ck(): String
    fun get__hx_cl(): String
    fun get__hx_cm(): String
    fun get__hx_cn(): String
    fun get__hx_co(): String
    fun get__hx_cp(): String
    fun get__hx_cq(): String
    fun get__hx_cr(): String
    fun get__hx_cs(): String
    fun get__hx_ct(): String
    fun get__hx_cu(): String
    fun get__hx_cv(): String
    fun get__hx_cw(): String
    fun get__hx_cx(): String
    fun get__hx_cy(): String
    fun get__hx_cz(): String
    fun get__hx_da(): String
    fun get__hx_db(): String
    fun get__hx_dc(): String
    fun get__hx_dd(): String
    fun get__hx_de(): String
    fun get__hx_df(): String
    fun get__hx_dg(): String
    fun get__hx_dh(): String
    fun get__hx_di(): String
    fun get__hx_dj(): String
    fun get__hx_dk(): String
    fun get__hx_dl(): String
    fun get__hx_dm(): String
    fun get__hx_dn(): String
    fun get__hx_do(): String
    fun get__hx_dp(): String
    fun get__hx_dq(): String
    fun get__hx_dr(): String
    fun get__hx_dt(): String
    fun get__hx_du(): String
    fun get__hx_dv(): String
    fun get__hx_dw(): String
    fun get__hx_dy(): String
    fun get__hx_dz(): String
    fun get__hx_e(): String
    fun get__hx_ea(): String
    fun get__hx_eb(): String
    fun get__hx_ec(): String
    fun get__hx_ed(): String
    fun get__hx_ee(): String
    fun get__hx_ef(): String
    fun get__hx_eh(): String
    fun get__hx_ei(): String
    fun get__hx_ej(): String
    fun get__hx_el(): String
    fun get__hx_em(): String
    fun get__hx_en(): String
    fun get__hx_eo(): String
    fun get__hx_ep(): String
    fun get__hx_eq(): String
    fun get__hx_er(): String
    fun get__hx_et(): String
    fun get__hx_eu(): String
    fun get__hx_ev(): String
    fun get__hx_ex(): String
    fun get__hx_ez(): String
    fun get__hx_fa(): String
    fun get__hx_fc(): String
    fun get__hx_fg(): String
    fun get__hx_fm(): String
    fun get__hx_fp(): String
    fun get__hx_fr(): String
    fun get__hx_fs(): String
    fun get__hx_fu(): String
    fun get__hx_fx(): String
    fun get__hx_fz(): String
    fun get__hx_ga(): String
    fun get__hx_gb(): String
    fun get__hx_gc(): String
    fun get__hx_gd(): String
    fun get__hx_ge(): String
    fun get__hx_gf(): String
    fun get__hx_gg(): String
    fun get__hx_gh(): String
    fun get__hx_gi(): String
    fun get__hx_gj(): String
    fun get__hx_gk(): String
    fun get__hx_gl(): String
    fun get__hx_gm(): String
    fun get__hx_gn(): String
    fun get__hx_go(): String
    fun get__hx_gp(): String
    fun get__hx_gq(): String
    fun get__hx_gr(): String
    fun get__hx_gs(): String
    fun get__hx_gt(): String
    fun get__hx_gu(): String
    fun get__hx_gv(): String
    fun get__hx_gw(): String
    fun get__hx_gx(): String
    fun get__hx_gy(): String
    fun get__hx_gz(): String
    fun get__hx_hc(): String
    fun get__hx_hf(): String
    fun get__hx_hh(): String
    fun get__hx_hi(): String
    fun get__hx_hl(): String
    fun get__hx_ho(): String
    fun get__hx_hq(): String
    fun get__hx_hr(): String
    fun get__hx_hs(): String
    fun get__hx_hv(): String
    fun get__hx_hw(): String
    fun get__hx_hx(): String
    fun get__hx_hy(): String
    fun get__hx_hz(): String
    fun get__hx_ib(): String
    fun get__hx_ic(): String
    fun get__hx_id(): String
    fun get__hx_ie(): String
    fun get__hx_if(): String
    fun get__hx_ig(): String
    fun get__hx_ii(): String
    fun get__hx_ij(): String
    fun get__hx_ik(): String
    fun get__hx_il(): String
    fun get__hx_io(): String
    fun get__hx_ir(): String
    fun get__hx_is(): String
    fun get__hx_it(): String
    fun get__hx_iu(): String
    fun get__hx_iv(): String
    fun get__hx_iw(): String
    fun get__hx_iz(): String
    fun get__hx_ja(): String
    fun get__hx_jb(): String
    fun get__hx_jc(): String
    fun get__hx_jd(): String
    fun get__hx_je(): String
    fun get__hx_jf(): String
    fun get__hx_jg(): String
    fun get__hx_jh(): String
    fun get__hx_ji(): String
    fun get__hx_jj(): String
    fun get__hx_jk(): String
    fun get__hx_jl(): String
    fun get__hx_jm(): String
    fun get__hx_jn(): String
    fun get__hx_jo(): String
    fun get__hx_jp(): String
    fun get__hx_jq(): String
    fun get__hx_jr(): String
    fun get__hx_js(): String
    fun get__hx_jt(): String
    fun get__hx_ju(): String
    fun get__hx_jv(): String
    fun get__hx_jw(): String
    fun get__hx_jx(): String
    fun get__hx_jy(): String
    fun get__hx_jz(): String
    fun get__hx_kc(): String
    fun get__hx_ke(): String
    fun get__hx_kf(): String
    fun get__hx_ki(): String
    fun get__hx_kk(): String
    fun get__hx_km(): String
    fun get__hx_kn(): String
    fun get__hx_ko(): String
    fun get__hx_kq(): String
    fun get__hx_kr(): String
    fun get__hx_ks(): String
    fun get__hx_kt(): String
    fun get__hx_ku(): String
    fun get__hx_kv(): String
    fun get__hx_kw(): String
    fun get__hx_ky(): String
    fun get__hx_s(): String
    fun get__hx_z(): String
    fun get__hx_rx(): Int
    fun get__hx_au(): String
    fun get__ii_d(): ServerBuild
    fun get__ii_k(): ServerBuild
    fun get__ii_m(): ServerBuild
    fun get__ii_x(): ServerBuild
    fun get__iv_d(): StudioGame
    fun get__iv_k(): StudioGame
    fun get__iv_m(): StudioGame
    fun get__iv_v(): StudioGame
    fun get__iv_w(): StudioGame
    fun get__iv_x(): StudioGame
    fun get__ix_re(): Int
    fun get__iy_a(): Int
    fun get__ip_k(): Int
    fun get__ia_o(): Byte
    fun get__ia_i(): Int
    fun get__ia_m(): Int
    fun get__ia_k(): Long
    fun get__iq_m(): EvictingDualNodeHashTable
    fun get__iq_x(): AbstractArchive
    fun get__ik_m(): Int
    fun get__ik_x(): AbstractArchive
    fun get__io_x(): AbstractArchive
    fun get__it_m(): EvictingDualNodeHashTable
    fun get__it_x(): AbstractArchive
    fun get__if_m(): EvictingDualNodeHashTable
    fun get__if_x(): AbstractArchive
    fun get__ib_k(): Int
    fun get__ib_bq(): Int
    fun get__ib_m(): AbstractArchive
    fun get__id_x(): AbstractArchive
    fun get__is_x(): AbstractArchive
    fun get__jq_m(): EvictingDualNodeHashTable
    fun get__jq_p(): IntArray
    fun get__jq_w(): IntArray
    fun get__jq_x(): AbstractArchive
    fun get__jq_bv(): IndexedSprite
    fun get__jv_w(): EvictingDualNodeHashTable
    fun get__jv_m(): AbstractArchive
    fun get__jv_x(): AbstractArchive
    fun get__jw_z(): Array<UnlitModel>
    fun get__jw_v(): EvictingDualNodeHashTable
    fun get__je_q(): Int
    fun get__jn_x(): AbstractArchive
    fun get__jn_m(): EvictingDualNodeHashTable
    fun get__jc_w(): EvictingDualNodeHashTable
    fun get__jc_nq(): Int
    fun get__jp_ex(): Archive
    fun get__jr_pc(): Boolean
    fun get__km_ab(): Any
    fun get__ky_rc(): Int
    fun get__kk_k(): AbstractArchive
    fun get__kq_m(): Array<Long>
    fun get__ks_k(): Array<Char>
    fun get__ks_m(): Array<Char>
    fun get__ks_x(): Array<Char>
    fun get__ks_d(): IntArray
    fun get__kc_v(): Int
    fun get__kb_z(): IntArray
    fun get__kb_e(): Array<Long>
    fun get__kl_t(): Array<Array<ByteArray>>
    fun get__kl_z(): IntArray
    fun get__lq_e(): Array<IndexedSprite>
    fun get__lf_z(): IntArray
    fun get__ll_m(): AbstractArchive
    fun get__lj_a(): Array<String>
    fun get__lu_x(): RectangleMode
    fun get__lu_k(): RectangleMode
    fun get__lu_m(): RectangleMode
    fun get__ls_k(): Int
    fun get__ls_m(): Int
    fun get__ls_x(): Int
    fun get__ls_d(): IntArray
    fun get__ls_q(): IntArray
    fun get__ls_v(): IntArray
    fun get__lr_t(): Int
    fun get__mq_gd(): Int
    fun get__mw_m(): AbstractArchive
    fun get__mj_t(): IntArray
    fun get__mc_e(): IntArray
    fun get__mc_s(): IntArray
    fun get__mx_t(): LoginType
    fun get__mx_x(): LoginType
    fun get__mx_d(): LoginType
    fun get__mx_k(): LoginType
    fun get__mx_m(): LoginType
    fun get__mx_q(): LoginType
    fun get__mx_v(): LoginType
    fun get__mx_w(): LoginType
    fun get__mx_z(): LoginType
    fun get__mr_d(): Array<Char>
    fun get__mr_k(): Array<Char>
    fun get__mr_w(): Array<Array<ByteArray>>
    fun get__mr_br(): Array<IndexedSprite>
    fun get__mf_d(): Int
    fun get__mf_q(): IntArray
}
