package com.p3achb0t._runestar_interfaces

interface UnlitModel: Entity{
	fun getFaceAlphas(): ByteArray
	fun getFaceColors(): ShortArray
	fun getFaceCount(): Int
	fun getFaceLabelsAlpha(): Array<IntArray>
	fun getFaceNormals(): Array<FaceNormal>
	fun getFaceTextures(): ShortArray
	fun getIndices1(): IntArray
	fun getIndices2(): IntArray
	fun getIndices3(): IntArray
	fun getIsBoundsCalculated(): Boolean
	fun getVertexLabels(): Array<IntArray>
	fun getVerticesCount(): Int
	fun getVerticesX(): IntArray
	fun getVerticesY(): IntArray
	fun getVerticesZ(): IntArray
	fun get__v(): Byte
	fun get__c(): ByteArray
	fun get__f(): ByteArray
	fun get__g(): ByteArray
	fun get__u(): ByteArray
	fun get__al(): Array<VertexNormal>
	fun get__z(): Array<VertexNormal>
	fun get__ad(): Int
	fun get__ag(): Int
	fun get__ar(): Int
	fun get__ax(): Int
	fun get__az(): Int
	fun get__y(): Int
	fun get__h(): IntArray
	fun get__o(): IntArray
	fun get__a(): ShortArray
	fun get__j(): ShortArray
	fun get__t(): ShortArray
	fun get__as(): Short
	fun get__av(): Short
}
