package com.p3achb0t._runestar_interfaces

interface WorldMap {
	fun getCacheLoader(): WorldMapArchiveLoader
	fun getCurrentMapArea0(): WorldMapArea
	fun getElementsDisabled(): Boolean
	fun getEnabledCategories(): Any
	fun getEnabledElements(): Any
	fun getFlashingElements(): Any
	fun getFont(): Font
	fun getFonts(): Any
	fun getIconIterator(): Any
	fun getMainMapArea(): WorldMapArea
	fun getMapAreas(): Any
	fun getMapSceneSprites(): Array<IndexedSprite>
	fun getMouseCoord(): Coord
	fun getPerpetualFlash0(): Boolean
	fun getSprite(): Sprite
	fun getWorldMapManager(): WorldMapManager
	fun getZoom(): Float
	fun getZoomTarget(): Float
	fun get__j(): WorldMapArea
	fun get__au(): Boolean
	fun get__b(): AbstractArchive
	fun get__c(): AbstractArchive
	fun get__i(): AbstractArchive
	fun get__aa(): Int
	fun get__ac(): Int
	fun get__ad(): Int
	fun get__ae(): Int
	fun get__ag(): Int
	fun get__aj(): Int
	fun get__an(): Int
	fun get__ao(): Int
	fun get__ap(): Int
	fun get__ar(): Int
	fun get__as(): Int
	fun get__at(): Int
	fun get__av(): Int
	fun get__aw(): Int
	fun get__bb(): Int
	fun get__bj(): Int
	fun get__bo(): Int
	fun get__bp(): Int
	fun get__bs(): Int
	fun get__d(): Int
	fun get__n(): Int
	fun get__o(): Int
	fun get__s(): Int
	fun get__af(): Any
	fun get__ay(): Any
	fun get__bm(): Any
	fun get__bg(): Any
	fun get__aq(): Long
	fun get__bi(): IntArray
	fun get__bc(): Boolean
}
