package com.p3achb0t.api.interfaces

interface Bzip2State {
    fun get__ab(): BooleanArray
    fun get__ag(): BooleanArray
    fun get__a(): Byte
    fun get__ae(): ByteArray
    fun get__am(): ByteArray
    fun get__ao(): ByteArray
    fun get__ap(): ByteArray
    fun get__m(): ByteArray
    fun get__x(): ByteArray
    fun get__au(): Array<ByteArray>
    fun get__al(): Int
    fun get__c(): Int
    fun get__d(): Int
    fun get__e(): Int
    fun get__f(): Int
    fun get__g(): Int
    fun get__h(): Int
    fun get__j(): Int
    fun get__n(): Int
    fun get__p(): Int
    fun get__q(): Int
    fun get__r(): Int
    fun get__v(): Int
    fun get__w(): Int
    fun get__y(): Int
    fun get__an(): IntArray
    fun get__aq(): IntArray
    fun get__b(): IntArray
    fun get__u(): IntArray
    fun get__aa(): Array<IntArray>
    fun get__ar(): Array<IntArray>
    fun get__at(): Array<IntArray>
    fun get__i(): Int
    fun get__k(): Int
    fun get__o(): Int
    fun get__s(): Int
    fun get__t(): Int
    fun get__z(): Int
}
