package com.p3achb0t.api.interfaces

interface Client : GameShell {
    fun getVarbit(id: Int): Int
    fun doAction(actionParam: Int, widgetID: Int, menuAction: Int, id: Int, menuOption: String, menuTarget: String, mouseX: Int, mouseY: Int, dummy: Int=0)
    fun setScene_selectedX(x: Int)
    fun setScene_selectedY(y: Int)
    fun setViewportWalking()
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderCount(): Int
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__y_ny(): Int
    fun get__y_c(): IndexedSprite
    fun get__p_rk(): Int
    fun get__p_ng(): Array<Component>
    fun get__j_an(): Int
    fun get__j_ez(): Archive
    fun get__d_o(): Boolean
    fun get__d_ed(): Archive
    fun get__l_tn(): Int
    fun get__o_p(): Any
    fun get__c_a(): Component
    fun get__g_s(): Array<ShortArray>
    fun get__g_l(): Int
    fun get__k_ie(): Int
    fun get__m_f(): Long
    fun get__m_re(): Int
    fun get__m_rf(): Int
    fun get__m_jm(): Component
    fun get__m_br(): Array<IndexedSprite>
    fun get__x_ba(): IndexedSprite
    fun get__z_d(): Array<Array<ByteArray>>
    fun get__z_j(): Array<Array<ByteArray>>
    fun get__z_es(): Int
    fun get__z_b(): Sprite
    fun get__w_qi(): Boolean
    fun get__h_u(): IntArray
    fun get__i_bh(): Array<IndexedSprite>
    fun get__ap_eh(): Int
    fun get__al_d(): ShortArray
    fun get__as_ra(): Int
    fun get__az_cb(): Int
    fun get__az_ce(): Int
    fun get__az_ch(): Int
    fun get__az_cj(): Int
    fun get__az_ck(): Int
    fun get__az_cy(): Int
    fun get__az_co(): IntArray
    fun get__az_cz(): IntArray
    fun get__az_cc(): Array<Char>
    fun get__az_cu(): IntArray
    fun get__ac_tf(): Int
    fun get__aq_v(): Any
    fun get__aq_n(): String
    fun get__af_c(): Array<Long>
    fun get__af_g(): Array<Long>
    fun get__af_a(): Int
    fun get__af_d(): Int
    fun get__af_e(): Int
    fun get__af_f(): Int
    fun get__af_s(): Int
    fun get__af_ax(): Any
    fun get__an_l(): BooleanArray
    fun get__an_s(): IntArray
    fun get__an_u(): IntArray
    fun get__an_n(): Array<Float>
    fun get__an_v(): IntArray
    fun get__bu_rw(): Int
    fun get__br_g(): BooleanArray
    fun get__br_ab(): Array<Float>
    fun get__br_ae(): Array<Float>
    fun get__br_ap(): Array<Float>
    fun get__br_h(): Array<Float>
    fun get__br_i(): Array<Float>
    fun get__br_q(): Array<Float>
    fun get__br_t(): Array<Float>
    fun get__br_a(): IntArray
    fun get__br_ad(): IntArray
    fun get__br_al(): IntArray
    fun get__be_mm(): Int
    fun get__be_l(): IndexedSprite
    fun get__be_s(): Array<IndexedSprite>
    fun get__bj_b(): Float
    fun get__bj_j(): Array<Array<Float>>
    fun get__bj_d(): Int
    fun get__bj_r(): Array<IntArray>
    fun get__bn_gh(): Int
    fun get__bn_bf(): IndexedSprite
    fun get__bo_ld(): Component
    fun get__bb_o(): Int
    fun get__bk_gw(): Int
    fun get__bk_as(): Bounds
    fun get__eo(): Packet
    fun get__client_tr(): Int
    fun get__client_sz(): OwnWorldComparator
    fun get__client_an(): Boolean
    fun get__client_bj(): Boolean
    fun get__client_cz(): Boolean
    fun get__client_dj(): Boolean
    fun get__client_ei(): Boolean
    fun get__client_fi(): Boolean
    fun get__client_hc(): Boolean
    fun get__client_id(): Boolean
    fun get__client_im(): Boolean
    fun get__client_jj(): Boolean
    fun get__client_no(): Boolean
    fun get__client_np(): Boolean
    fun get__client_qr(): Boolean
    fun get__client_kp(): BooleanArray
    fun get__client_or(): BooleanArray
    fun get__client_ov(): BooleanArray
    fun get__client_pc(): BooleanArray
    fun get__client_rs(): BooleanArray
    fun get__client_fz(): ByteArray
    fun get__client_sj(): PlayerAppearance
    fun get__client_be(): Int
    fun get__client_cc(): Int
    fun get__client_cj(): Int
    fun get__client_df(): Int
    fun get__client_dv(): Int
    fun get__client_ej(): Int
    fun get__client_el(): Int
    fun get__client_et(): Int
    fun get__client_fb(): Int
    fun get__client_fg(): Int
    fun get__client_gb(): Int
    fun get__client_gm(): Int
    fun get__client_gp(): Int
    fun get__client_gs(): Int
    fun get__client_gv(): Int
    fun get__client_gz(): Int
    fun get__client_hh(): Int
    fun get__client_hi(): Int
    fun get__client_hk(): Int
    fun get__client_hm(): Int
    fun get__client_hn(): Int
    fun get__client_hp(): Int
    fun get__client_ht(): Int
    fun get__client_hx(): Int
    fun get__client_hz(): Int
    fun get__client_ig(): Int
    fun get__client_ii(): Int
    fun get__client_ik(): Int
    fun get__client_il(): Int
    fun get__client_io(): Int
    fun get__client_ip(): Int
    fun get__client_ir(): Int
    fun get__client_is(): Int
    fun get__client_iu(): Int
    fun get__client_jc(): Int
    fun get__client_jf(): Int
    fun get__client_jt(): Int
    fun get__client_ju(): Int
    fun get__client_jv(): Int
    fun get__client_kg(): Int
    fun get__client_kl(): Int
    fun get__client_ko(): Int
    fun get__client_lf(): Int
    fun get__client_lk(): Int
    fun get__client_lm(): Int
    fun get__client_ma(): Int
    fun get__client_mc(): Int
    fun get__client_mi(): Int
    fun get__client_mp(): Int
    fun get__client_ms(): Int
    fun get__client_mv(): Int
    fun get__client_mz(): Int
    fun get__client_na(): Int
    fun get__client_nd(): Int
    fun get__client_nj(): Int
    fun get__client_nl(): Int
    fun get__client_nq(): Int
    fun get__client_nw(): Int
    fun get__client_nx(): Int
    fun get__client_oc(): Int
    fun get__client_oe(): Int
    fun get__client_of(): Int
    fun get__client_og(): Int
    fun get__client_oh(): Int
    fun get__client_ol(): Int
    fun get__client_on(): Int
    fun get__client_op(): Int
    fun get__client_ou(): Int
    fun get__client_ox(): Int
    fun get__client_oy(): Int
    fun get__client_pg(): Int
    fun get__client_pn(): Int
    fun get__client_pw(): Int
    fun get__client_qe(): Int
    fun get__client_qq(): Int
    fun get__client_sd(): Int
    fun get__client_sh(): Int
    fun get__client_tx(): Int
    fun get__client_fo(): IntArray
    fun get__client_kt(): IntArray
    fun get__client_kw(): IntArray
    fun get__client_ne(): IntArray
    fun get__client_nn(): IntArray
    fun get__client_ns(): IntArray
    fun get__client_oi(): IntArray
    fun get__client_ph(): IntArray
    fun get__client_pi(): IntArray
    fun get__client_py(): IntArray
    fun get__client_rd(): IntArray
    fun get__client_rh(): IntArray
    fun get__client_rq(): IntArray
    fun get__client_rt(): IntArray
    fun get__client_rv(): IntArray
    fun get__client_rx(): IntArray
    fun get__client_sb(): IntArray
    fun get__client_tt(): IntArray
    fun get__client_tu(): IntArray
    fun get__client_mj(): Component
    fun get__client_nv(): Component
    fun get__client_pp(): String
    fun get__client_ke(): NodeDeque
    fun get__client_oj(): NodeDeque
    fun get__client_om(): NodeDeque
    fun get__client_cu(): Long
    fun get__client_pq(): Long
    fun get__client_qb(): Long
    fun get__client_pe(): Array<Long>
    fun get__client_fj(): AbstractSocket
    fun get__client_sa(): Short
    fun get__client_sg(): Short
    fun get__client_si(): Short
    fun get__client_sk(): Short
    fun get__client_sm(): Short
    fun get__client_so(): Short
    fun get__client_sp(): Short
    fun get__client_su(): Short
    fun get__client_gd(): IntArray
    fun get__bg_r(): Int
    fun get__bg_b(): IntArray
    fun get__bg_d(): IntArray
    fun get__by_u(): IndexedSprite
    fun get__cd_h(): Boolean
    fun get__cd_q(): Boolean
    fun get__cd_i(): Int
    fun get__cd_x(): Int
    fun get__cd_g(): Component
    fun get__cd_gy(): Sprite
    fun get__cd_al(): Double
    fun get__cd_w(): Array<String>
    fun get__cv_j(): Any
    fun get__cv_p(): Any
    fun get__ci_nb(): Int
    fun get__ci_n(): Any
    fun get__ci_v(): Any
    fun get__ct_aa(): Boolean
    fun get__ct_au(): Boolean
    fun get__ct_bm(): Boolean
    fun get__ct_bt(): Boolean
    fun get__ct_n(): Boolean
    fun get__ct_aj(): Int
    fun get__ct_al(): Int
    fun get__ct_ar(): Int
    fun get__ct_bj(): Int
    fun get__ct_bp(): Int
    fun get__ct_bq(): Int
    fun get__ct_bx(): Int
    fun get__ct_f(): Int
    fun get__ct_x(): Int
    fun get__ct_bl(): String
    fun get__ct_bu(): String
    fun get__ct_bo(): Long
    fun get__ct_bw(): Long
    fun get__ct_r(): Sprite
    fun get__ct_j(): IndexedSprite
    fun get__ct_y(): Array<IndexedSprite>
    fun get__cf_bf(): Int
    fun get__cn_ax(): Bounds
    fun get__cs_ey(): Int
    fun get__cs_s(): IntArray
    fun get__cg_y(): Array<Array<ByteArray>>
    fun get__cg_i(): Int
    fun get__cg_q(): Int
    fun get__cg_l(): IntArray
    fun get__cg_h(): IntArray
    fun get__cg_m(): IntArray
    fun get__cg_t(): IntArray
    fun get__cg_w(): IntArray
    fun get__cg_x(): IntArray
    fun get__cg_z(): IntArray
    fun get__cj_b(): Boolean
    fun get__cl_v(): Int
    fun get__di_f(): ByteArray
    fun get__di_y(): ByteArray
    fun get__di_b(): Int
    fun get__di_o(): Int
    fun get__di_c(): IntArray
    fun get__di_d(): IntArray
    fun get__di_e(): Packet
    fun get__di_p(): Array<Packet>
    fun get__ds_av(): String
    fun get__do_e(): Array<Array<IntArray>>
    fun get__dv_gi(): Int
    fun get__dv_z(): Int
    fun get__da_u(): ShortArray
    fun get__du_g(): Int
    fun get__du_p(): Int
    fun get__ec_v(): Boolean
    fun get__ec_n(): Any
    fun get__ec_f(): Any
    fun get__ek_b(): IntArray
    fun get__ek_s(): UrlRequest
    fun get__ez_tg(): ShortArray
    fun get__ep_n(): EvictingDualNodeHashTable
    fun get__ep_v(): AbstractArchive
    fun get__ex_f(): EvictingDualNodeHashTable
    fun get__ex_n(): Int
    fun get__ex_rr(): Int
    fun get__ex_v(): AbstractArchive
    fun get__ew_f(): AbstractArchive
    fun get__ew_v(): AbstractArchive
    fun get__ej_n(): EvictingDualNodeHashTable
    fun get__ej_v(): AbstractArchive
    fun get__el_al(): Any
    fun get__el_n(): AbstractArchive
    fun get__et_n(): AbstractArchive
    fun get__et_v(): AbstractArchive
    fun get__et_eq(): IntArray
    fun get__eb_v(): AbstractArchive
    fun get__er_n(): EvictingDualNodeHashTable
    fun get__er_v(): AbstractArchive
    fun get__ef_gr(): Sprite
    fun get__ey_n(): EvictingDualNodeHashTable
    fun get__ey_v(): AbstractArchive
    fun get__ee_l(): Array<ShortArray>
    fun get__ee_j(): IntArray
    fun get__eh_v(): AbstractArchive
    fun get__eh_o(): IntArray
    fun get__ei_n(): EvictingDualNodeHashTable
    fun get__ei_v(): AbstractArchive
    fun get__ev_f(): AbstractArchive
    fun get__ev_n(): AbstractArchive
    fun get__ev_v(): AbstractArchive
    fun get__ev_p(): EvictingDualNodeHashTable
    fun get__ev_bs(): Array<IndexedSprite>
    fun get__eg_b(): Array<UnlitModel>
    fun get__eg_j(): EvictingDualNodeHashTable
    fun get__eq_cg(): Int
    fun get__eq_d(): Int
    fun get__eo_n(): EvictingDualNodeHashTable
    fun get__fl_f(): AbstractArchive
    fun get__fl_n(): AbstractArchive
    fun get__fl_p(): EvictingDualNodeHashTable
    fun get__fc_ih(): Int
    fun get__fa_b(): IntArray
    fun get__fa_d(): IntArray
    fun get__fa_f(): Array<IntArray>
    fun get__fa_y(): Array<IntArray>
    fun get__fs_u(): Int
    fun get__fe_ay(): Int
    fun get__fq_p(): DemotingHashTable
    fun get__fw_ee(): Int
    fun get__fx_f(): WorldMapSectionType
    fun get__fx_n(): WorldMapSectionType
    fun get__fx_v(): WorldMapSectionType
    fun get__fx_y(): WorldMapSectionType
    fun get__fh_y(): IntArray
    fun get__fh_d(): Int
    fun get__fn_ek(): Archive
    fun get__fr_d(): IntArray
    fun get__fr_be(): IndexedSprite
    fun get__gg_aw(): Boolean
    fun get__gm_am(): Int
    fun get__gm_aj(): IntArray
    fun get__gm_as(): IntArray
    fun get__gu_f(): IntArray
    fun get__gu_n(): IntArray
    fun get__gu_v(): IntArray
    fun get__gu_y(): IntArray
    fun get__gj_y(): Boolean
    fun get__gj_n(): Boolean
    fun get__gj_v(): Boolean
    fun get__gj_h(): IntArray
    fun get__gj_q(): IntArray
    fun get__ge_ak(): Int
    fun get__gt_ai(): Boolean
    fun get__gt_am(): Boolean
    fun get__gt_ac(): Int
    fun get__gt_e(): Int
    fun get__gt_aa(): IntArray
    fun get__gt_af(): IntArray
    fun get__gt_ak(): IntArray
    fun get__gt_an(): IntArray
    fun get__gt_au(): IntArray
    fun get__gt_ay(): IntArray
    fun get__gt_bd(): IntArray
    fun get__gk_j(): Int
    fun get__gn_gn(): Int
    fun get__gp_a(): IntArray
    fun get__gp_g(): IntArray
    fun get__gp_k(): IntArray
    fun get__gp_m(): IntArray
    fun get__gp_x(): IntArray
    fun get__gp_w(): Array<IntArray>
    fun get__gp_z(): Array<IntArray>
    fun get__gr_bs(): Boolean
    fun get__gr_ac(): BooleanArray
    fun get__gr_av(): BooleanArray
    fun get__gr_af(): IntArray
    fun get__gr_ao(): IntArray
    fun get__gr_aq(): IntArray
    fun get__gr_au(): IntArray
    fun get__gr_aw(): IntArray
    fun get__gr_ay(): IntArray
    fun get__gr_bd(): IntArray
    fun get__gr_bj(): IntArray
    fun get__gr_bl(): IntArray
    fun get__gr_bq(): IntArray
    fun get__gr_bt(): IntArray
    fun get__gr_bu(): IntArray
    fun get__gr_bv(): IntArray
    fun get__gr_bx(): IntArray
    fun get__gr_aa(): Array<IntArray>
    fun get__gr_an(): Array<IntArray>
    fun get__gy_b(): Int
    fun get__gy_p(): Int
    fun get__gy_r(): Int
    fun get__gc_l(): AbstractArchive
    fun get__hy_f(): Int
    fun get__hy_j(): AbstractArchive
    fun get__hy_iq(): Int
    fun get__hs_a(): ClientProt
    fun get__hs_aa(): ClientProt
    fun get__hs_ac(): ClientProt
    fun get__hs_ad(): ClientProt
    fun get__hs_ae(): ClientProt
    fun get__hs_af(): ClientProt
    fun get__hs_ag(): ClientProt
    fun get__hs_ah(): ClientProt
    fun get__hs_aj(): ClientProt
    fun get__hs_ak(): ClientProt
    fun get__hs_al(): ClientProt
    fun get__hs_am(): ClientProt
    fun get__hs_an(): ClientProt
    fun get__hs_ao(): ClientProt
    fun get__hs_ap(): ClientProt
    fun get__hs_aq(): ClientProt
    fun get__hs_ar(): ClientProt
    fun get__hs_as(): ClientProt
    fun get__hs_at(): ClientProt
    fun get__hs_au(): ClientProt
    fun get__hs_av(): ClientProt
    fun get__hs_aw(): ClientProt
    fun get__hs_ax(): ClientProt
    fun get__hs_ay(): ClientProt
    fun get__hs_az(): ClientProt
    fun get__hs_b(): ClientProt
    fun get__hs_ba(): ClientProt
    fun get__hs_bb(): ClientProt
    fun get__hs_bc(): ClientProt
    fun get__hs_bd(): ClientProt
    fun get__hs_be(): ClientProt
    fun get__hs_bf(): ClientProt
    fun get__hs_bg(): ClientProt
    fun get__hs_bh(): ClientProt
    fun get__hs_bi(): ClientProt
    fun get__hs_bj(): ClientProt
    fun get__hs_bk(): ClientProt
    fun get__hs_bl(): ClientProt
    fun get__hs_bm(): ClientProt
    fun get__hs_bn(): ClientProt
    fun get__hs_bo(): ClientProt
    fun get__hs_bp(): ClientProt
    fun get__hs_bq(): ClientProt
    fun get__hs_br(): ClientProt
    fun get__hs_bs(): ClientProt
    fun get__hs_bt(): ClientProt
    fun get__hs_bu(): ClientProt
    fun get__hs_bw(): ClientProt
    fun get__hs_bx(): ClientProt
    fun get__hs_by(): ClientProt
    fun get__hs_bz(): ClientProt
    fun get__hs_c(): ClientProt
    fun get__hs_ca(): ClientProt
    fun get__hs_cb(): ClientProt
    fun get__hs_cc(): ClientProt
    fun get__hs_cd(): ClientProt
    fun get__hs_ce(): ClientProt
    fun get__hs_cf(): ClientProt
    fun get__hs_cg(): ClientProt
    fun get__hs_ch(): ClientProt
    fun get__hs_ci(): ClientProt
    fun get__hs_cj(): ClientProt
    fun get__hs_ck(): ClientProt
    fun get__hs_cl(): ClientProt
    fun get__hs_cm(): ClientProt
    fun get__hs_cn(): ClientProt
    fun get__hs_co(): ClientProt
    fun get__hs_cp(): ClientProt
    fun get__hs_cq(): ClientProt
    fun get__hs_cr(): ClientProt
    fun get__hs_cs(): ClientProt
    fun get__hs_ct(): ClientProt
    fun get__hs_cu(): ClientProt
    fun get__hs_cv(): ClientProt
    fun get__hs_cw(): ClientProt
    fun get__hs_cx(): ClientProt
    fun get__hs_cy(): ClientProt
    fun get__hs_cz(): ClientProt
    fun get__hs_d(): ClientProt
    fun get__hs_db(): ClientProt
    fun get__hs_dz(): ClientProt
    fun get__hs_e(): ClientProt
    fun get__hs_f(): ClientProt
    fun get__hs_h(): ClientProt
    fun get__hs_i(): ClientProt
    fun get__hs_j(): ClientProt
    fun get__hs_k(): ClientProt
    fun get__hs_l(): ClientProt
    fun get__hs_m(): ClientProt
    fun get__hs_n(): ClientProt
    fun get__hs_o(): ClientProt
    fun get__hs_p(): ClientProt
    fun get__hs_q(): ClientProt
    fun get__hs_r(): ClientProt
    fun get__hs_t(): ClientProt
    fun get__hs_u(): ClientProt
    fun get__hs_v(): ClientProt
    fun get__hs_w(): ClientProt
    fun get__hs_x(): ClientProt
    fun get__hs_y(): ClientProt
    fun get__hs_z(): ClientProt
    fun get__hs_ab(): ClientProt
    fun get__hs_ai(): ClientProt
    fun get__hs_bv(): ClientProt
    fun get__hs_g(): ClientProt
    fun get__hs_s(): ClientProt
    fun get__hq_j(): Int
    fun get__hl_a(): ServerProt
    fun get__hl_aa(): ServerProt
    fun get__hl_ab(): ServerProt
    fun get__hl_ac(): ServerProt
    fun get__hl_ad(): ServerProt
    fun get__hl_ae(): ServerProt
    fun get__hl_af(): ServerProt
    fun get__hl_ag(): ServerProt
    fun get__hl_ah(): ServerProt
    fun get__hl_ai(): ServerProt
    fun get__hl_aj(): ServerProt
    fun get__hl_ak(): ServerProt
    fun get__hl_al(): ServerProt
    fun get__hl_am(): ServerProt
    fun get__hl_an(): ServerProt
    fun get__hl_ao(): ServerProt
    fun get__hl_ap(): ServerProt
    fun get__hl_aq(): ServerProt
    fun get__hl_ar(): ServerProt
    fun get__hl_as(): ServerProt
    fun get__hl_at(): ServerProt
    fun get__hl_au(): ServerProt
    fun get__hl_av(): ServerProt
    fun get__hl_aw(): ServerProt
    fun get__hl_ax(): ServerProt
    fun get__hl_ay(): ServerProt
    fun get__hl_az(): ServerProt
    fun get__hl_b(): ServerProt
    fun get__hl_ba(): ServerProt
    fun get__hl_bb(): ServerProt
    fun get__hl_bc(): ServerProt
    fun get__hl_bd(): ServerProt
    fun get__hl_be(): ServerProt
    fun get__hl_bf(): ServerProt
    fun get__hl_bg(): ServerProt
    fun get__hl_bh(): ServerProt
    fun get__hl_bi(): ServerProt
    fun get__hl_bj(): ServerProt
    fun get__hl_bk(): ServerProt
    fun get__hl_bl(): ServerProt
    fun get__hl_bm(): ServerProt
    fun get__hl_bn(): ServerProt
    fun get__hl_bo(): ServerProt
    fun get__hl_bp(): ServerProt
    fun get__hl_bq(): ServerProt
    fun get__hl_br(): ServerProt
    fun get__hl_bs(): ServerProt
    fun get__hl_bt(): ServerProt
    fun get__hl_bu(): ServerProt
    fun get__hl_bv(): ServerProt
    fun get__hl_bw(): ServerProt
    fun get__hl_bx(): ServerProt
    fun get__hl_by(): ServerProt
    fun get__hl_bz(): ServerProt
    fun get__hl_c(): ServerProt
    fun get__hl_cc(): ServerProt
    fun get__hl_cd(): ServerProt
    fun get__hl_cf(): ServerProt
    fun get__hl_cg(): ServerProt
    fun get__hl_ci(): ServerProt
    fun get__hl_cj(): ServerProt
    fun get__hl_ck(): ServerProt
    fun get__hl_cm(): ServerProt
    fun get__hl_cn(): ServerProt
    fun get__hl_co(): ServerProt
    fun get__hl_cp(): ServerProt
    fun get__hl_cq(): ServerProt
    fun get__hl_cr(): ServerProt
    fun get__hl_cs(): ServerProt
    fun get__hl_ct(): ServerProt
    fun get__hl_cu(): ServerProt
    fun get__hl_cv(): ServerProt
    fun get__hl_d(): ServerProt
    fun get__hl_e(): ServerProt
    fun get__hl_f(): ServerProt
    fun get__hl_g(): ServerProt
    fun get__hl_h(): ServerProt
    fun get__hl_i(): ServerProt
    fun get__hl_j(): ServerProt
    fun get__hl_k(): ServerProt
    fun get__hl_l(): ServerProt
    fun get__hl_m(): ServerProt
    fun get__hl_n(): ServerProt
    fun get__hl_o(): ServerProt
    fun get__hl_p(): ServerProt
    fun get__hl_q(): ServerProt
    fun get__hl_r(): ServerProt
    fun get__hl_s(): ServerProt
    fun get__hl_t(): ServerProt
    fun get__hl_u(): ServerProt
    fun get__hl_v(): ServerProt
    fun get__hl_w(): ServerProt
    fun get__hl_x(): ServerProt
    fun get__hl_y(): ServerProt
    fun get__hl_z(): ServerProt
    fun get__hv_f(): LoginProt
    fun get__hv_p(): LoginProt
    fun get__hv_v(): LoginProt
    fun get__hv_y(): LoginProt
    fun get__hv_j(): LoginProt
    fun get__hv_n(): LoginProt
    fun get__hv_b(): Array<LoginProt>
    fun get__hu_d(): Array<IntArray>
    fun get__hi_v(): IntArray
    fun get__hx_d(): Int
    fun get__hx_p(): Int
    fun get__hx_n(): AbstractArchive
    fun get__hx_v(): AbstractArchive
    fun get__hx_s(): Int
    fun get__ir_s(): ByteArray
    fun get__in_qo(): Boolean
    fun get__ih_ag(): String
    fun get__it_s(): AbstractArchive
    fun get__ik_bd(): String
    fun get__ic_o(): IntArray
    fun get__ig_u(): AbstractArchive
    fun get__ig_f(): ShortArray
    fun get__ig_v(): ShortArray
    fun get__ig_n(): Array<ShortArray>
    fun get__ig_y(): Array<ShortArray>
    fun get__io_a(): Boolean
    fun get__io_g(): EvictingDualNodeHashTable
    fun get__io_o(): EvictingDualNodeHashTable
    fun get__io_sr(): Long
    fun get__il_cs(): Char
    fun get__il_j(): Int
    fun get__im_ry(): Int
    fun get__ip_p(): IntArray
    fun get__ip_f(): Any
    fun get__ip_n(): Array<String>
    fun get__ip_v(): Array<Array<String>>
    fun get__if_r(): Array<Array<ByteArray>>
    fun get__if_s(): Int
    fun get__ia_p(): Array<Array<ByteArray>>
    fun get__ji_b(): Int
    fun get__ji_p(): IndexedSprite
    fun get__jk_f(): ServerBuild
    fun get__jk_n(): ServerBuild
    fun get__jk_v(): ServerBuild
    fun get__jk_y(): ServerBuild
    fun get__jd_f(): StudioGame
    fun get__jd_j(): StudioGame
    fun get__jd_n(): StudioGame
    fun get__jd_p(): StudioGame
    fun get__jd_v(): StudioGame
    fun get__jd_y(): StudioGame
    fun get__jo_aa(): String
    fun get__jo_ac(): String
    fun get__jo_af(): String
    fun get__jo_ah(): String
    fun get__jo_ak(): String
    fun get__jo_an(): String
    fun get__jo_ao(): String
    fun get__jo_aq(): String
    fun get__jo_at(): String
    fun get__jo_au(): String
    fun get__jo_av(): String
    fun get__jo_aw(): String
    fun get__jo_ay(): String
    fun get__jo_az(): String
    fun get__jo_b(): String
    fun get__jo_ba(): String
    fun get__jo_bb(): String
    fun get__jo_bc(): String
    fun get__jo_bd(): String
    fun get__jo_be(): String
    fun get__jo_bf(): String
    fun get__jo_bg(): String
    fun get__jo_bh(): String
    fun get__jo_bi(): String
    fun get__jo_bj(): String
    fun get__jo_bk(): String
    fun get__jo_bl(): String
    fun get__jo_bm(): String
    fun get__jo_bn(): String
    fun get__jo_bo(): String
    fun get__jo_bp(): String
    fun get__jo_bq(): String
    fun get__jo_br(): String
    fun get__jo_bs(): String
    fun get__jo_bt(): String
    fun get__jo_bu(): String
    fun get__jo_bv(): String
    fun get__jo_bw(): String
    fun get__jo_bx(): String
    fun get__jo_by(): String
    fun get__jo_bz(): String
    fun get__jo_ca(): String
    fun get__jo_cb(): String
    fun get__jo_cc(): String
    fun get__jo_cd(): String
    fun get__jo_ce(): String
    fun get__jo_cf(): String
    fun get__jo_cg(): String
    fun get__jo_ch(): String
    fun get__jo_ci(): String
    fun get__jo_cj(): String
    fun get__jo_ck(): String
    fun get__jo_cl(): String
    fun get__jo_cm(): String
    fun get__jo_cn(): String
    fun get__jo_co(): String
    fun get__jo_cp(): String
    fun get__jo_cq(): String
    fun get__jo_cr(): String
    fun get__jo_cs(): String
    fun get__jo_ct(): String
    fun get__jo_cu(): String
    fun get__jo_cv(): String
    fun get__jo_cw(): String
    fun get__jo_cx(): String
    fun get__jo_cy(): String
    fun get__jo_cz(): String
    fun get__jo_da(): String
    fun get__jo_db(): String
    fun get__jo_dc(): String
    fun get__jo_dd(): String
    fun get__jo_de(): String
    fun get__jo_df(): String
    fun get__jo_dg(): String
    fun get__jo_dh(): String
    fun get__jo_di(): String
    fun get__jo_dj(): String
    fun get__jo_dk(): String
    fun get__jo_dm(): String
    fun get__jo_dn(): String
    fun get__jo_do(): String
    fun get__jo_dp(): String
    fun get__jo_dq(): String
    fun get__jo_dr(): String
    fun get__jo_ds(): String
    fun get__jo_du(): String
    fun get__jo_dv(): String
    fun get__jo_dw(): String
    fun get__jo_dx(): String
    fun get__jo_dy(): String
    fun get__jo_dz(): String
    fun get__jo_ea(): String
    fun get__jo_eb(): String
    fun get__jo_ec(): String
    fun get__jo_ed(): String
    fun get__jo_ee(): String
    fun get__jo_ef(): String
    fun get__jo_eh(): String
    fun get__jo_ej(): String
    fun get__jo_ek(): String
    fun get__jo_el(): String
    fun get__jo_em(): String
    fun get__jo_en(): String
    fun get__jo_ep(): String
    fun get__jo_er(): String
    fun get__jo_es(): String
    fun get__jo_et(): String
    fun get__jo_eu(): String
    fun get__jo_ew(): String
    fun get__jo_ex(): String
    fun get__jo_ey(): String
    fun get__jo_ez(): String
    fun get__jo_ff(): String
    fun get__jo_fj(): String
    fun get__jo_fk(): String
    fun get__jo_fm(): String
    fun get__jo_fo(): String
    fun get__jo_fq(): String
    fun get__jo_fr(): String
    fun get__jo_fu(): String
    fun get__jo_fw(): String
    fun get__jo_fx(): String
    fun get__jo_ga(): String
    fun get__jo_gb(): String
    fun get__jo_gc(): String
    fun get__jo_gd(): String
    fun get__jo_ge(): String
    fun get__jo_gf(): String
    fun get__jo_gg(): String
    fun get__jo_gh(): String
    fun get__jo_gi(): String
    fun get__jo_gj(): String
    fun get__jo_gk(): String
    fun get__jo_gl(): String
    fun get__jo_gm(): String
    fun get__jo_gn(): String
    fun get__jo_go(): String
    fun get__jo_gp(): String
    fun get__jo_gq(): String
    fun get__jo_gr(): String
    fun get__jo_gs(): String
    fun get__jo_gt(): String
    fun get__jo_gu(): String
    fun get__jo_gv(): String
    fun get__jo_gw(): String
    fun get__jo_gx(): String
    fun get__jo_gy(): String
    fun get__jo_gz(): String
    fun get__jo_hb(): String
    fun get__jo_hf(): String
    fun get__jo_hg(): String
    fun get__jo_hh(): String
    fun get__jo_hi(): String
    fun get__jo_hj(): String
    fun get__jo_hk(): String
    fun get__jo_hm(): String
    fun get__jo_ho(): String
    fun get__jo_hp(): String
    fun get__jo_ht(): String
    fun get__jo_hw(): String
    fun get__jo_hx(): String
    fun get__jo_hy(): String
    fun get__jo_ia(): String
    fun get__jo_ib(): String
    fun get__jo_id(): String
    fun get__jo_ie(): String
    fun get__jo_if(): String
    fun get__jo_ih(): String
    fun get__jo_ij(): String
    fun get__jo_ik(): String
    fun get__jo_im(): String
    fun get__jo_in(): String
    fun get__jo_ip(): String
    fun get__jo_iq(): String
    fun get__jo_it(): String
    fun get__jo_iv(): String
    fun get__jo_iw(): String
    fun get__jo_ix(): String
    fun get__jo_iy(): String
    fun get__jo_iz(): String
    fun get__jo_ja(): String
    fun get__jo_jb(): String
    fun get__jo_jc(): String
    fun get__jo_jd(): String
    fun get__jo_je(): String
    fun get__jo_jf(): String
    fun get__jo_jg(): String
    fun get__jo_jh(): String
    fun get__jo_ji(): String
    fun get__jo_jj(): String
    fun get__jo_jk(): String
    fun get__jo_jl(): String
    fun get__jo_jm(): String
    fun get__jo_jn(): String
    fun get__jo_jo(): String
    fun get__jo_jp(): String
    fun get__jo_jq(): String
    fun get__jo_jr(): String
    fun get__jo_js(): String
    fun get__jo_jt(): String
    fun get__jo_ju(): String
    fun get__jo_jv(): String
    fun get__jo_jw(): String
    fun get__jo_jx(): String
    fun get__jo_jy(): String
    fun get__jo_jz(): String
    fun get__jo_ka(): String
    fun get__jo_kc(): String
    fun get__jo_kd(): String
    fun get__jo_kg(): String
    fun get__jo_kh(): String
    fun get__jo_ki(): String
    fun get__jo_kj(): String
    fun get__jo_kk(): String
    fun get__jo_kl(): String
    fun get__jo_km(): String
    fun get__jo_ko(): String
    fun get__jo_kq(): String
    fun get__jo_kr(): String
    fun get__jo_kt(): String
    fun get__jo_kx(): String
    fun get__jo_ky(): String
    fun get__jo_s(): String
    fun get__jo_u(): String
    fun get__jo_am(): String
    fun get__ja_k(): Array<String>
    fun get__ja_r(): PlayerType
    fun get__jg_f(): Int
    fun get__jv_al(): Int
    fun get__jx_w(): Byte
    fun get__jx_a(): Int
    fun get__jx_n(): Int
    fun get__jm_f(): Any
    fun get__jm_n(): Any
    fun get__jm_p(): Any
    fun get__jm_y(): Any
    fun get__jm_jp(): Component
    fun get__jt_fq(): Long
    fun get__ju_o(): IndexedSprite
    fun get__kh_o(): Font
    fun get__kd_v(): Array<Char>
    fun get__kd_r(): IntArray
    fun get__kd_f(): Array<Char>
    fun get__kd_n(): Array<Char>
    fun get__kd_y(): IntArray
    fun get__ku_n(): Array<Long>
    fun get__ke_b(): IntArray
    fun get__ke_r(): IntArray
    fun get__lb_rn(): Int
    fun get__la_rl(): Int
    fun get__lh_ru(): Int
    fun get__lf_c(): IntArray
    fun get__lf_ad(): Any
    fun get__ld_bz(): Array<Sprite>
    fun get__mu_d(): IndexedSprite
    fun get__mv_eu(): Archive
    fun get__mt_br(): String
    fun get__nc_d(): LoginType
    fun get__nc_v(): LoginType
    fun get__nc_b(): LoginType
    fun get__nc_f(): LoginType
    fun get__nc_j(): LoginType
    fun get__nc_n(): LoginType
    fun get__nc_p(): LoginType
    fun get__nc_r(): LoginType
    fun get__nc_y(): LoginType
    fun get__nk_f(): Array<Char>
    fun get__nk_y(): Array<Char>
    fun get__nx_v(): IntArray
    fun get__nx_b(): Array<Array<ByteArray>>
    fun get__nq_q(): IntArray
    fun get__nd_b(): IntArray
    fun get__nd_s(): Array<Long>
    fun get__nj_f(): Int
    fun get__on_v(): RectangleMode
    fun get__on_f(): RectangleMode
    fun get__on_n(): RectangleMode
    fun get__ox_d(): Array<ByteArray>
    fun get__ox_j(): IntArray
    fun get__ox_n(): Int
    fun get__ox_v(): Int
    fun get__oo_s(): IntArray
    fun get__oo_u(): IntArray
    fun get__oz_y(): Int
}
