package com.p3achb0t.api.interfaces

interface Client : GameShell {
    fun getVarbit(id: Int): Int
    fun doAction(actionParam: Int, widgetID: Int, menuAction: Int, id: Int, menuOption: String, menuTarget: String, mouseX: Int, mouseY: Int, dummy: Byte=0)
    fun setScene_selectedX(x: Int)
    fun setScene_selectedY(y: Int)
    fun setViewportWalking()
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getEnumType_archive(): AbstractArchive
    fun getEnumType_cached(): EvictingDualNodeHashTable
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderCount(): Int
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__k_z(): AbstractArchive
    fun get__t_h(): Component
    fun get__t_n(): Int
    fun get__t_es(): Archive
    fun get__w_if(): Int
    fun get__w_g(): IntArray
    fun get__w_be(): IndexedSprite
    fun get__g_pv(): Boolean
    fun get__g_rf(): Int
    fun get__q_im(): Int
    fun get__c_i(): Any
    fun get__c_k(): Any
    fun get__c_s(): Any
    fun get__c_t(): Any
    fun get__f_ji(): Component
    fun get__y_g(): ShortArray
    fun get__y_t(): Array<IndexedSprite>
    fun get__v_be(): Int
    fun get__r_na(): Array<Component>
    fun get__r_aj(): Int
    fun get__r_aa(): Bounds
    fun get__u_s(): AbstractArchive
    fun get__p_w(): Array<Array<ByteArray>>
    fun get__ab_bl(): String
    fun get__ag_gl(): Int
    fun get__ag_bu(): IndexedSprite
    fun get__ae_g(): Int
    fun get__ae_k(): WorldMapSectionType
    fun get__ae_s(): WorldMapSectionType
    fun get__ae_t(): WorldMapSectionType
    fun get__ae_z(): WorldMapSectionType
    fun get__am_d(): IntArray
    fun get__ap_ew(): Int
    fun get__at_w(): Array<ShortArray>
    fun get__al_i(): DemotingHashTable
    fun get__ah_g(): Array<IntArray>
    fun get__av_i(): Int
    fun get__az_bp(): Array<IndexedSprite>
    fun get__aj_ey(): Int
    fun get__aw_en(): Archive
    fun get__af_m(): UrlRequest
    fun get__af_h(): IntArray
    fun get__bl_gk(): Int
    fun get__bz_cf(): Int
    fun get__bz_ch(): Int
    fun get__bz_cj(): Int
    fun get__bz_ck(): Int
    fun get__bz_co(): Int
    fun get__bz_cs(): Int
    fun get__bz_cc(): IntArray
    fun get__bz_cp(): IntArray
    fun get__bz_cd(): Array<Char>
    fun get__bz_cx(): IntArray
    fun get__bi_a(): Component
    fun get__bg_g(): Int
    fun get__bp_ah(): String
    fun get__bp_ef(): Int
    fun get__bp_a(): IntArray
    fun get__bp_z(): Any
    fun get__bp_k(): String
    fun get__bw_ai(): Boolean
    fun get__bw_m(): Int
    fun get__bw_n(): Int
    fun get__bw_s(): Int
    fun get__bw_f(): Array<Long>
    fun get__bw_q(): Array<Long>
    fun get__be_ij(): Int
    fun get__be_fg(): AbstractSocket
    fun get__bu_g(): Int
    fun get__bu_i(): Array<Array<ByteArray>>
    fun get__bu_t(): Array<Array<ByteArray>>
    fun get__bu_e(): Int
    fun get__bu_l(): Int
    fun get__bu_m(): IntArray
    fun get__bu_n(): IntArray
    fun get__bu_b(): IntArray
    fun get__bu_j(): IntArray
    fun get__bu_p(): IntArray
    fun get__bu_r(): IntArray
    fun get__bu_u(): IntArray
    fun get__bu_v(): IntArray
    fun get__bb_sf(): Long
    fun get__bx_y(): Array<String>
    fun get__by_dq(): Boolean
    fun get__by_gy(): Int
    fun get__by_sz(): Int
    fun get__by_h(): Font
    fun get__bo_rc(): Int
    fun get__bo_eu(): Archive
    fun get__bv_an(): Any
    fun get__el(): Packet
    fun get__client_sr(): Int
    fun get__client_ac(): Boolean
    fun get__client_ba(): Boolean
    fun get__client_cx(): Boolean
    fun get__client_ex(): Boolean
    fun get__client_fr(): Boolean
    fun get__client_ht(): Boolean
    fun get__client_id(): Boolean
    fun get__client_ik(): Boolean
    fun get__client_jy(): Boolean
    fun get__client_no(): Boolean
    fun get__client_nx(): Boolean
    fun get__client_qk(): Boolean
    fun get__client_kl(): BooleanArray
    fun get__client_oo(): BooleanArray
    fun get__client_or(): BooleanArray
    fun get__client_oz(): BooleanArray
    fun get__client_rz(): BooleanArray
    fun get__client_sd(): OwnWorldComparator
    fun get__client_fq(): ByteArray
    fun get__client_sq(): PlayerAppearance
    fun get__client_mq(): Component
    fun get__client_nh(): Component
    fun get__client_cf(): Int
    fun get__client_cj(): Int
    fun get__client_da(): Int
    fun get__client_de(): Int
    fun get__client_eg(): Int
    fun get__client_em(): Int
    fun get__client_eq(): Int
    fun get__client_ff(): Int
    fun get__client_fk(): Int
    fun get__client_gj(): Int
    fun get__client_gm(): Int
    fun get__client_gr(): Int
    fun get__client_gu(): Int
    fun get__client_gv(): Int
    fun get__client_gw(): Int
    fun get__client_hd(): Int
    fun get__client_hh(): Int
    fun get__client_hi(): Int
    fun get__client_hk(): Int
    fun get__client_hl(): Int
    fun get__client_hm(): Int
    fun get__client_ho(): Int
    fun get__client_hp(): Int
    fun get__client_hw(): Int
    fun get__client_hy(): Int
    fun get__client_ig(): Int
    fun get__client_ii(): Int
    fun get__client_io(): Int
    fun get__client_ip(): Int
    fun get__client_iq(): Int
    fun get__client_is(): Int
    fun get__client_iv(): Int
    fun get__client_iw(): Int
    fun get__client_ja(): Int
    fun get__client_jb(): Int
    fun get__client_je(): Int
    fun get__client_jf(): Int
    fun get__client_jr(): Int
    fun get__client_kh(): Int
    fun get__client_kp(): Int
    fun get__client_kt(): Int
    fun get__client_lh(): Int
    fun get__client_li(): Int
    fun get__client_lm(): Int
    fun get__client_ls(): Int
    fun get__client_ma(): Int
    fun get__client_mc(): Int
    fun get__client_mf(): Int
    fun get__client_ms(): Int
    fun get__client_mv(): Int
    fun get__client_mw(): Int
    fun get__client_nb(): Int
    fun get__client_nd(): Int
    fun get__client_ne(): Int
    fun get__client_ng(): Int
    fun get__client_ni(): Int
    fun get__client_nr(): Int
    fun get__client_nt(): Int
    fun get__client_nu(): Int
    fun get__client_nz(): Int
    fun get__client_od(): Int
    fun get__client_oe(): Int
    fun get__client_oi(): Int
    fun get__client_oj(): Int
    fun get__client_on(): Int
    fun get__client_oq(): Int
    fun get__client_ox(): Int
    fun get__client_pd(): Int
    fun get__client_ps(): Int
    fun get__client_pt(): Int
    fun get__client_py(): Int
    fun get__client_qa(): Int
    fun get__client_qf(): Int
    fun get__client_qu(): Int
    fun get__client_qv(): Int
    fun get__client_si(): Int
    fun get__client_ss(): Int
    fun get__client_su(): Int
    fun get__client_fe(): IntArray
    fun get__client_ks(): IntArray
    fun get__client_kv(): IntArray
    fun get__client_np(): IntArray
    fun get__client_nq(): IntArray
    fun get__client_nw(): IntArray
    fun get__client_pa(): IntArray
    fun get__client_po(): IntArray
    fun get__client_pr(): IntArray
    fun get__client_qi(): IntArray
    fun get__client_qp(): IntArray
    fun get__client_qt(): IntArray
    fun get__client_rh(): IntArray
    fun get__client_rk(): IntArray
    fun get__client_rl(): IntArray
    fun get__client_rr(): IntArray
    fun get__client_te(): IntArray
    fun get__client_tv(): IntArray
    fun get__client_pm(): String
    fun get__client_ki(): NodeDeque
    fun get__client_oc(): NodeDeque
    fun get__client_ok(): NodeDeque
    fun get__client_cd(): Long
    fun get__client_ob(): Long
    fun get__client_pb(): Long
    fun get__client_pj(): Array<Long>
    fun get__client_rd(): Short
    fun get__client_rm(): Short
    fun get__client_rq(): Short
    fun get__client_ru(): Short
    fun get__client_rv(): Short
    fun get__client_rw(): Short
    fun get__client_rx(): Short
    fun get__client_ry(): Short
    fun get__client_gn(): IntArray
    fun get__ca_rb(): Int
    fun get__ct_x(): Int
    fun get__ct_g(): IntArray
    fun get__ct_w(): IntArray
    fun get__cv_ac(): Int
    fun get__cv_et(): Int
    fun get__ce_z(): Int
    fun get__ce_m(): Array<IndexedSprite>
    fun get__ci_v(): Boolean
    fun get__ci_y(): Boolean
    fun get__ci_j(): Int
    fun get__ci_b(): Double
    fun get__ci_c(): Array<String>
    fun get__cu_d(): AbstractArchive
    fun get__cu_l(): IntArray
    fun get__cq_i(): Any
    fun get__cq_o(): Any
    fun get__cj_g(): Array<ByteArray>
    fun get__cj_k(): Any
    fun get__cj_z(): Any
    fun get__cx_af(): Boolean
    fun get__cx_ak(): Boolean
    fun get__cx_bc(): Boolean
    fun get__cx_bg(): Boolean
    fun get__cx_k(): Boolean
    fun get__cx_ae(): Int
    fun get__cx_ap(): Int
    fun get__cx_at(): Int
    fun get__cx_bb(): Int
    fun get__cx_bd(): Int
    fun get__cx_bm(): Int
    fun get__cx_bz(): Int
    fun get__cx_j(): Int
    fun get__cx_s(): Int
    fun get__cx_bh(): String
    fun get__cx_bj(): String
    fun get__cx_bq(): Long
    fun get__cx_by(): Long
    fun get__cx_w(): Sprite
    fun get__cx_a(): IndexedSprite
    fun get__cx_bw(): Array<IndexedSprite>
    fun get__ck_s(): ByteArray
    fun get__ck_t(): ByteArray
    fun get__ck_h(): Int
    fun get__ck_w(): Int
    fun get__ck_a(): IntArray
    fun get__ck_g(): IntArray
    fun get__ck_q(): Packet
    fun get__ck_i(): Array<Packet>
    fun get__cz_n(): AbstractArchive
    fun get__cz_sb(): ShortArray
    fun get__dx_cw(): Char
    fun get__dv_aw(): Int
    fun get__dk_c(): BooleanArray
    fun get__dk_ab(): Array<Float>
    fun get__dk_ag(): Array<Float>
    fun get__dk_ao(): Array<Float>
    fun get__dk_b(): Array<Float>
    fun get__dk_e(): Array<Float>
    fun get__dk_l(): Array<Float>
    fun get__dk_p(): Array<Float>
    fun get__dk_ae(): IntArray
    fun get__dk_an(): IntArray
    fun get__dk_f(): IntArray
    fun get__da_d(): BooleanArray
    fun get__da_m(): IntArray
    fun get__da_n(): IntArray
    fun get__da_k(): Array<Float>
    fun get__da_z(): IntArray
    fun get__dr_fb(): Long
    fun get__dy_c(): Int
    fun get__ds_rp(): Int
    fun get__du_w(): Float
    fun get__du_o(): Array<Array<Float>>
    fun get__du_g(): Int
    fun get__du_x(): Array<IntArray>
    fun get__dt_ri(): Int
    fun get__ee_aq(): Int
    fun get__ee_ar(): IntArray
    fun get__ee_at(): IntArray
    fun get__en_c(): IntArray
    fun get__en_f(): IntArray
    fun get__en_j(): IntArray
    fun get__en_v(): IntArray
    fun get__en_y(): IntArray
    fun get__en_r(): Array<IntArray>
    fun get__en_u(): Array<IntArray>
    fun get__eu_re(): Int
    fun get__es_k(): IntArray
    fun get__es_s(): IntArray
    fun get__es_t(): IntArray
    fun get__es_z(): IntArray
    fun get__er_bn(): Boolean
    fun get__er_ah(): BooleanArray
    fun get__er_av(): BooleanArray
    fun get__er_ad(): IntArray
    fun get__er_ai(): IntArray
    fun get__er_ak(): IntArray
    fun get__er_aw(): IntArray
    fun get__er_ay(): IntArray
    fun get__er_az(): IntArray
    fun get__er_bc(): IntArray
    fun get__er_bd(): IntArray
    fun get__er_bh(): IntArray
    fun get__er_bi(): IntArray
    fun get__er_bj(): IntArray
    fun get__er_bl(): IntArray
    fun get__er_bm(): IntArray
    fun get__er_bz(): IntArray
    fun get__er_ac(): Array<IntArray>
    fun get__er_af(): Array<IntArray>
    fun get__ep_h(): Int
    fun get__ep_i(): Int
    fun get__ep_m(): Int
    fun get__ep_x(): Int
    fun get__eq_t(): Boolean
    fun get__eq_k(): Boolean
    fun get__eq_z(): Boolean
    fun get__eq_b(): IntArray
    fun get__eq_l(): IntArray
    fun get__ec_am(): Boolean
    fun get__ec_aq(): Boolean
    fun get__ec_av(): Int
    fun get__ec_q(): Int
    fun get__ec_ac(): IntArray
    fun get__ec_af(): IntArray
    fun get__ec_aj(): IntArray
    fun get__ec_ak(): IntArray
    fun get__ec_aw(): IntArray
    fun get__ec_ay(): IntArray
    fun get__ec_bl(): IntArray
    fun get__ej_s(): AbstractArchive
    fun get__ej_au(): String
    fun get__ej_o(): IndexedSprite
    fun get__eb_c(): Int
    fun get__et_m(): Int
    fun get__ew_le(): Component
    fun get__ei_h(): Boolean
    fun get__fv_rn(): Int
    fun get__fk_ei(): IntArray
    fun get__fe_m(): Array<ShortArray>
    fun get__fi_x(): Array<Array<ByteArray>>
    fun get__fo_w(): IntArray
    fun get__fn_i(): Any
    fun get__fw_z(): Boolean
    fun get__fw_rt(): Int
    fun get__fw_k(): Any
    fun get__fw_s(): Any
    fun get__gx_i(): Int
    fun get__gx_o(): Int
    fun get__gx_g(): IntArray
    fun get__gx_w(): IntArray
    fun get__gx_s(): Array<IntArray>
    fun get__gx_t(): Array<IntArray>
    fun get__ga_a(): ServerProt
    fun get__ga_aa(): ServerProt
    fun get__ga_ab(): ServerProt
    fun get__ga_ac(): ServerProt
    fun get__ga_ad(): ServerProt
    fun get__ga_ae(): ServerProt
    fun get__ga_af(): ServerProt
    fun get__ga_ag(): ServerProt
    fun get__ga_ah(): ServerProt
    fun get__ga_ai(): ServerProt
    fun get__ga_aj(): ServerProt
    fun get__ga_ak(): ServerProt
    fun get__ga_al(): ServerProt
    fun get__ga_am(): ServerProt
    fun get__ga_an(): ServerProt
    fun get__ga_ao(): ServerProt
    fun get__ga_ap(): ServerProt
    fun get__ga_aq(): ServerProt
    fun get__ga_ar(): ServerProt
    fun get__ga_as(): ServerProt
    fun get__ga_at(): ServerProt
    fun get__ga_au(): ServerProt
    fun get__ga_av(): ServerProt
    fun get__ga_aw(): ServerProt
    fun get__ga_ax(): ServerProt
    fun get__ga_ay(): ServerProt
    fun get__ga_az(): ServerProt
    fun get__ga_b(): ServerProt
    fun get__ga_ba(): ServerProt
    fun get__ga_bb(): ServerProt
    fun get__ga_bc(): ServerProt
    fun get__ga_bd(): ServerProt
    fun get__ga_be(): ServerProt
    fun get__ga_bf(): ServerProt
    fun get__ga_bg(): ServerProt
    fun get__ga_bh(): ServerProt
    fun get__ga_bi(): ServerProt
    fun get__ga_bj(): ServerProt
    fun get__ga_bk(): ServerProt
    fun get__ga_bl(): ServerProt
    fun get__ga_bm(): ServerProt
    fun get__ga_bn(): ServerProt
    fun get__ga_bo(): ServerProt
    fun get__ga_bp(): ServerProt
    fun get__ga_bq(): ServerProt
    fun get__ga_br(): ServerProt
    fun get__ga_bs(): ServerProt
    fun get__ga_bt(): ServerProt
    fun get__ga_bu(): ServerProt
    fun get__ga_bv(): ServerProt
    fun get__ga_bw(): ServerProt
    fun get__ga_bx(): ServerProt
    fun get__ga_by(): ServerProt
    fun get__ga_bz(): ServerProt
    fun get__ga_c(): ServerProt
    fun get__ga_ca(): ServerProt
    fun get__ga_ce(): ServerProt
    fun get__ga_cg(): ServerProt
    fun get__ga_ci(): ServerProt
    fun get__ga_cn(): ServerProt
    fun get__ga_cr(): ServerProt
    fun get__ga_ct(): ServerProt
    fun get__ga_cv(): ServerProt
    fun get__ga_d(): ServerProt
    fun get__ga_e(): ServerProt
    fun get__ga_f(): ServerProt
    fun get__ga_g(): ServerProt
    fun get__ga_h(): ServerProt
    fun get__ga_i(): ServerProt
    fun get__ga_j(): ServerProt
    fun get__ga_k(): ServerProt
    fun get__ga_l(): ServerProt
    fun get__ga_m(): ServerProt
    fun get__ga_n(): ServerProt
    fun get__ga_o(): ServerProt
    fun get__ga_p(): ServerProt
    fun get__ga_q(): ServerProt
    fun get__ga_r(): ServerProt
    fun get__ga_s(): ServerProt
    fun get__ga_t(): ServerProt
    fun get__ga_u(): ServerProt
    fun get__ga_v(): ServerProt
    fun get__ga_w(): ServerProt
    fun get__ga_x(): ServerProt
    fun get__ga_y(): ServerProt
    fun get__ga_z(): ServerProt
    fun get__gf_a(): ClientProt
    fun get__gf_aa(): ClientProt
    fun get__gf_ab(): ClientProt
    fun get__gf_ac(): ClientProt
    fun get__gf_ad(): ClientProt
    fun get__gf_ae(): ClientProt
    fun get__gf_af(): ClientProt
    fun get__gf_ag(): ClientProt
    fun get__gf_ah(): ClientProt
    fun get__gf_ai(): ClientProt
    fun get__gf_aj(): ClientProt
    fun get__gf_ak(): ClientProt
    fun get__gf_al(): ClientProt
    fun get__gf_am(): ClientProt
    fun get__gf_an(): ClientProt
    fun get__gf_ao(): ClientProt
    fun get__gf_ap(): ClientProt
    fun get__gf_aq(): ClientProt
    fun get__gf_ar(): ClientProt
    fun get__gf_as(): ClientProt
    fun get__gf_at(): ClientProt
    fun get__gf_au(): ClientProt
    fun get__gf_av(): ClientProt
    fun get__gf_aw(): ClientProt
    fun get__gf_ax(): ClientProt
    fun get__gf_ay(): ClientProt
    fun get__gf_az(): ClientProt
    fun get__gf_b(): ClientProt
    fun get__gf_ba(): ClientProt
    fun get__gf_bb(): ClientProt
    fun get__gf_bc(): ClientProt
    fun get__gf_bd(): ClientProt
    fun get__gf_be(): ClientProt
    fun get__gf_bf(): ClientProt
    fun get__gf_bg(): ClientProt
    fun get__gf_bh(): ClientProt
    fun get__gf_bi(): ClientProt
    fun get__gf_bj(): ClientProt
    fun get__gf_bk(): ClientProt
    fun get__gf_bm(): ClientProt
    fun get__gf_bo(): ClientProt
    fun get__gf_bp(): ClientProt
    fun get__gf_bq(): ClientProt
    fun get__gf_br(): ClientProt
    fun get__gf_bs(): ClientProt
    fun get__gf_bt(): ClientProt
    fun get__gf_bu(): ClientProt
    fun get__gf_bv(): ClientProt
    fun get__gf_bw(): ClientProt
    fun get__gf_bx(): ClientProt
    fun get__gf_by(): ClientProt
    fun get__gf_bz(): ClientProt
    fun get__gf_c(): ClientProt
    fun get__gf_ca(): ClientProt
    fun get__gf_cc(): ClientProt
    fun get__gf_cd(): ClientProt
    fun get__gf_ce(): ClientProt
    fun get__gf_cf(): ClientProt
    fun get__gf_cg(): ClientProt
    fun get__gf_ch(): ClientProt
    fun get__gf_ci(): ClientProt
    fun get__gf_cj(): ClientProt
    fun get__gf_ck(): ClientProt
    fun get__gf_cm(): ClientProt
    fun get__gf_cn(): ClientProt
    fun get__gf_co(): ClientProt
    fun get__gf_cp(): ClientProt
    fun get__gf_cq(): ClientProt
    fun get__gf_cr(): ClientProt
    fun get__gf_cs(): ClientProt
    fun get__gf_ct(): ClientProt
    fun get__gf_cu(): ClientProt
    fun get__gf_cv(): ClientProt
    fun get__gf_cw(): ClientProt
    fun get__gf_cx(): ClientProt
    fun get__gf_cz(): ClientProt
    fun get__gf_d(): ClientProt
    fun get__gf_e(): ClientProt
    fun get__gf_f(): ClientProt
    fun get__gf_g(): ClientProt
    fun get__gf_h(): ClientProt
    fun get__gf_i(): ClientProt
    fun get__gf_j(): ClientProt
    fun get__gf_k(): ClientProt
    fun get__gf_l(): ClientProt
    fun get__gf_m(): ClientProt
    fun get__gf_n(): ClientProt
    fun get__gf_o(): ClientProt
    fun get__gf_p(): ClientProt
    fun get__gf_r(): ClientProt
    fun get__gf_s(): ClientProt
    fun get__gf_t(): ClientProt
    fun get__gf_u(): ClientProt
    fun get__gf_v(): ClientProt
    fun get__gf_w(): ClientProt
    fun get__gf_x(): ClientProt
    fun get__gf_y(): ClientProt
    fun get__gf_z(): ClientProt
    fun get__gf_bl(): ClientProt
    fun get__gf_bn(): ClientProt
    fun get__gf_q(): ClientProt
    fun get__gc_i(): LoginProt
    fun get__gc_s(): LoginProt
    fun get__gc_t(): LoginProt
    fun get__gc_z(): LoginProt
    fun get__gc_gq(): Sprite
    fun get__gc_k(): LoginProt
    fun get__gc_o(): LoginProt
    fun get__gc_w(): Array<LoginProt>
    fun get__gb_o(): Int
    fun get__gp_z(): IntArray
    fun get__gl_bw(): String
    fun get__gg_o(): AbstractArchive
    fun get__gg_sm(): Int
    fun get__gg_q(): Array<Array<IntArray>>
    fun get__go_h(): IndexedSprite
    fun get__gi_i(): Int
    fun get__gi_k(): AbstractArchive
    fun get__gi_z(): AbstractArchive
    fun get__ge_br(): Array<Sprite>
    fun get__he_bn(): Array<IndexedSprite>
    fun get__hf_m(): ByteArray
    fun get__hb_ar(): Bounds
    fun get__hh_g(): IndexedSprite
    fun get__hk_x(): ShortArray
    fun get__hk_s(): Any
    fun get__hk_k(): Array<String>
    fun get__hk_z(): Array<Array<String>>
    fun get__hp_o(): Int
    fun get__ho_ns(): Int
    fun get__hz_w(): Int
    fun get__ha_cq(): Int
    fun get__ha_n(): IntArray
    fun get__hc_s(): ShortArray
    fun get__hc_z(): ShortArray
    fun get__hc_k(): Array<ShortArray>
    fun get__hc_t(): Array<ShortArray>
    fun get__hu_rs(): Int
    fun get__hq_f(): Boolean
    fun get__hq_m(): AbstractArchive
    fun get__hq_c(): EvictingDualNodeHashTable
    fun get__hq_h(): EvictingDualNodeHashTable
    fun get__hs_g(): Int
    fun get__hs_n(): IndexedSprite
    fun get__hw_mx(): Int
    fun get__hy_ac(): String
    fun get__hy_ad(): String
    fun get__hy_af(): String
    fun get__hy_ah(): String
    fun get__hy_ai(): String
    fun get__hy_aj(): String
    fun get__hy_ak(): String
    fun get__hy_al(): String
    fun get__hy_as(): String
    fun get__hy_av(): String
    fun get__hy_aw(): String
    fun get__hy_ax(): String
    fun get__hy_ay(): String
    fun get__hy_az(): String
    fun get__hy_ba(): String
    fun get__hy_bb(): String
    fun get__hy_bc(): String
    fun get__hy_bd(): String
    fun get__hy_be(): String
    fun get__hy_bf(): String
    fun get__hy_bg(): String
    fun get__hy_bh(): String
    fun get__hy_bi(): String
    fun get__hy_bj(): String
    fun get__hy_bk(): String
    fun get__hy_bl(): String
    fun get__hy_bm(): String
    fun get__hy_bn(): String
    fun get__hy_bo(): String
    fun get__hy_bp(): String
    fun get__hy_bq(): String
    fun get__hy_br(): String
    fun get__hy_bs(): String
    fun get__hy_bt(): String
    fun get__hy_bu(): String
    fun get__hy_bv(): String
    fun get__hy_bw(): String
    fun get__hy_bx(): String
    fun get__hy_by(): String
    fun get__hy_bz(): String
    fun get__hy_ca(): String
    fun get__hy_cb(): String
    fun get__hy_cc(): String
    fun get__hy_cd(): String
    fun get__hy_ce(): String
    fun get__hy_cf(): String
    fun get__hy_cg(): String
    fun get__hy_ch(): String
    fun get__hy_ci(): String
    fun get__hy_cj(): String
    fun get__hy_ck(): String
    fun get__hy_cl(): String
    fun get__hy_cm(): String
    fun get__hy_cn(): String
    fun get__hy_co(): String
    fun get__hy_cp(): String
    fun get__hy_cq(): String
    fun get__hy_cr(): String
    fun get__hy_cs(): String
    fun get__hy_ct(): String
    fun get__hy_cu(): String
    fun get__hy_cv(): String
    fun get__hy_cw(): String
    fun get__hy_cx(): String
    fun get__hy_cy(): String
    fun get__hy_cz(): String
    fun get__hy_da(): String
    fun get__hy_db(): String
    fun get__hy_dd(): String
    fun get__hy_de(): String
    fun get__hy_dg(): String
    fun get__hy_dh(): String
    fun get__hy_di(): String
    fun get__hy_dj(): String
    fun get__hy_dk(): String
    fun get__hy_dl(): String
    fun get__hy_dm(): String
    fun get__hy_dn(): String
    fun get__hy_do(): String
    fun get__hy_dp(): String
    fun get__hy_dq(): String
    fun get__hy_dr(): String
    fun get__hy_ds(): String
    fun get__hy_dt(): String
    fun get__hy_du(): String
    fun get__hy_dv(): String
    fun get__hy_dw(): String
    fun get__hy_dx(): String
    fun get__hy_dy(): String
    fun get__hy_dz(): String
    fun get__hy_eb(): String
    fun get__hy_ec(): String
    fun get__hy_ee(): String
    fun get__hy_ef(): String
    fun get__hy_eg(): String
    fun get__hy_eh(): String
    fun get__hy_ej(): String
    fun get__hy_ek(): String
    fun get__hy_em(): String
    fun get__hy_en(): String
    fun get__hy_eo(): String
    fun get__hy_ep(): String
    fun get__hy_eq(): String
    fun get__hy_er(): String
    fun get__hy_es(): String
    fun get__hy_et(): String
    fun get__hy_eu(): String
    fun get__hy_ew(): String
    fun get__hy_ex(): String
    fun get__hy_ey(): String
    fun get__hy_ez(): String
    fun get__hy_fb(): String
    fun get__hy_fc(): String
    fun get__hy_ff(): String
    fun get__hy_fg(): String
    fun get__hy_fh(): String
    fun get__hy_fl(): String
    fun get__hy_fm(): String
    fun get__hy_fo(): String
    fun get__hy_ft(): String
    fun get__hy_fu(): String
    fun get__hy_ga(): String
    fun get__hy_gb(): String
    fun get__hy_gc(): String
    fun get__hy_gd(): String
    fun get__hy_ge(): String
    fun get__hy_gf(): String
    fun get__hy_gg(): String
    fun get__hy_gh(): String
    fun get__hy_gi(): String
    fun get__hy_gj(): String
    fun get__hy_gk(): String
    fun get__hy_gl(): String
    fun get__hy_gm(): String
    fun get__hy_gn(): String
    fun get__hy_go(): String
    fun get__hy_gp(): String
    fun get__hy_gq(): String
    fun get__hy_gr(): String
    fun get__hy_gs(): String
    fun get__hy_gt(): String
    fun get__hy_gu(): String
    fun get__hy_gv(): String
    fun get__hy_gw(): String
    fun get__hy_gx(): String
    fun get__hy_gy(): String
    fun get__hy_gz(): String
    fun get__hy_hb(): String
    fun get__hy_hd(): String
    fun get__hy_he(): String
    fun get__hy_hf(): String
    fun get__hy_hh(): String
    fun get__hy_hi(): String
    fun get__hy_hj(): String
    fun get__hy_hk(): String
    fun get__hy_hm(): String
    fun get__hy_hn(): String
    fun get__hy_hp(): String
    fun get__hy_hw(): String
    fun get__hy_hx(): String
    fun get__hy_hy(): String
    fun get__hy_ib(): String
    fun get__hy_ie(): String
    fun get__hy_if(): String
    fun get__hy_ig(): String
    fun get__hy_ih(): String
    fun get__hy_ij(): String
    fun get__hy_ik(): String
    fun get__hy_il(): String
    fun get__hy_im(): String
    fun get__hy_in(): String
    fun get__hy_ir(): String
    fun get__hy_is(): String
    fun get__hy_it(): String
    fun get__hy_iu(): String
    fun get__hy_iv(): String
    fun get__hy_ix(): String
    fun get__hy_iy(): String
    fun get__hy_iz(): String
    fun get__hy_ja(): String
    fun get__hy_jb(): String
    fun get__hy_jc(): String
    fun get__hy_jd(): String
    fun get__hy_je(): String
    fun get__hy_jf(): String
    fun get__hy_jg(): String
    fun get__hy_jh(): String
    fun get__hy_ji(): String
    fun get__hy_jj(): String
    fun get__hy_jk(): String
    fun get__hy_jl(): String
    fun get__hy_jm(): String
    fun get__hy_jn(): String
    fun get__hy_jo(): String
    fun get__hy_jp(): String
    fun get__hy_jq(): String
    fun get__hy_jr(): String
    fun get__hy_js(): String
    fun get__hy_jt(): String
    fun get__hy_ju(): String
    fun get__hy_jv(): String
    fun get__hy_jw(): String
    fun get__hy_jx(): String
    fun get__hy_jy(): String
    fun get__hy_jz(): String
    fun get__hy_ka(): String
    fun get__hy_kb(): String
    fun get__hy_kc(): String
    fun get__hy_kd(): String
    fun get__hy_ke(): String
    fun get__hy_kh(): String
    fun get__hy_kk(): String
    fun get__hy_kl(): String
    fun get__hy_km(): String
    fun get__hy_ko(): String
    fun get__hy_kp(): String
    fun get__hy_ks(): String
    fun get__hy_kt(): String
    fun get__hy_ku(): String
    fun get__hy_kw(): String
    fun get__hy_kx(): String
    fun get__hy_m(): String
    fun get__hy_n(): String
    fun get__hy_w(): String
    fun get__hy_aq(): String
    fun get__ia_d(): Int
    fun get__ix_d(): IndexedSprite
    fun get__ix_x(): PlayerType
    fun get__ij_k(): ServerBuild
    fun get__ij_s(): ServerBuild
    fun get__ij_t(): ServerBuild
    fun get__ij_z(): ServerBuild
    fun get__is_o(): StudioGame
    fun get__is_i(): StudioGame
    fun get__is_k(): StudioGame
    fun get__is_s(): StudioGame
    fun get__is_t(): StudioGame
    fun get__is_z(): StudioGame
    fun get__ic_y(): Int
    fun get__ip_s(): Int
    fun get__ip_ba(): IndexedSprite
    fun get__ii_u(): Byte
    fun get__ii_f(): Int
    fun get__ii_k(): Int
    fun get__ii_s(): Long
    fun get__it_jh(): Component
    fun get__iq_k(): EvictingDualNodeHashTable
    fun get__iq_z(): AbstractArchive
    fun get__ik_k(): Int
    fun get__ik_z(): AbstractArchive
    fun get__iv_z(): AbstractArchive
    fun get__ib_z(): AbstractArchive
    fun get__ib_k(): EvictingDualNodeHashTable
    fun get__ih_gs(): Int
    fun get__iu_k(): EvictingDualNodeHashTable
    fun get__iu_z(): AbstractArchive
    fun get__ie_s(): Int
    fun get__ie_k(): AbstractArchive
    fun get__ir_k(): AbstractArchive
    fun get__ir_z(): AbstractArchive
    fun get__il_z(): AbstractArchive
    fun get__jj_k(): EvictingDualNodeHashTable
    fun get__jj_z(): AbstractArchive
    fun get__jd_i(): EvictingDualNodeHashTable
    fun get__jd_k(): AbstractArchive
    fun get__jd_s(): AbstractArchive
    fun get__jd_z(): AbstractArchive
    fun get__jg_w(): Array<UnlitModel>
    fun get__jg_o(): EvictingDualNodeHashTable
    fun get__jq_w(): Boolean
    fun get__jt_k(): EvictingDualNodeHashTable
    fun get__jm_i(): EvictingDualNodeHashTable
    fun get__jm_k(): AbstractArchive
    fun get__ja_ae(): Any
    fun get__js_rj(): Int
    fun get__ku_t(): IntArray
    fun get__kh_i(): IndexedSprite
    fun get__kt_o(): Array<Array<ByteArray>>
    fun get__ks_k(): Array<Long>
    fun get__ke_k(): Array<Char>
    fun get__ke_s(): Array<Char>
    fun get__ke_z(): Array<Char>
    fun get__ke_t(): IntArray
    fun get__kz_v(): Int
    fun get__kz_eo(): Archive
    fun get__kz_gg(): Sprite
    fun get__ky_aa(): Any
    fun get__kf_w(): IntArray
    fun get__kf_m(): Array<Long>
    fun get__kg_g(): Array<Array<ByteArray>>
    fun get__kg_w(): IntArray
    fun get__kg_x(): IntArray
    fun get__lg_x(): Sprite
    fun get__lm_z(): RectangleMode
    fun get__lm_k(): RectangleMode
    fun get__lm_s(): RectangleMode
    fun get__lj_k(): Int
    fun get__lj_s(): Int
    fun get__lj_z(): Int
    fun get__lj_i(): IntArray
    fun get__lj_o(): IntArray
    fun get__lj_x(): IntArray
    fun get__lh_r(): Int
    fun get__mp_m(): IntArray
    fun get__mp_n(): IntArray
    fun get__mu_g(): LoginType
    fun get__mu_z(): LoginType
    fun get__mu_i(): LoginType
    fun get__mu_k(): LoginType
    fun get__mu_o(): LoginType
    fun get__mu_s(): LoginType
    fun get__mu_t(): LoginType
    fun get__mu_w(): LoginType
    fun get__mu_x(): LoginType
    fun get__mi_s(): Array<Char>
    fun get__mi_t(): Array<Char>
}
