package com.p3achb0t.api.interfaces

interface Client : GameShell {
    fun getVarbit(id: Int): Int
    fun doAction(actionParam: Int, widgetID: Int, menuAction: Int, id: Int, menuOption: String, menuTarget: String, mouseX: Int, mouseY: Int, dummy: Byte=0)
    fun setScene_selectedX(x: Int)
    fun setScene_selectedY(y: Int)
    fun setViewportWalking()
    fun getAbstractFont_alpha(): Int
    fun getAbstractFont_color(): Int
    fun getAbstractFont_justificationCurrent(): Int
    fun getAbstractFont_justificationTotal(): Int
    fun getAbstractFont_lines(): Array<String>
    fun getAbstractFont_modIconSprites(): Array<IndexedSprite>
    fun getAbstractFont_previousColor(): Int
    fun getAbstractFont_previousShadow(): Int
    fun getAbstractFont_random(): Any
    fun getAbstractFont_shadow(): Int
    fun getAbstractFont_strike(): Int
    fun getAbstractFont_underline(): Int
    fun getArchiveDiskActionHandler_lock(): Any
    fun getArchiveDiskActionHandler_requestQueue(): NodeDeque
    fun getArchiveDiskActionHandler_responseQueue(): NodeDeque
    fun getArchiveDiskActionHandler_thread(): Any
    fun getArchiveDisk_buffer(): ByteArray
    fun getArchive_crc(): Any
    fun getAttackOption_alwaysRightClick(): AttackOption
    fun getAttackOption_dependsOnCombatLevels(): AttackOption
    fun getAttackOption_hidden(): AttackOption
    fun getAttackOption_leftClickWhereAvailable(): AttackOption
    fun getByteArrayPool_large(): Array<ByteArray>
    fun getByteArrayPool_largeCount(): Int
    fun getByteArrayPool_medium(): Array<ByteArray>
    fun getByteArrayPool_mediumCount(): Int
    fun getByteArrayPool_small(): Array<ByteArray>
    fun getByteArrayPool_smallCount(): Int
    fun getBzip2Decompressor_state(): Bzip2State
    fun getClientScript_cached(): EvictingDualNodeHashTable
    fun getComponent_archive(): AbstractArchive
    fun getComponent_cachedFonts(): EvictingDualNodeHashTable
    fun getComponent_cachedModels(): EvictingDualNodeHashTable
    fun getDefaultsGroup_graphics(): DefaultsGroup
    fun getEnumType_archive(): AbstractArchive
    fun getEnumType_cached(): EvictingDualNodeHashTable
    fun getFontName_bold12(): FontName
    fun getFontName_plain11(): FontName
    fun getFontName_plain12(): FontName
    fun getFontName_verdana11(): FontName
    fun getFontName_verdana13(): FontName
    fun getFontName_verdana15(): FontName
    fun getFormatting_colorEndTag(): String
    fun getFormatting_comma(): String
    fun getFormatting_lineBreakTag(): String
    fun getFormatting_pipe(): String
    fun getFormatting_rightArrow(): String
    fun getFormatting_rightParenthesis(): String
    fun getFormatting_spaceLeftParenthesis(): String
    fun getFormatting_true(): String
    fun getHeadbarType_cached(): EvictingDualNodeHashTable
    fun getHeadbarType_cachedSprites(): EvictingDualNodeHashTable
    fun getHitmarkType_cached(): EvictingDualNodeHashTable
    fun getHitmarkType_cachedFonts(): EvictingDualNodeHashTable
    fun getIDKType_archive(): AbstractArchive
    fun getIDKType_cached(): EvictingDualNodeHashTable
    fun getInstrument_delays(): IntArray
    fun getInstrument_noise(): IntArray
    fun getInstrument_phases(): IntArray
    fun getInstrument_pitchBaseSteps(): IntArray
    fun getInstrument_pitchSteps(): IntArray
    fun getInstrument_samples(): IntArray
    fun getInstrument_sine(): IntArray
    fun getInstrument_volumeSteps(): IntArray
    fun getInterpreter_arrayLengths(): IntArray
    fun getInterpreter_arrays(): Array<IntArray>
    fun getInterpreter_calendar(): Any
    fun getInterpreter_frameDepth(): Int
    fun getInterpreter_frames(): Array<ClientScriptFrame>
    fun getInterpreter_intLocals(): IntArray
    fun getInterpreter_intStack(): IntArray
    fun getInterpreter_intStackSize(): Int
    fun getInterpreter_stringLocals(): Array<String>
    fun getInterpreter_stringStack(): Array<String>
    fun getInterpreter_stringStackSize(): Int
    fun getKeyHandler_idleCycles(): Int
    fun getKeyHandler_instance(): KeyHandler
    fun getKeyHandler_keyCodes(): IntArray
    fun getKeyHandler_pressedKeys(): BooleanArray
    fun getLocType_archive(): AbstractArchive
    fun getLocType_cached(): EvictingDualNodeHashTable
    fun getLocType_cachedModels(): EvictingDualNodeHashTable
    fun getLocType_cachedUnlitModels(): EvictingDualNodeHashTable
    fun getLocType_isLowDetail(): Boolean
    fun getLocType_modelArchive(): AbstractArchive
    fun getLogin_loadingPercent(): Int
    fun getLogin_loadingText(): String
    fun getLogin_password(): String
    fun getLogin_response0(): String
    fun getLogin_response1(): String
    fun getLogin_response2(): String
    fun getLogin_response3(): String
    fun getLogin_username(): String
    fun getMapElementType_cached(): Array<MapElementType>
    fun getMapElementType_cachedSprites(): EvictingDualNodeHashTable
    fun getMapElementType_count(): Int
    fun getMessages_channels(): Any
    fun getMessages_count(): Int
    fun getMessages_hashTable(): IterableNodeHashTable
    fun getMessages_queue(): IterableDualNodeQueue
    fun getModel_cosine(): IntArray
    fun getModel_sharedSequenceModel(): Model
    fun getModel_sharedSequenceModelFaceAlphas(): ByteArray
    fun getModel_sharedSpotAnimationModel(): Model
    fun getModel_sharedSpotAnimationModelFaceAlphas(): ByteArray
    fun getModel_sine(): IntArray
    fun getModel_transformTempX(): Int
    fun getModel_transformTempY(): Int
    fun getModel_transformTempZ(): Int
    fun getMouseHandler_currentButton(): Int
    fun getMouseHandler_currentButton0(): Int
    fun getMouseHandler_idleCycles(): Int
    fun getMouseHandler_instance(): MouseHandler
    fun getMouseHandler_lastButton(): Int
    fun getMouseHandler_lastButton0(): Int
    fun getMouseHandler_lastPressedTimeMillis(): Long
    fun getMouseHandler_lastPressedTimeMillis0(): Long
    fun getMouseHandler_lastPressedX(): Int
    fun getMouseHandler_lastPressedX0(): Int
    fun getMouseHandler_lastPressedY(): Int
    fun getMouseHandler_lastPressedY0(): Int
    fun getMouseHandler_millis(): Long
    fun getMouseHandler_millis0(): Long
    fun getMouseHandler_x(): Int
    fun getMouseHandler_x0(): Int
    fun getMouseHandler_y(): Int
    fun getMouseHandler_y0(): Int
    fun getNPCType_archive(): AbstractArchive
    fun getNPCType_cached(): EvictingDualNodeHashTable
    fun getNPCType_cachedModels(): EvictingDualNodeHashTable
    fun getNPCType_modelArchive(): AbstractArchive
    fun getNetCache_archives(): Array<Archive>
    fun getNetCache_crc(): Any
    fun getNetCache_crcMismatches(): Int
    fun getNetCache_currentResponse(): NetFileRequest
    fun getNetCache_ioExceptions(): Int
    fun getNetCache_pendingPriorityResponses(): NodeHashTable
    fun getNetCache_pendingPriorityResponsesCount(): Int
    fun getNetCache_pendingPriorityWrites(): NodeHashTable
    fun getNetCache_pendingPriorityWritesCount(): Int
    fun getNetCache_pendingResponses(): NodeHashTable
    fun getNetCache_pendingResponsesCount(): Int
    fun getNetCache_pendingWrites(): NodeHashTable
    fun getNetCache_pendingWritesCount(): Int
    fun getNetCache_pendingWritesQueue(): DualNodeDeque
    fun getNetCache_reference(): Packet
    fun getNetCache_responseArchiveBuffer(): Packet
    fun getNetCache_responseHeaderBuffer(): Packet
    fun getNetCache_socket(): AbstractSocket
    fun getObjType_archive(): AbstractArchive
    fun getObjType_cached(): EvictingDualNodeHashTable
    fun getObjType_cachedModels(): EvictingDualNodeHashTable
    fun getObjType_modelArchive(): AbstractArchive
    fun getPacketBit_masks(): IntArray
    fun getParamType_cached(): EvictingDualNodeHashTable
    fun getPcmPlayer_sampleRate(): Int
    fun getPlayerAppearance_cachedModels(): EvictingDualNodeHashTable
    fun getPlayerType_hardcoreIronman(): PlayerType
    fun getPlayerType_ironman(): PlayerType
    fun getPlayerType_jagexModerator(): PlayerType
    fun getPlayerType_normal(): PlayerType
    fun getPlayerType_playerModerator(): PlayerType
    fun getPlayerType_ultimateIronman(): PlayerType
    fun getPlayers_count(): Int
    fun getPlayers_indices(): IntArray
    fun getPlayers_orientations(): IntArray
    fun getPlayers_regions(): IntArray
    fun getPlayers_targetIndices(): IntArray
    fun getRasterizer2D_height(): Int
    fun getRasterizer2D_pixels(): IntArray
    fun getRasterizer2D_width(): Int
    fun getRasterizer2D_xClipEnd(): Int
    fun getRasterizer2D_xClipStart(): Int
    fun getRasterizer2D_yClipEnd(): Int
    fun getRasterizer2D_yClipStart(): Int
    fun getRasterizer3D_alpha(): Int
    fun getRasterizer3D_clipHeight(): Int
    fun getRasterizer3D_clipMidX(): Int
    fun getRasterizer3D_clipMidX2(): Int
    fun getRasterizer3D_clipMidY(): Int
    fun getRasterizer3D_clipMidY2(): Int
    fun getRasterizer3D_clipNegativeMidX(): Int
    fun getRasterizer3D_clipNegativeMidY(): Int
    fun getRasterizer3D_clipWidth(): Int
    fun getRasterizer3D_colorPalette(): IntArray
    fun getRasterizer3D_cosine(): IntArray
    fun getRasterizer3D_isLowDetailTexture(): Boolean
    fun getRasterizer3D_rowOffsets(): IntArray
    fun getRasterizer3D_sine(): IntArray
    fun getRasterizer3D_textureLoader(): TextureLoader
    fun getRasterizer3D_zoom(): Int
    fun getScene_cameraPitchCosine(): Int
    fun getScene_cameraPitchSine(): Int
    fun getScene_cameraX(): Int
    fun getScene_cameraXTile(): Int
    fun getScene_cameraXTileMax(): Int
    fun getScene_cameraXTileMin(): Int
    fun getScene_cameraY(): Int
    fun getScene_cameraYTile(): Int
    fun getScene_cameraYTileMax(): Int
    fun getScene_cameraYTileMin(): Int
    fun getScene_cameraYawCosine(): Int
    fun getScene_cameraYawSine(): Int
    fun getScene_cameraZ(): Int
    fun getScene_currentOccluders(): Array<Occluder>
    fun getScene_currentOccludersCount(): Int
    fun getScene_drawnCount(): Int
    fun getScene_isLowDetail(): Boolean
    fun getScene_plane(): Int
    fun getScene_planeOccluderCounts(): IntArray
    fun getScene_planeOccluders(): Array<Array<Occluder>>
    fun getScene_selectedPlane(): Int
    fun getScene_selectedScreenX(): Int
    fun getScene_selectedScreenY(): Int
    fun getScene_selectedX(): Int
    fun getScene_selectedY(): Int
    fun getScene_tilesDeque(): NodeDeque
    fun getScene_viewportXCenter(): Int
    fun getScene_viewportXMax(): Int
    fun getScene_viewportXMin(): Int
    fun getScene_viewportYCenter(): Int
    fun getScene_viewportYMax(): Int
    fun getScene_viewportYMin(): Int
    fun getSeqType_archive(): AbstractArchive
    fun getSeqType_cached(): EvictingDualNodeHashTable
    fun getSkills_enabled(): BooleanArray
    fun getSkills_experienceTable(): IntArray
    fun getSpotType_archive(): AbstractArchive
    fun getSpotType_cached(): EvictingDualNodeHashTable
    fun getSpotType_cachedModels(): EvictingDualNodeHashTable
    fun getSpotType_modelArchive(): AbstractArchive
    fun getSprite_cached(): EvictingDualNodeHashTable
    fun getStrings_almostEverywhere(): String
    fun getStrings_andTheProtectItemPrayerWontWork(): String
    fun getStrings_attack(): String
    fun getStrings_cancel(): String
    fun getStrings_checkingForUpdates(): String
    fun getStrings_chooseOption(): String
    fun getStrings_close(): String
    fun getStrings_connectingToServer(): String
    fun getStrings_connectingToUpdateServer(): String
    fun getStrings_connectionLost(): String
    fun getStrings_continue(): String
    fun getStrings_drop(): String
    fun getStrings_examine(): String
    fun getStrings_existingUser(): String
    fun getStrings_fromYourFriendListFirst(): String
    fun getStrings_fromYourIgnoreListFirst(): String
    fun getStrings_hasLoggedIn(): String
    fun getStrings_hasLoggedOut(): String
    fun getStrings_hidden(): String
    fun getStrings_isAlreadyOnYourFriendList(): String
    fun getStrings_level(): String
    fun getStrings_loadedConfig(): String
    fun getStrings_loadedFonts(): String
    fun getStrings_loadedInputHandler(): String
    fun getStrings_loadedInterfaces(): String
    fun getStrings_loadedSprites(): String
    fun getStrings_loadedTextures(): String
    fun getStrings_loadedTitleScreen(): String
    fun getStrings_loadedUpdateList(): String
    fun getStrings_loadedWordpack(): String
    fun getStrings_loadedWorldMap(): String
    fun getStrings_loading(): String
    fun getStrings_loadingConfig(): String
    fun getStrings_loadingFonts(): String
    fun getStrings_loadingInterfaces(): String
    fun getStrings_loadingPleaseWait(): String
    fun getStrings_loadingSprites(): String
    fun getStrings_loadingTextures(): String
    fun getStrings_loadingTitleScreen(): String
    fun getStrings_loadingWordpack(): String
    fun getStrings_loadingWorldMap(): String
    fun getStrings_login(): String
    fun getStrings_membersObject(): String
    fun getStrings_moreOptions(): String
    fun getStrings_newUser(): String
    fun getStrings_notWorkOnThisWorld(): String
    fun getStrings_null(): String
    fun getStrings_ok(): String
    fun getStrings_password(): String
    fun getStrings_pin(): String
    fun getStrings_playersCanAttackEachOther(): String
    fun getStrings_playersCanAttackEachOtherAlmostEverywhere(): String
    fun getStrings_pleaseEnterYourPassword(): String
    fun getStrings_pleaseEnterYourUsername(): String
    fun getStrings_pleaseRemoveFriend(): String
    fun getStrings_pleaseRemoveIgnore(): String
    fun getStrings_pleaseWait(): String
    fun getStrings_pleaseWaitAttemptingToReestablish(): String
    fun getStrings_preparedSoundEngine(): String
    fun getStrings_preparedVisibilityMap(): String
    fun getStrings_select(): String
    fun getStrings_skill(): String
    fun getStrings_space(): String
    fun getStrings_startingGameEngine(): String
    fun getStrings_take(): String
    fun getStrings_theProtectItemPrayerWill(): String
    fun getStrings_thisIsABetaWorld(): String
    fun getStrings_thisIsAHighRiskPvpWorld(): String
    fun getStrings_thisIsAHighRiskWorld(): String
    fun getStrings_thisIsAPvpWorld(): String
    fun getStrings_unableToFind(): String
    fun getStrings_use(): String
    fun getStrings_walkHere(): String
    fun getStrings_warning(): String
    fun getStrings_welcomeToRuneScape(): String
    fun getStrings_yourFriendListIsFull(): String
    fun getStrings_yourIgnoreListIsFull(): String
    fun getStrings_yourNormalAccountWillNotBeAffected(): String
    fun getTexture_animatedPixels(): IntArray
    fun getTiles_heights(): Array<Array<IntArray>>
    fun getTiles_minPlane(): Int
    fun getTiles_renderFlags(): Array<Array<ByteArray>>
    fun getTriBool_false(): TriBool
    fun getTriBool_true(): TriBool
    fun getTriBool_unknown(): TriBool
    fun getUnlitModel_cosine(): IntArray
    fun getUnlitModel_sine(): IntArray
    fun getVarBitType_archive(): AbstractArchive
    fun getVarBitType_cached(): EvictingDualNodeHashTable
    fun getVarps_main(): IntArray
    fun getVarps_masks(): IntArray
    fun getVarps_temp(): IntArray
    fun getViewportMouse_entityCount(): Int
    fun getViewportMouse_entityTags(): Array<Long>
    fun getViewportMouse_false0(): Boolean
    fun getViewportMouse_isInViewport(): Boolean
    fun getViewportMouse_x(): Int
    fun getViewportMouse_y(): Int
    fun getVorbisSample_bitPos(): Int
    fun getVorbisSample_blocksize0(): Int
    fun getVorbisSample_blocksize1(): Int
    fun getVorbisSample_bytePos(): Int
    fun getVorbisSample_codebooks(): Array<VorbisCodebook>
    fun getVorbisSample_floors(): Array<VorbisFloor>
    fun getVorbisSample_mappings(): Array<VorbisMapping>
    fun getVorbisSample_residues(): Array<VorbisResidue>
    fun getVorbisSample_setupHeaderLoaded(): Boolean
    fun getVorbisSample_stream(): ByteArray
    fun getWorldMapCacheName_area(): WorldMapCacheName
    fun getWorldMapCacheName_compositeMap(): WorldMapCacheName
    fun getWorldMapCacheName_compositeTexture(): WorldMapCacheName
    fun getWorldMapCacheName_details(): WorldMapCacheName
    fun getWorldMapCacheName_labels(): WorldMapCacheName
    fun getWorldMapLabelSize_large(): WorldMapLabelSize
    fun getWorldMapLabelSize_medium(): WorldMapLabelSize
    fun getWorldMapLabelSize_small(): WorldMapLabelSize
    fun getApplet(): Any
    fun getArchive0(): Archive
    fun getArchive1(): Archive
    fun getArchive10(): Archive
    fun getArchive11(): Archive
    fun getArchive12(): Archive
    fun getArchive13(): Archive
    fun getArchive14(): Archive
    fun getArchive15(): Archive
    fun getArchive2(): Archive
    fun getArchive3(): Archive
    fun getArchive4(): Archive
    fun getArchive5(): Archive
    fun getArchive6(): Archive
    fun getArchive7(): Archive
    fun getArchive8(): Archive
    fun getArchive9(): Archive
    fun getArchiveLoaderArchive(): Int
    fun getArchiveLoaders(): Any
    fun getBase37Table(): Array<Char>
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCacheDirectoryLocations(): Array<String>
    fun getCamAngleX(): Int
    fun getCamAngleY(): Int
    fun getCamFollowHeight(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvasHeight(): Int
    fun getCanvasWidth(): Int
    fun getChatEffects(): Int
    fun getClDat(): Any
    fun getClanChat(): ClanChat
    fun getClickedComponent(): Component
    fun getClickedComponentParent(): Component
    fun getClient(): Client
    fun getClientPreferences(): ClientPreferences
    fun getClientScriptEvents(): NodeDeque
    fun getClientType(): Int
    fun getClock(): Clock
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCombatTargetPlayerIndex(): Int
    fun getComponentClickMasks(): NodeHashTable
    fun getComponentClickX(): Int
    fun getComponentClickY(): Int
    fun getComponentDragDuration(): Int
    fun getCp1252AsciiExtension(): Array<Char>
    fun getCrossSprites(): Array<Sprite>
    fun getCurrentLevels(): IntArray
    fun getCurrentTimeMsLast(): Long
    fun getCurrentTimeMsOffset(): Long
    fun getCycle(): Int
    fun getDat2File(): BufferedFile
    fun getDecimator(): Decimator
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getDisplayFps(): Boolean
    fun getDragInventoryComponent(): Component
    fun getDragItemSlotDestination(): Int
    fun getDragItemSlotSource(): Int
    fun getExperience(): IntArray
    fun getFollowerIndex(): Int
    fun getFollowerOpsLowPriority(): Boolean
    fun getFontBold12(): Font
    fun getFontNameVerdana11(): FontName
    fun getFontNameVerdana13(): FontName
    fun getFontNameVerdana15(): FontName
    fun getFontPlain11(): Font
    fun getFontPlain12(): Font
    fun getFonts(): Fonts
    fun getFontsMap(): Any
    fun getFps(): Int
    fun getFriendSystem(): FriendSystem
    fun getGameBuild(): Int
    fun getGameDrawingMode(): Int
    fun getGameShell(): GameShell
    fun getGameState(): Int
    fun getGarbageCollector(): Any
    fun getGarbageCollectorLastCheckTimeMs(): Long
    fun getGarbageCollectorLastCollectionTime(): Long
    fun getGrandExchangeEvents(): GrandExchangeEvents
    fun getGrandExchangeOffers(): Array<GrandExchangeOffer>
    fun getGraphicsObjects(): NodeDeque
    fun getGzipDecompressor(): GzipDecompressor
    fun getHasFocus(): Boolean
    fun getHeadIconHintSprites(): Array<Sprite>
    fun getHeadIconPkSprites(): Array<Sprite>
    fun getHeadIconPrayerSprites(): Array<Sprite>
    fun getHintArrowHeight(): Int
    fun getHintArrowNpcIndex(): Int
    fun getHintArrowPlayerIndex(): Int
    fun getHintArrowSubX(): Int
    fun getHintArrowSubY(): Int
    fun getHintArrowType(): Int
    fun getHintArrowX(): Int
    fun getHintArrowY(): Int
    fun getHuffman(): Huffman
    fun getIdx255File(): BufferedFile
    fun getIdxCount(): Int
    fun getIdxFiles(): Array<BufferedFile>
    fun getInstanceChunkTemplates(): Array<Array<IntArray>>
    fun getInterfaceComponents(): Array<Array<Component>>
    fun getInterfaceParents(): NodeHashTable
    fun getIsCameraLocked(): Boolean
    fun getIsDraggingComponent(): Boolean
    fun getIsInInstance(): Boolean
    fun getIsItemSelected(): Int
    fun getIsKilled(): Boolean
    fun getIsLoading(): Boolean
    fun getIsLowDetail(): Boolean
    fun getIsMembersWorld(): Boolean
    fun getIsMiniMenuOpen(): Boolean
    fun getIsResizable(): Boolean
    fun getIsSpellSelected(): Boolean
    fun getIsStereo(): Boolean
    fun getItemContainers(): NodeHashTable
    fun getItemDragDuration(): Int
    fun getJavaVendor(): String
    fun getJavaVersion(): String
    fun getJs5Errors(): Int
    fun getJs5Socket(): AbstractSocket
    fun getJs5SocketTask(): Task
    fun getJs5StartTimeMs(): Long
    fun getLevels(): IntArray
    fun getLoadedInterfaces(): BooleanArray
    fun getLocalPlayer(): Player
    fun getLocalPlayerIndex(): Int
    fun getLocalPlayerName(): String
    fun getLoginState(): Int
    fun getLoginType(): LoginType
    fun getMapDotSprites(): Array<Sprite>
    fun getMapIconCount(): Int
    fun getMapIconXs(): IntArray
    fun getMapIconYs(): IntArray
    fun getMapIcons(): Array<Sprite>
    fun getMapMarkerSprites(): Array<Sprite>
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMasterDisk(): ArchiveDisk
    fun getMenuActions(): Array<String>
    fun getMenuArguments0(): IntArray
    fun getMenuArguments1(): IntArray
    fun getMenuArguments2(): IntArray
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptionsCount(): Int
    fun getMenuShiftClick(): BooleanArray
    fun getMenuTargetNames(): Array<String>
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuY(): Int
    fun getMidiPcmStream(): MidiPcmStream
    fun getMinimapState(): Int
    fun getModIconSprites(): Array<IndexedSprite>
    fun getModelViewportXs(): IntArray
    fun getModelViewportYs(): IntArray
    fun getMouseCrossColor(): Int
    fun getMouseCrossState(): Int
    fun getMouseCrossX(): Int
    fun getMouseCrossY(): Int
    fun getMouseLastLastPressedTimeMillis(): Long
    fun getMouseRecorder(): MouseRecorder
    fun getMouseWheel(): MouseWheel
    fun getMouseWheelRotation(): Int
    fun getMousedOverComponentIf1(): Component
    fun getMusicTrack(): MusicTrack
    fun getMusicTrackBoolean(): Boolean
    fun getMusicTrackFileId(): Int
    fun getMusicTrackGroupId(): Int
    fun getNpcAttackOption(): AttackOption
    fun getNpcCount(): Int
    fun getNpcIndices(): IntArray
    fun getNpcs(): Array<Npc>
    fun getObjStacks(): Array<Array<Array<NodeDeque>>>
    fun getObjectSounds(): NodeDeque
    fun getOsName(): String
    fun getOsNameLowerCase(): String
    fun getOverheadText(): Array<String>
    fun getOverheadTextAscents(): IntArray
    fun getOverheadTextColors(): IntArray
    fun getOverheadTextCount(): Int
    fun getOverheadTextCyclesRemaining(): IntArray
    fun getOverheadTextEffects(): IntArray
    fun getOverheadTextLimit(): Int
    fun getOverheadTextXOffsets(): IntArray
    fun getOverheadTextXs(): IntArray
    fun getOverheadTextYs(): IntArray
    fun getPacketBitNodes(): Array<PacketBitNode>
    fun getPacketWriter(): PacketWriter
    fun getPcmPlayer0(): PcmPlayer
    fun getPcmPlayer1(): PcmPlayer
    fun getPcmPlayerCount(): Int
    fun getPcmPlayerProvider(): PcmPlayerProvider
    fun getPcmStreamMixer(): PcmStreamMixer
    fun getPlane(): Int
    fun getPlatformInfo(): PlatformInfo
    fun getPlatformInfoProvider(): PlatformInfoProvider
    fun getPlayerAttackOption(): AttackOption
    fun getPlayerMenuActions(): Array<String>
    fun getPlayerMenuOpcodes(): IntArray
    fun getPlayerMod(): Boolean
    fun getPlayers(): Array<Player>
    fun getPort1(): Int
    fun getPort2(): Int
    fun getPort3(): Int
    fun getProjectiles(): NodeDeque
    fun getPublicChatMode(): Int
    fun getRandomDat(): BufferedFile
    fun getRasterProvider(): AbstractRasterProvider
    fun getRebootTimer(): Int
    fun getReflectionChecks(): IterableNodeDeque
    fun getRegionLandArchiveIds(): IntArray
    fun getRegionLandArchives(): Array<ByteArray>
    fun getRegionMapArchiveIds(): IntArray
    fun getRegionMapArchives(): Array<ByteArray>
    fun getRegions(): IntArray
    fun getRenderCount(): Int
    fun getRenderSelf(): Boolean
    fun getRevision(): Int
    fun getRootComponentCount(): Int
    fun getRootComponentHeights(): IntArray
    fun getRootComponentWidths(): IntArray
    fun getRootComponentXs(): IntArray
    fun getRootComponentYs(): IntArray
    fun getRootInterface(): Int
    fun getRunEnergy(): Int
    fun getScene(): Scene
    fun getSceneMinimapSprite(): Sprite
    fun getScenery(): Array<Scenery>
    fun getScrollBarSprites(): Array<IndexedSprite>
    fun getSecureRandom(): Any
    fun getSecureRandomFuture(): SecureRandomFuture
    fun getSelectedItemComponent(): Int
    fun getSelectedItemId(): Int
    fun getSelectedItemName(): String
    fun getSelectedItemSlot(): Int
    fun getSelectedSpellActionName(): String
    fun getSelectedSpellFlags(): Int
    fun getSelectedSpellName(): String
    fun getServerBuild(): ServerBuild
    fun getShiftClickDrop(): Boolean
    fun getShowLoadingMessages(): Boolean
    fun getShowMouseCross(): Boolean
    fun getShowMouseOverText(): Boolean
    fun getSocketTask(): Task
    fun getSoundCache(): SoundCache
    fun getSoundEffectCount(): Int
    fun getSoundEffectIds(): IntArray
    fun getSoundEffects(): Array<SoundEffect>
    fun getSoundSystem(): SoundSystem
    fun getSoundSystemExecutor(): Any
    fun getSpriteIds(): GraphicsDefaults
    fun getStaffModLevel(): Int
    fun getStudioGame(): StudioGame
    fun getTapToDrop(): Boolean
    fun getTaskHandler(): TaskHandler
    fun getTempMenuAction(): MiniMenuEntry
    fun getTextureProvider(): TextureProvider
    fun getTileLastDrawnActor(): Array<IntArray>
    fun getTimer(): Timer
    fun getTitleLoadingStage(): Int
    fun getUrlRequester(): UrlRequester
    fun getUseBufferedSocket(): Boolean
    fun getUserHomeDirectory(): String
    fun getVarcs(): Varcs
    fun getViewportComponent(): Component
    fun getViewportDrawCount(): Int
    fun getViewportHeight(): Int
    fun getViewportOffsetX(): Int
    fun getViewportOffsetY(): Int
    fun getViewportTempX(): Int
    fun getViewportTempY(): Int
    fun getViewportWidth(): Int
    fun getViewportZoom(): Int
    fun getVisibilityMap(): Array<Array<Array<BooleanArray>>>
    fun getVisibleTiles(): Array<BooleanArray>
    fun getWeight(): Int
    fun getWorldHost(): String
    fun getWorldId(): Int
    fun getWorldMap0(): WorldMap
    fun getWorldMapEvent(): WorldMapEvent
    fun getWorldProperties(): Int
    fun getWorlds(): Array<World>
    fun getWorldsCount(): Int
    fun getWorldsUrl(): String
    fun getXteaKeys(): Array<IntArray>
    fun get__v_z(): Array<Array<ByteArray>>
    fun get__v_ex(): IntArray
    fun get__v_bj(): String
    fun get__d_q(): Array<ByteArray>
    fun get__d_k(): Array<Array<IntArray>>
    fun get__d_bz(): IndexedSprite
    fun get__c_gj(): Int
    fun get__e_l(): Int
    fun get__e_b(): Int
    fun get__e_bh(): IndexedSprite
    fun get__q_du(): Boolean
    fun get__q_h(): Int
    fun get__l_sc(): Long
    fun get__i_c(): Any
    fun get__i_d(): Any
    fun get__i_v(): Any
    fun get__i_y(): Any
    fun get__x_gw(): Int
    fun get__g_le(): Component
    fun get__u_go(): Int
    fun get__u_rq(): Int
    fun get__t_y(): IndexedSprite
    fun get__p_l(): IntArray
    fun get__p_ac(): Any
    fun get__j_l(): Int
    fun get__j_rh(): Int
    fun get__j_ep(): Archive
    fun get__ay_sx(): Int
    fun get__am_ae(): Any
    fun get__ae_c(): WorldMapSectionType
    fun get__ae_d(): WorldMapSectionType
    fun get__ae_n(): WorldMapSectionType
    fun get__ae_v(): WorldMapSectionType
    fun get__at_nt(): Int
    fun get__ax_au(): Int
    fun get__ax_w(): IndexedSprite
    fun get__al_l(): Array<ShortArray>
    fun get__al_ji(): Component
    fun get__al_q(): Array<IntArray>
    fun get__aa_b(): IntArray
    fun get__as_y(): DemotingHashTable
    fun get__aw_gf(): Int
    fun get__aw_z(): Int
    fun get__az_ca(): Char
    fun get__az_w(): IntArray
    fun get__az_bc(): Array<Sprite>
    fun get__ai_qw(): Int
    fun get__ai_bw(): Array<IndexedSprite>
    fun get__au_nz(): Array<Component>
    fun get__ad_aw(): String
    fun get__av_rk(): Int
    fun get__bj_q(): Int
    fun get__bj_su(): ShortArray
    fun get__bi_cc(): Int
    fun get__bi_ce(): Int
    fun get__bi_cg(): Int
    fun get__bi_co(): Int
    fun get__bi_cu(): Int
    fun get__bi_cx(): Int
    fun get__bi_cm(): IntArray
    fun get__bi_cs(): IntArray
    fun get__bi_ph(): Boolean
    fun get__bi_ci(): Array<Char>
    fun get__bi_cy(): IntArray
    fun get__bi_ar(): Bounds
    fun get__bp_q(): Int
    fun get__bp_ak(): String
    fun get__bp_bv(): Array<IndexedSprite>
    fun get__bq_ao(): Int
    fun get__bx_v(): Int
    fun get__bw_i(): Int
    fun get__bw_n(): Any
    fun get__bw_v(): String
    fun get__bt_f(): Array<Long>
    fun get__bt_k(): Array<Long>
    fun get__bt_d(): Int
    fun get__bt_l(): Int
    fun get__bt_q(): Int
    fun get__bt_ax(): Any
    fun get__bl_ad(): Int
    fun get__bh_c(): Array<Array<ByteArray>>
    fun get__bh_h(): Array<Array<ByteArray>>
    fun get__bh_j(): Int
    fun get__bh_o(): Int
    fun get__bh_s(): IntArray
    fun get__bh_g(): IntArray
    fun get__bh_m(): IntArray
    fun get__bh_p(): IntArray
    fun get__bh_r(): IntArray
    fun get__bh_t(): IntArray
    fun get__bh_u(): IntArray
    fun get__bm_en(): Archive
    fun get__be_s(): IndexedSprite
    fun get__bs_s(): AbstractArchive
    fun get__bs_h(): IndexedSprite
    fun get__ba_iv(): Int
    fun get__bu_ny(): Int
    fun get__ez(): Packet
    fun get__client_iy(): Int
    fun get__client_sw(): Int
    fun get__client_ao(): Boolean
    fun get__client_bg(): Boolean
    fun get__client_cm(): Boolean
    fun get__client_ej(): Boolean
    fun get__client_fd(): Boolean
    fun get__client_hh(): Boolean
    fun get__client_ie(): Boolean
    fun get__client_ii(): Boolean
    fun get__client_jq(): Boolean
    fun get__client_nf(): Boolean
    fun get__client_no(): Boolean
    fun get__client_qy(): Boolean
    fun get__client_ki(): BooleanArray
    fun get__client_ok(): BooleanArray
    fun get__client_oq(): BooleanArray
    fun get__client_ou(): BooleanArray
    fun get__client_rj(): BooleanArray
    fun get__client_sz(): OwnWorldComparator
    fun get__client_fa(): ByteArray
    fun get__client_sq(): PlayerAppearance
    fun get__client_mh(): Component
    fun get__client_nv(): Component
    fun get__client_bz(): Int
    fun get__client_ci(): Int
    fun get__client_cu(): Int
    fun get__client_dh(): Int
    fun get__client_dj(): Int
    fun get__client_ec(): Int
    fun get__client_et(): Int
    fun get__client_ev(): Int
    fun get__client_fc(): Int
    fun get__client_ff(): Int
    fun get__client_ga(): Int
    fun get__client_gh(): Int
    fun get__client_gm(): Int
    fun get__client_gq(): Int
    fun get__client_gt(): Int
    fun get__client_gu(): Int
    fun get__client_hc(): Int
    fun get__client_hf(): Int
    fun get__client_hg(): Int
    fun get__client_hi(): Int
    fun get__client_hk(): Int
    fun get__client_hl(): Int
    fun get__client_hp(): Int
    fun get__client_ht(): Int
    fun get__client_hy(): Int
    fun get__client_if(): Int
    fun get__client_ig(): Int
    fun get__client_ij(): Int
    fun get__client_ik(): Int
    fun get__client_im(): Int
    fun get__client_io(): Int
    fun get__client_iq(): Int
    fun get__client_iu(): Int
    fun get__client_jb(): Int
    fun get__client_jk(): Int
    fun get__client_jt(): Int
    fun get__client_ju(): Int
    fun get__client_jw(): Int
    fun get__client_kb(): Int
    fun get__client_kg(): Int
    fun get__client_kw(): Int
    fun get__client_lp(): Int
    fun get__client_lx(): Int
    fun get__client_ly(): Int
    fun get__client_ma(): Int
    fun get__client_mg(): Int
    fun get__client_mi(): Int
    fun get__client_mm(): Int
    fun get__client_mq(): Int
    fun get__client_mv(): Int
    fun get__client_mw(): Int
    fun get__client_na(): Int
    fun get__client_nb(): Int
    fun get__client_np(): Int
    fun get__client_nr(): Int
    fun get__client_ns(): Int
    fun get__client_nu(): Int
    fun get__client_nx(): Int
    fun get__client_ob(): Int
    fun get__client_oc(): Int
    fun get__client_od(): Int
    fun get__client_oe(): Int
    fun get__client_ol(): Int
    fun get__client_os(): Int
    fun get__client_ov(): Int
    fun get__client_oy(): Int
    fun get__client_pa(): Int
    fun get__client_pf(): Int
    fun get__client_pg(): Int
    fun get__client_pr(): Int
    fun get__client_qd(): Int
    fun get__client_sk(): Int
    fun get__client_sn(): Int
    fun get__client_sp(): Int
    fun get__client_fg(): IntArray
    fun get__client_kf(): IntArray
    fun get__client_kn(): IntArray
    fun get__client_ng(): IntArray
    fun get__client_nh(): IntArray
    fun get__client_nm(): IntArray
    fun get__client_pb(): IntArray
    fun get__client_pi(): IntArray
    fun get__client_pk(): IntArray
    fun get__client_qa(): IntArray
    fun get__client_qg(): IntArray
    fun get__client_qt(): IntArray
    fun get__client_rc(): IntArray
    fun get__client_re(): IntArray
    fun get__client_rm(): IntArray
    fun get__client_rp(): IntArray
    fun get__client_tl(): IntArray
    fun get__client_to(): IntArray
    fun get__client_pe(): String
    fun get__client_kc(): NodeDeque
    fun get__client_om(): NodeDeque
    fun get__client_or(): NodeDeque
    fun get__client_cy(): Long
    fun get__client_ot(): Long
    fun get__client_pj(): Long
    fun get__client_py(): Array<Long>
    fun get__client_ra(): Short
    fun get__client_rf(): Short
    fun get__client_rn(): Short
    fun get__client_rs(): Short
    fun get__client_rt(): Short
    fun get__client_ru(): Short
    fun get__client_rw(): Short
    fun get__client_ry(): Short
    fun get__client_gx(): IntArray
    fun get__cd_id(): Int
    fun get__cq_z(): Int
    fun get__cq_e(): IntArray
    fun get__cq_q(): IntArray
    fun get__cq_bl(): IndexedSprite
    fun get__cb_gc(): Sprite
    fun get__cf_n(): Int
    fun get__cn_t(): Boolean
    fun get__cn_u(): Boolean
    fun get__cn_k(): Component
    fun get__cn_ea(): Int
    fun get__cn_p(): Int
    fun get__cn_j(): Double
    fun get__cn_f(): Array<String>
    fun get__cj_t(): Int
    fun get__cr_q(): ShortArray
    fun get__ca_si(): Int
    fun get__cz_h(): Any
    fun get__cz_y(): Any
    fun get__cu_n(): Any
    fun get__cu_v(): Any
    fun get__ci_ax(): Bounds
    fun get__cy_af(): Boolean
    fun get__cy_av(): Boolean
    fun get__cy_bn(): Boolean
    fun get__cy_bx(): Boolean
    fun get__cy_v(): Boolean
    fun get__cy_ae(): Int
    fun get__cy_al(): Int
    fun get__cy_at(): Int
    fun get__cy_bf(): Int
    fun get__cy_bg(): Int
    fun get__cy_bi(): Int
    fun get__cy_bm(): Int
    fun get__cy_d(): Int
    fun get__cy_u(): Int
    fun get__cy_eg(): Archive
    fun get__cy_bp(): String
    fun get__cy_br(): String
    fun get__cy_e(): Sprite
    fun get__cy_z(): Sprite
    fun get__cy_bs(): Long
    fun get__cy_by(): Long
    fun get__cy_a(): IndexedSprite
    fun get__cy_q(): IndexedSprite
    fun get__cy_c(): Array<IndexedSprite>
    fun get__cy_l(): Array<IndexedSprite>
    fun get__cx_c(): ByteArray
    fun get__cx_d(): ByteArray
    fun get__cx_a(): Int
    fun get__cx_e(): Int
    fun get__cx_q(): IntArray
    fun get__cx_w(): IntArray
    fun get__cx_k(): Packet
    fun get__cx_y(): Array<Packet>
    fun get__cw_a(): Int
    fun get__do_c(): IntArray
    fun get__do_e(): Array<ShortArray>
    fun get__dl_i(): BooleanArray
    fun get__dl_ag(): Array<Float>
    fun get__dl_am(): Array<Float>
    fun get__dl_ay(): Array<Float>
    fun get__dl_j(): Array<Float>
    fun get__dl_m(): Array<Float>
    fun get__dl_o(): Array<Float>
    fun get__dl_r(): Array<Float>
    fun get__dl_ac(): IntArray
    fun get__dl_ae(): IntArray
    fun get__dl_x(): IntArray
    fun get__dj_b(): BooleanArray
    fun get__dj_l(): IntArray
    fun get__dj_s(): IntArray
    fun get__dj_v(): Array<Float>
    fun get__dj_n(): IntArray
    fun get__dh_ai(): Boolean
    fun get__dq_eu(): Int
    fun get__dq_rl(): Int
    fun get__de_e(): Float
    fun get__de_h(): Array<Array<Float>>
    fun get__de_q(): Int
    fun get__de_z(): Array<IntArray>
    fun get__df_bl(): Int
    fun get__ek_aa(): Int
    fun get__ek_al(): IntArray
    fun get__ek_ar(): IntArray
    fun get__eo_f(): IntArray
    fun get__eo_g(): IntArray
    fun get__eo_i(): IntArray
    fun get__eo_u(): IntArray
    fun get__eo_x(): IntArray
    fun get__eo_p(): Array<IntArray>
    fun get__eo_t(): Array<IntArray>
    fun get__eg_c(): IntArray
    fun get__eg_d(): IntArray
    fun get__eg_n(): IntArray
    fun get__eg_v(): IntArray
    fun get__ef_bv(): Boolean
    fun get__ef_aw(): BooleanArray
    fun get__ef_az(): BooleanArray
    fun get__ef_ab(): IntArray
    fun get__ef_ad(): IntArray
    fun get__ef_ai(): IntArray
    fun get__ef_aj(): IntArray
    fun get__ef_an(): IntArray
    fun get__ef_av(): IntArray
    fun get__ef_bg(): IntArray
    fun get__ef_bi(): IntArray
    fun get__ef_bj(): IntArray
    fun get__ef_bm(): IntArray
    fun get__ef_bn(): IntArray
    fun get__ef_bp(): IntArray
    fun get__ef_bq(): IntArray
    fun get__ef_br(): IntArray
    fun get__ef_af(): Array<IntArray>
    fun get__ef_ao(): Array<IntArray>
    fun get__eb_e(): Int
    fun get__eb_q(): Int
    fun get__eb_y(): Int
    fun get__eh_e(): Int
    fun get__et_c(): Boolean
    fun get__et_n(): Boolean
    fun get__et_v(): Boolean
    fun get__et_o(): IntArray
    fun get__et_r(): IntArray
    fun get__ev_rb(): Int
    fun get__eq_aa(): Boolean
    fun get__eq_aq(): Boolean
    fun get__eq_az(): Int
    fun get__eq_k(): Int
    fun get__eq_ab(): IntArray
    fun get__eq_ad(): IntArray
    fun get__eq_af(): IntArray
    fun get__eq_ao(): IntArray
    fun get__eq_au(): IntArray
    fun get__eq_av(): IntArray
    fun get__eq_bj(): IntArray
    fun get__ey_ib(): Int
    fun get__el_v(): AbstractArchive
    fun get__ea_bt(): Array<IndexedSprite>
    fun get__eu_g(): Int
    fun get__ed_b(): IndexedSprite
    fun get__fs_l(): UrlRequest
    fun get__fc_el(): Int
    fun get__fk_fw(): AbstractSocket
    fun get__fz_ew(): Int
    fun get__fu_e(): Array<Array<ByteArray>>
    fun get__fu_a(): IntArray
    fun get__fp_i(): Int
    fun get__fp_rg(): Int
    fun get__fp_rv(): Int
    fun get__fp_y(): Any
    fun get__fj_n(): Boolean
    fun get__fj_v(): Any
    fun get__fj_d(): Any
    fun get__fm_rd(): Int
    fun get__gl_h(): Int
    fun get__gl_y(): Int
    fun get__gl_e(): IntArray
    fun get__gl_q(): IntArray
    fun get__gl_c(): Array<IntArray>
    fun get__gl_d(): Array<IntArray>
    fun get__gb_a(): ServerProt
    fun get__gb_aa(): ServerProt
    fun get__gb_ab(): ServerProt
    fun get__gb_ac(): ServerProt
    fun get__gb_ad(): ServerProt
    fun get__gb_ae(): ServerProt
    fun get__gb_af(): ServerProt
    fun get__gb_ag(): ServerProt
    fun get__gb_ah(): ServerProt
    fun get__gb_ai(): ServerProt
    fun get__gb_aj(): ServerProt
    fun get__gb_ak(): ServerProt
    fun get__gb_al(): ServerProt
    fun get__gb_am(): ServerProt
    fun get__gb_an(): ServerProt
    fun get__gb_ao(): ServerProt
    fun get__gb_ap(): ServerProt
    fun get__gb_aq(): ServerProt
    fun get__gb_ar(): ServerProt
    fun get__gb_as(): ServerProt
    fun get__gb_at(): ServerProt
    fun get__gb_au(): ServerProt
    fun get__gb_av(): ServerProt
    fun get__gb_aw(): ServerProt
    fun get__gb_ax(): ServerProt
    fun get__gb_ay(): ServerProt
    fun get__gb_az(): ServerProt
    fun get__gb_b(): ServerProt
    fun get__gb_ba(): ServerProt
    fun get__gb_bb(): ServerProt
    fun get__gb_bc(): ServerProt
    fun get__gb_bd(): ServerProt
    fun get__gb_be(): ServerProt
    fun get__gb_bf(): ServerProt
    fun get__gb_bg(): ServerProt
    fun get__gb_bh(): ServerProt
    fun get__gb_bi(): ServerProt
    fun get__gb_bj(): ServerProt
    fun get__gb_bk(): ServerProt
    fun get__gb_bl(): ServerProt
    fun get__gb_bm(): ServerProt
    fun get__gb_bn(): ServerProt
    fun get__gb_bo(): ServerProt
    fun get__gb_bp(): ServerProt
    fun get__gb_bq(): ServerProt
    fun get__gb_br(): ServerProt
    fun get__gb_bs(): ServerProt
    fun get__gb_bt(): ServerProt
    fun get__gb_bu(): ServerProt
    fun get__gb_bv(): ServerProt
    fun get__gb_bw(): ServerProt
    fun get__gb_bx(): ServerProt
    fun get__gb_by(): ServerProt
    fun get__gb_bz(): ServerProt
    fun get__gb_c(): ServerProt
    fun get__gb_cb(): ServerProt
    fun get__gb_cd(): ServerProt
    fun get__gb_cf(): ServerProt
    fun get__gb_ck(): ServerProt
    fun get__gb_cn(): ServerProt
    fun get__gb_cp(): ServerProt
    fun get__gb_cq(): ServerProt
    fun get__gb_cv(): ServerProt
    fun get__gb_d(): ServerProt
    fun get__gb_e(): ServerProt
    fun get__gb_f(): ServerProt
    fun get__gb_g(): ServerProt
    fun get__gb_h(): ServerProt
    fun get__gb_i(): ServerProt
    fun get__gb_j(): ServerProt
    fun get__gb_k(): ServerProt
    fun get__gb_l(): ServerProt
    fun get__gb_m(): ServerProt
    fun get__gb_n(): ServerProt
    fun get__gb_o(): ServerProt
    fun get__gb_p(): ServerProt
    fun get__gb_q(): ServerProt
    fun get__gb_r(): ServerProt
    fun get__gb_s(): ServerProt
    fun get__gb_t(): ServerProt
    fun get__gb_u(): ServerProt
    fun get__gb_v(): ServerProt
    fun get__gb_w(): ServerProt
    fun get__gb_x(): ServerProt
    fun get__gb_y(): ServerProt
    fun get__gb_z(): ServerProt
    fun get__gd_a(): ClientProt
    fun get__gd_aa(): ClientProt
    fun get__gd_ab(): ClientProt
    fun get__gd_ac(): ClientProt
    fun get__gd_ad(): ClientProt
    fun get__gd_ae(): ClientProt
    fun get__gd_af(): ClientProt
    fun get__gd_ag(): ClientProt
    fun get__gd_ah(): ClientProt
    fun get__gd_ai(): ClientProt
    fun get__gd_aj(): ClientProt
    fun get__gd_ak(): ClientProt
    fun get__gd_al(): ClientProt
    fun get__gd_am(): ClientProt
    fun get__gd_ao(): ClientProt
    fun get__gd_ap(): ClientProt
    fun get__gd_aq(): ClientProt
    fun get__gd_ar(): ClientProt
    fun get__gd_as(): ClientProt
    fun get__gd_at(): ClientProt
    fun get__gd_au(): ClientProt
    fun get__gd_av(): ClientProt
    fun get__gd_aw(): ClientProt
    fun get__gd_ax(): ClientProt
    fun get__gd_ay(): ClientProt
    fun get__gd_az(): ClientProt
    fun get__gd_b(): ClientProt
    fun get__gd_ba(): ClientProt
    fun get__gd_bb(): ClientProt
    fun get__gd_bc(): ClientProt
    fun get__gd_bd(): ClientProt
    fun get__gd_be(): ClientProt
    fun get__gd_bf(): ClientProt
    fun get__gd_bg(): ClientProt
    fun get__gd_bh(): ClientProt
    fun get__gd_bi(): ClientProt
    fun get__gd_bj(): ClientProt
    fun get__gd_bk(): ClientProt
    fun get__gd_bl(): ClientProt
    fun get__gd_bm(): ClientProt
    fun get__gd_bn(): ClientProt
    fun get__gd_bp(): ClientProt
    fun get__gd_bq(): ClientProt
    fun get__gd_br(): ClientProt
    fun get__gd_bs(): ClientProt
    fun get__gd_bt(): ClientProt
    fun get__gd_bu(): ClientProt
    fun get__gd_bv(): ClientProt
    fun get__gd_bw(): ClientProt
    fun get__gd_by(): ClientProt
    fun get__gd_bz(): ClientProt
    fun get__gd_c(): ClientProt
    fun get__gd_ca(): ClientProt
    fun get__gd_cc(): ClientProt
    fun get__gd_cd(): ClientProt
    fun get__gd_ce(): ClientProt
    fun get__gd_cf(): ClientProt
    fun get__gd_cg(): ClientProt
    fun get__gd_ch(): ClientProt
    fun get__gd_ci(): ClientProt
    fun get__gd_cj(): ClientProt
    fun get__gd_ck(): ClientProt
    fun get__gd_cl(): ClientProt
    fun get__gd_cm(): ClientProt
    fun get__gd_cn(): ClientProt
    fun get__gd_co(): ClientProt
    fun get__gd_cp(): ClientProt
    fun get__gd_cq(): ClientProt
    fun get__gd_cr(): ClientProt
    fun get__gd_cs(): ClientProt
    fun get__gd_cu(): ClientProt
    fun get__gd_cv(): ClientProt
    fun get__gd_cw(): ClientProt
    fun get__gd_cx(): ClientProt
    fun get__gd_cy(): ClientProt
    fun get__gd_cz(): ClientProt
    fun get__gd_d(): ClientProt
    fun get__gd_e(): ClientProt
    fun get__gd_f(): ClientProt
    fun get__gd_g(): ClientProt
    fun get__gd_h(): ClientProt
    fun get__gd_i(): ClientProt
    fun get__gd_j(): ClientProt
    fun get__gd_k(): ClientProt
    fun get__gd_l(): ClientProt
    fun get__gd_m(): ClientProt
    fun get__gd_o(): ClientProt
    fun get__gd_p(): ClientProt
    fun get__gd_q(): ClientProt
    fun get__gd_r(): ClientProt
    fun get__gd_s(): ClientProt
    fun get__gd_t(): ClientProt
    fun get__gd_u(): ClientProt
    fun get__gd_v(): ClientProt
    fun get__gd_w(): ClientProt
    fun get__gd_x(): ClientProt
    fun get__gd_y(): ClientProt
    fun get__gd_z(): ClientProt
    fun get__gd_an(): ClientProt
    fun get__gd_bo(): ClientProt
    fun get__gd_bx(): ClientProt
    fun get__gd_cb(): ClientProt
    fun get__gd_n(): ClientProt
    fun get__gv_c(): LoginProt
    fun get__gv_d(): LoginProt
    fun get__gv_n(): LoginProt
    fun get__gv_y(): LoginProt
    fun get__gv_h(): LoginProt
    fun get__gv_v(): LoginProt
    fun get__gv_e(): Array<LoginProt>
    fun get__gk_h(): Int
    fun get__gr_n(): IntArray
    fun get__gx_y(): Array<Array<ByteArray>>
    fun get__gw_cz(): Int
    fun get__ge_d(): AbstractArchive
    fun get__ge_h(): AbstractArchive
    fun get__ge_n(): AbstractArchive
    fun get__ge_v(): AbstractArchive
    fun get__ge_y(): Int
    fun get__gg_mf(): Int
    fun get__ho_l(): ByteArray
    fun get__he_s(): Int
    fun get__hf_l(): AbstractArchive
    fun get__hc_d(): Any
    fun get__hc_v(): Array<String>
    fun get__hc_n(): Array<Array<String>>
    fun get__hg_c(): Int
    fun get__hd_q(): IntArray
    fun get__hu_z(): ShortArray
    fun get__hu_s(): IntArray
    fun get__hn_d(): ShortArray
    fun get__hn_n(): ShortArray
    fun get__hn_c(): Array<ShortArray>
    fun get__hn_v(): Array<ShortArray>
    fun get__hv_z(): IntArray
    fun get__hv_e(): IntArray
    fun get__hz_x(): Boolean
    fun get__hz_a(): EvictingDualNodeHashTable
    fun get__hz_i(): EvictingDualNodeHashTable
    fun get__hz_b(): AbstractArchive
    fun get__hx_ri(): Int
    fun get__hi_ab(): String
    fun get__hi_ad(): String
    fun get__hi_af(): String
    fun get__hi_ah(): String
    fun get__hi_ai(): String
    fun get__hi_aj(): String
    fun get__hi_an(): String
    fun get__hi_ao(): String
    fun get__hi_ap(): String
    fun get__hi_as(): String
    fun get__hi_au(): String
    fun get__hi_av(): String
    fun get__hi_aw(): String
    fun get__hi_az(): String
    fun get__hi_ba(): String
    fun get__hi_bb(): String
    fun get__hi_bc(): String
    fun get__hi_bd(): String
    fun get__hi_be(): String
    fun get__hi_bf(): String
    fun get__hi_bg(): String
    fun get__hi_bh(): String
    fun get__hi_bi(): String
    fun get__hi_bj(): String
    fun get__hi_bk(): String
    fun get__hi_bl(): String
    fun get__hi_bm(): String
    fun get__hi_bn(): String
    fun get__hi_bo(): String
    fun get__hi_bp(): String
    fun get__hi_bq(): String
    fun get__hi_br(): String
    fun get__hi_bs(): String
    fun get__hi_bt(): String
    fun get__hi_bu(): String
    fun get__hi_bv(): String
    fun get__hi_bw(): String
    fun get__hi_bx(): String
    fun get__hi_by(): String
    fun get__hi_bz(): String
    fun get__hi_ca(): String
    fun get__hi_cb(): String
    fun get__hi_cc(): String
    fun get__hi_cd(): String
    fun get__hi_ce(): String
    fun get__hi_cf(): String
    fun get__hi_cg(): String
    fun get__hi_ch(): String
    fun get__hi_ci(): String
    fun get__hi_cj(): String
    fun get__hi_ck(): String
    fun get__hi_cl(): String
    fun get__hi_cm(): String
    fun get__hi_cn(): String
    fun get__hi_co(): String
    fun get__hi_cp(): String
    fun get__hi_cq(): String
    fun get__hi_cr(): String
    fun get__hi_cs(): String
    fun get__hi_ct(): String
    fun get__hi_cu(): String
    fun get__hi_cv(): String
    fun get__hi_cw(): String
    fun get__hi_cx(): String
    fun get__hi_cy(): String
    fun get__hi_cz(): String
    fun get__hi_da(): String
    fun get__hi_db(): String
    fun get__hi_dc(): String
    fun get__hi_dd(): String
    fun get__hi_de(): String
    fun get__hi_df(): String
    fun get__hi_dg(): String
    fun get__hi_dh(): String
    fun get__hi_di(): String
    fun get__hi_dj(): String
    fun get__hi_dk(): String
    fun get__hi_dl(): String
    fun get__hi_dm(): String
    fun get__hi_dn(): String
    fun get__hi_do(): String
    fun get__hi_dp(): String
    fun get__hi_dr(): String
    fun get__hi_ds(): String
    fun get__hi_dt(): String
    fun get__hi_du(): String
    fun get__hi_dv(): String
    fun get__hi_dx(): String
    fun get__hi_dy(): String
    fun get__hi_dz(): String
    fun get__hi_e(): String
    fun get__hi_ea(): String
    fun get__hi_eb(): String
    fun get__hi_ec(): String
    fun get__hi_ee(): String
    fun get__hi_ef(): String
    fun get__hi_eg(): String
    fun get__hi_eh(): String
    fun get__hi_ek(): String
    fun get__hi_el(): String
    fun get__hi_em(): String
    fun get__hi_en(): String
    fun get__hi_eo(): String
    fun get__hi_ep(): String
    fun get__hi_eq(): String
    fun get__hi_er(): String
    fun get__hi_es(): String
    fun get__hi_et(): String
    fun get__hi_eu(): String
    fun get__hi_ev(): String
    fun get__hi_ew(): String
    fun get__hi_ey(): String
    fun get__hi_fe(): String
    fun get__hi_fg(): String
    fun get__hi_fk(): String
    fun get__hi_fl(): String
    fun get__hi_fr(): String
    fun get__hi_fu(): String
    fun get__hi_fv(): String
    fun get__hi_fw(): String
    fun get__hi_fy(): String
    fun get__hi_fz(): String
    fun get__hi_ga(): String
    fun get__hi_gb(): String
    fun get__hi_gc(): String
    fun get__hi_gd(): String
    fun get__hi_ge(): String
    fun get__hi_gf(): String
    fun get__hi_gg(): String
    fun get__hi_gh(): String
    fun get__hi_gi(): String
    fun get__hi_gj(): String
    fun get__hi_gk(): String
    fun get__hi_gl(): String
    fun get__hi_gm(): String
    fun get__hi_gn(): String
    fun get__hi_go(): String
    fun get__hi_gp(): String
    fun get__hi_gq(): String
    fun get__hi_gr(): String
    fun get__hi_gs(): String
    fun get__hi_gt(): String
    fun get__hi_gu(): String
    fun get__hi_gv(): String
    fun get__hi_gw(): String
    fun get__hi_gx(): String
    fun get__hi_gy(): String
    fun get__hi_gz(): String
    fun get__hi_ha(): String
    fun get__hi_hb(): String
    fun get__hi_hc(): String
    fun get__hi_he(): String
    fun get__hi_hf(): String
    fun get__hi_hg(): String
    fun get__hi_hi(): String
    fun get__hi_hk(): String
    fun get__hi_hl(): String
    fun get__hi_ho(): String
    fun get__hi_hq(): String
    fun get__hi_hr(): String
    fun get__hi_hs(): String
    fun get__hi_hy(): String
    fun get__hi_ia(): String
    fun get__hi_ib(): String
    fun get__hi_ic(): String
    fun get__hi_id(): String
    fun get__hi_ih(): String
    fun get__hi_ij(): String
    fun get__hi_il(): String
    fun get__hi_im(): String
    fun get__hi_in(): String
    fun get__hi_io(): String
    fun get__hi_ir(): String
    fun get__hi_is(): String
    fun get__hi_it(): String
    fun get__hi_iu(): String
    fun get__hi_iv(): String
    fun get__hi_iw(): String
    fun get__hi_ix(): String
    fun get__hi_iz(): String
    fun get__hi_ja(): String
    fun get__hi_jb(): String
    fun get__hi_jc(): String
    fun get__hi_jd(): String
    fun get__hi_je(): String
    fun get__hi_jf(): String
    fun get__hi_jg(): String
    fun get__hi_jh(): String
    fun get__hi_ji(): String
    fun get__hi_jj(): String
    fun get__hi_jk(): String
    fun get__hi_jl(): String
    fun get__hi_jm(): String
    fun get__hi_jn(): String
    fun get__hi_jo(): String
    fun get__hi_jp(): String
    fun get__hi_jq(): String
    fun get__hi_jr(): String
    fun get__hi_js(): String
    fun get__hi_jt(): String
    fun get__hi_ju(): String
    fun get__hi_jv(): String
    fun get__hi_jw(): String
    fun get__hi_jx(): String
    fun get__hi_jy(): String
    fun get__hi_jz(): String
    fun get__hi_ka(): String
    fun get__hi_kb(): String
    fun get__hi_ke(): String
    fun get__hi_kf(): String
    fun get__hi_kg(): String
    fun get__hi_kj(): String
    fun get__hi_kk(): String
    fun get__hi_km(): String
    fun get__hi_ko(): String
    fun get__hi_kp(): String
    fun get__hi_kq(): String
    fun get__hi_kr(): String
    fun get__hi_kt(): String
    fun get__hi_ku(): String
    fun get__hi_kw(): String
    fun get__hi_ky(): String
    fun get__hi_l(): String
    fun get__hi_s(): String
    fun get__hi_aa(): String
    fun get__id_gy(): Sprite
    fun get__id_fv(): Long
    fun get__iv_a(): Boolean
    fun get__iv_z(): PlayerType
    fun get__iu_c(): ServerBuild
    fun get__iu_d(): ServerBuild
    fun get__iu_n(): ServerBuild
    fun get__iu_v(): ServerBuild
    fun get__im_h(): StudioGame
    fun get__im_c(): StudioGame
    fun get__im_d(): StudioGame
    fun get__im_n(): StudioGame
    fun get__im_v(): StudioGame
    fun get__im_y(): StudioGame
    fun get__ig_f(): Int
    fun get__if_d(): Int
    fun get__ii_p(): Byte
    fun get__ii_v(): Int
    fun get__ii_x(): Int
    fun get__ii_d(): Long
    fun get__ij_v(): EvictingDualNodeHashTable
    fun get__ij_n(): AbstractArchive
    fun get__il_n(): AbstractArchive
    fun get__il_d(): EvictingDualNodeHashTable
    fun get__ic_n(): AbstractArchive
    fun get__ia_v(): EvictingDualNodeHashTable
    fun get__ia_n(): AbstractArchive
    fun get__iw_v(): EvictingDualNodeHashTable
    fun get__iw_n(): AbstractArchive
    fun get__it_d(): Int
    fun get__it_v(): AbstractArchive
    fun get__ix_n(): AbstractArchive
    fun get__ix_v(): AbstractArchive
    fun get__jl_n(): AbstractArchive
    fun get__jp_v(): EvictingDualNodeHashTable
    fun get__jp_n(): AbstractArchive
    fun get__jz_y(): EvictingDualNodeHashTable
    fun get__jz_d(): AbstractArchive
    fun get__jz_n(): AbstractArchive
    fun get__jg_h(): EvictingDualNodeHashTable
    fun get__jg_e(): Array<UnlitModel>
    fun get__jj_a(): Font
    fun get__jj_es(): Archive
    fun get__je_e(): IntArray
    fun get__je_jf(): Component
    fun get__jo_v(): EvictingDualNodeHashTable
    fun get__jo_n(): AbstractArchive
    fun get__js_y(): EvictingDualNodeHashTable
    fun get__js_d(): AbstractArchive
    fun get__js_v(): AbstractArchive
    fun get__jm_i(): Component
    fun get__jr_f(): Array<String>
    fun get__ka_z(): IntArray
    fun get__kf_v(): Array<Long>
    fun get__kr_d(): Array<Char>
    fun get__kr_n(): Array<Char>
    fun get__kr_v(): Array<Char>
    fun get__kr_c(): IntArray
    fun get__kx_e(): IntArray
    fun get__kx_l(): Array<Long>
    fun get__lk_q(): Array<Array<ByteArray>>
    fun get__lx_o(): IntArray
    fun get__li_e(): Boolean
    fun get__lp_n(): RectangleMode
    fun get__lp_d(): RectangleMode
    fun get__lp_v(): RectangleMode
    fun get__lz_h(): IntArray
    fun get__lz_y(): IntArray
    fun get__lz_d(): Int
    fun get__lz_n(): Int
    fun get__lz_v(): Int
    fun get__mk_l(): IntArray
    fun get__mk_s(): IntArray
    fun get__ml_n(): LoginType
    fun get__ml_q(): LoginType
    fun get__ml_c(): LoginType
    fun get__ml_d(): LoginType
    fun get__ml_e(): LoginType
    fun get__ml_h(): LoginType
    fun get__ml_v(): LoginType
    fun get__ml_y(): LoginType
    fun get__ml_z(): LoginType
    fun get__mp_c(): Array<Char>
    fun get__mp_d(): Array<Char>
    fun get__mc_bt(): String
}
