package com.p3achb0t.api.interfaces

interface ObjType : DualNode {
    fun getAmbient(): Int
    fun getBoughtlink(): Int
    fun getBoughttemplate(): Int
    fun getCertlink(): Int
    fun getCerttemplate(): Int
    fun getContrast(): Int
    fun getCost(): Int
    fun getCountco(): IntArray
    fun getCountobj(): IntArray
    fun getId(): Int
    fun getIop(): Array<String>
    fun getManhead(): Int
    fun getManhead2(): Int
    fun getManwear(): Int
    fun getManwear2(): Int
    fun getManwear3(): Int
    fun getManwearyoff(): Int
    fun getMembers(): Boolean
    fun getModel(): Int
    fun getName(): String
    fun getOp(): Array<String>
    fun getParams(): IterableNodeHashTable
    fun getPlaceholderlink(): Int
    fun getPlaceholdertemplate(): Int
    fun getRecol_d(): ShortArray
    fun getRecol_s(): ShortArray
    fun getResizex(): Int
    fun getResizey(): Int
    fun getResizez(): Int
    fun getRetex_d(): ShortArray
    fun getRetex_s(): ShortArray
    fun getShiftclickindex(): Int
    fun getStackable(): Int
    fun getStockmarket(): Boolean
    fun getTeam(): Int
    fun getWomanhead(): Int
    fun getWomanhead2(): Int
    fun getWomanwear(): Int
    fun getWomanwear2(): Int
    fun getWomanwear3(): Int
    fun getWomanwearyoff(): Int
    fun getXan2d(): Int
    fun getXof2d(): Int
    fun getYan2d(): Int
    fun getYof2d(): Int
    fun getZan2d(): Int
    fun getZoom2d(): Int
}
