package com.p3achb0t.api.interfaces

interface WorldMap {
    fun getCacheLoader(): WorldMapArchiveLoader
    fun getCurrentMapArea0(): WorldMapArea
    fun getElementsDisabled(): Boolean
    fun getEnabledCategories(): Any
    fun getEnabledElements(): Any
    fun getFlashingElements(): Any
    fun getFont(): Font
    fun getFonts(): Any
    fun getIconIterator(): Any
    fun getMainMapArea(): WorldMapArea
    fun getMapAreas(): Any
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMouseCoord(): Coord
    fun getPerpetualFlash0(): Boolean
    fun getSprite(): Sprite
    fun getWorldMapManager(): WorldMapManager
    fun getZoom(): Float
    fun getZoomTarget(): Float
    fun get__ac(): Boolean
    fun get__u(): WorldMapArea
    fun get__aa(): Int
    fun get__ad(): Int
    fun get__ae(): Int
    fun get__ai(): Int
    fun get__aj(): Int
    fun get__ak(): Int
    fun get__am(): Int
    fun get__ao(): Int
    fun get__as(): Int
    fun get__at(): Int
    fun get__av(): Int
    fun get__aw(): Int
    fun get__ax(): Int
    fun get__ay(): Int
    fun get__ba(): Int
    fun get__bd(): Int
    fun get__bm(): Int
    fun get__bn(): Int
    fun get__br(): Int
    fun get__f(): Int
    fun get__s(): Int
    fun get__w(): Int
    fun get__y(): Int
    fun get__af(): Any
    fun get__ah(): Any
    fun get__bk(): Any
    fun get__bu(): Any
    fun get__b(): AbstractArchive
    fun get__t(): AbstractArchive
    fun get__v(): AbstractArchive
    fun get__au(): Long
    fun get__bf(): IntArray
    fun get__by(): Boolean
}
