package com.p3achb0t.api.interfaces

interface WorldMap {
    fun getCacheLoader(): WorldMapArchiveLoader
    fun getCurrentMapArea0(): WorldMapArea
    fun getElementsDisabled(): Boolean
    fun getEnabledCategories(): Any
    fun getEnabledElements(): Any
    fun getFlashingElements(): Any
    fun getFont(): Font
    fun getFonts(): Any
    fun getIconIterator(): Any
    fun getMainMapArea(): WorldMapArea
    fun getMapAreas(): Any
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMouseCoord(): Coord
    fun getPerpetualFlash0(): Boolean
    fun getSprite(): Sprite
    fun getWorldMapManager(): WorldMapManager
    fun getZoom(): Float
    fun getZoomTarget(): Float
    fun get__ab(): Boolean
    fun get__v(): WorldMapArea
    fun get__a(): Int
    fun get__ad(): Int
    fun get__af(): Int
    fun get__ag(): Int
    fun get__ai(): Int
    fun get__aj(): Int
    fun get__am(): Int
    fun get__ao(): Int
    fun get__aq(): Int
    fun get__as(): Int
    fun get__at(): Int
    fun get__au(): Int
    fun get__ax(): Int
    fun get__ay(): Int
    fun get__az(): Int
    fun get__bh(): Int
    fun get__bj(): Int
    fun get__bo(): Int
    fun get__bp(): Int
    fun get__bw(): Int
    fun get__i(): Int
    fun get__s(): Int
    fun get__w(): Int
    fun get__g(): AbstractArchive
    fun get__h(): AbstractArchive
    fun get__k(): AbstractArchive
    fun get__ah(): Any
    fun get__an(): Any
    fun get__bk(): Any
    fun get__bi(): Any
    fun get__av(): Long
    fun get__bn(): IntArray
    fun get__ba(): Boolean
}
