package com.p3achb0t.api.interfaces

interface WorldMap {
    fun getCacheLoader(): WorldMapArchiveLoader
    fun getCurrentMapArea0(): WorldMapArea
    fun getElementsDisabled(): Boolean
    fun getEnabledCategories(): Any
    fun getEnabledElements(): Any
    fun getFlashingElements(): Any
    fun getFont(): Font
    fun getFonts(): Any
    fun getIconIterator(): Any
    fun getMainMapArea(): WorldMapArea
    fun getMapAreas(): Any
    fun getMapSceneSprites(): Array<IndexedSprite>
    fun getMouseCoord(): Coord
    fun getPerpetualFlash0(): Boolean
    fun getSprite(): Sprite
    fun getWorldMapManager(): WorldMapManager
    fun getZoom(): Float
    fun getZoomTarget(): Float
    fun get__d(): WorldMapArea
    fun get__at(): Boolean
    fun get__a(): AbstractArchive
    fun get__n(): AbstractArchive
    fun get__u(): AbstractArchive
    fun get__ab(): Int
    fun get__ad(): Int
    fun get__ae(): Int
    fun get__af(): Int
    fun get__ag(): Int
    fun get__ai(): Int
    fun get__al(): Int
    fun get__an(): Int
    fun get__ao(): Int
    fun get__ap(): Int
    fun get__ar(): Int
    fun get__as(): Int
    fun get__av(): Int
    fun get__ax(): Int
    fun get__b(): Int
    fun get__bc(): Int
    fun get__bk(): Int
    fun get__bn(): Int
    fun get__bo(): Int
    fun get__bq(): Int
    fun get__i(): Int
    fun get__t(): Int
    fun get__x(): Int
    fun get__au(): Any
    fun get__ay(): Any
    fun get__ba(): Any
    fun get__be(): Any
    fun get__ac(): Long
    fun get__bg(): IntArray
    fun get__bb(): Boolean
}
