package com.p3achb0t.scripts.paint.debug

import com.p3achb0t.api.Context
import com.p3achb0t.api.LoginResponse
import com.p3achb0t.api.wrappers.utils.Calculations
import java.awt.Color
import java.awt.Font
import java.awt.Graphics



fun drawClientDebugText(g: Graphics, ctx: Context) {

    val debugText = arrayListOf<DebugText>()
    if (true) {

        g.color = Color.white
//        debugText.add(DebugText("get__t_n       : ${ctx.client.get__t_n()}"))
//        debugText.add(DebugText("get__w_if      : ${ctx.client.get__w_if()}"))
//        debugText.add(DebugText("get__g_rf      : ${ctx.client.get__g_rf()}"))
//        debugText.add(DebugText("get__q_im      : ${ctx.client.get__q_im()}"))
//        debugText.add(DebugText("get__v_be      : ${ctx.client.get__v_be()}"))
//        debugText.add(DebugText("get__r_aj      : ${ctx.client.get__r_aj()}"))
//        debugText.add(DebugText("get__ag_gl     : ${ctx.client.get__ag_gl()}"))
//        debugText.add(DebugText("get__ae_g      : ${ctx.client.get__ae_g()}"))
//        debugText.add(DebugText("get__ap_ew     : ${ctx.client.get__ap_ew()}"))
//        debugText.add(DebugText("get__av_i      : ${ctx.client.get__av_i()}"))
//        debugText.add(DebugText("get__aj_ey     : ${ctx.client.get__aj_ey()}"))
//        debugText.add(DebugText("get__bl_gk     : ${ctx.client.get__bl_gk()}"))
//        debugText.add(DebugText("get__bz_cf     : ${ctx.client.get__bz_cf()}"))
//        debugText.add(DebugText("get__bz_ch     : ${ctx.client.get__bz_ch()}"))
//        debugText.add(DebugText("get__bz_cj     : ${ctx.client.get__bz_cj()}"))
//        debugText.add(DebugText("get__bz_ck     : ${ctx.client.get__bz_ck()}"))
//        debugText.add(DebugText("get__bz_co     : ${ctx.client.get__bz_co()}"))
//        debugText.add(DebugText("get__bz_cs     : ${ctx.client.get__bz_cs()}"))
//        debugText.add(DebugText("get__bg_g      : ${ctx.client.get__bg_g()}"))
//        debugText.add(DebugText("get__bp_ef     : ${ctx.client.get__bp_ef()}"))
//        debugText.add(DebugText("get__bw_m      : ${ctx.client.get__bw_m()}"))
//        debugText.add(DebugText("get__bw_n      : ${ctx.client.get__bw_n()}"))
//        debugText.add(DebugText("get__bw_s      : ${ctx.client.get__bw_s()}"))
//        debugText.add(DebugText("get__be_ij     : ${ctx.client.get__be_ij()}"))
//        debugText.add(DebugText("get__bu_g      : ${ctx.client.get__bu_g()}"))
//        debugText.add(DebugText("get__bu_e      : ${ctx.client.get__bu_e()}"))
//        debugText.add(DebugText("get__bu_l      : ${ctx.client.get__bu_l()}"))
//        debugText.add(DebugText("get__by_gy     : ${ctx.client.get__by_gy()}"))
//        debugText.add(DebugText("get__by_sz     : ${ctx.client.get__by_sz()}"))
//        debugText.add(DebugText("get__bo_rc     : ${ctx.client.get__bo_rc()}"))
//        debugText.add(DebugText("get__client_sr : ${ctx.client.get__client_sr()}"))
//        debugText.add(DebugText("get__client_cf : ${ctx.client.get__client_cf()}"))
//        debugText.add(DebugText("get__client_cj : ${ctx.client.get__client_cj()}"))
//        debugText.add(DebugText("get__client_da : ${ctx.client.get__client_da()}"))
//        debugText.add(DebugText("get__client_de : ${ctx.client.get__client_de()}"))
//        debugText.add(DebugText("get__client_eg : ${ctx.client.get__client_eg()}"))
//        debugText.add(DebugText("get__client_em : ${ctx.client.get__client_em()}"))
//        debugText.add(DebugText("get__client_eq : ${ctx.client.get__client_eq()}"))
//        debugText.add(DebugText("get__client_ff : ${ctx.client.get__client_ff()}"))
//        debugText.add(DebugText("get__client_fk : ${ctx.client.get__client_fk()}"))
//        debugText.add(DebugText("get__client_gj : ${ctx.client.get__client_gj()}"))
//        debugText.add(DebugText("get__client_gm : ${ctx.client.get__client_gm()}"))
//        debugText.add(DebugText("get__client_gr : ${ctx.client.get__client_gr()}"))
//        debugText.add(DebugText("get__client_gu : ${ctx.client.get__client_gu()}"))
//        debugText.add(DebugText("get__client_gv : ${ctx.client.get__client_gv()}"))
//        debugText.add(DebugText("get__client_gw : ${ctx.client.get__client_gw()}"))
//        debugText.add(DebugText("get__client_hd : ${ctx.client.get__client_hd()}"))
//        debugText.add(DebugText("get__client_hh : ${ctx.client.get__client_hh()}"))
//        debugText.add(DebugText("get__client_hi : ${ctx.client.get__client_hi()}"))
//        debugText.add(DebugText("get__client_hk : ${ctx.client.get__client_hk()}"))
//        debugText.add(DebugText("get__client_hl : ${ctx.client.get__client_hl()}"))
//        debugText.add(DebugText("get__client_hm : ${ctx.client.get__client_hm()}"))
//        debugText.add(DebugText("get__client_ho : ${ctx.client.get__client_ho()}"))
//        debugText.add(DebugText("get__client_hp : ${ctx.client.get__client_hp()}"))
//        debugText.add(DebugText("get__client_hw : ${ctx.client.get__client_hw()}"))
//        debugText.add(DebugText("get__client_hy : ${ctx.client.get__client_hy()}"))
//        debugText.add(DebugText("get__client_ig : ${ctx.client.get__client_ig()}"))
//        debugText.add(DebugText("get__client_ii : ${ctx.client.get__client_ii()}"))
//        debugText.add(DebugText("get__client_io : ${ctx.client.get__client_io()}"))
//        debugText.add(DebugText("get__client_ip : ${ctx.client.get__client_ip()}"))
//        debugText.add(DebugText("get__client_iq : ${ctx.client.get__client_iq()}"))
//        debugText.add(DebugText("get__client_is : ${ctx.client.get__client_is()}"))
//        debugText.add(DebugText("get__client_iv : ${ctx.client.get__client_iv()}"))
//        debugText.add(DebugText("get__client_iw : ${ctx.client.get__client_iw()}"))
//        debugText.add(DebugText("get__client_ja : ${ctx.client.get__client_ja()}"))
//        debugText.add(DebugText("get__client_jb : ${ctx.client.get__client_jb()}"))
//        debugText.add(DebugText("get__client_je : ${ctx.client.get__client_je()}"))
//        debugText.add(DebugText("get__client_jf : ${ctx.client.get__client_jf()}"))
//        debugText.add(DebugText("get__client_jr : ${ctx.client.get__client_jr()}"))
//        debugText.add(DebugText("get__client_kh : ${ctx.client.get__client_kh()}"))
//        debugText.add(DebugText("get__client_kp : ${ctx.client.get__client_kp()}"))
//        debugText.add(DebugText("get__client_kt : ${ctx.client.get__client_kt()}"))
//        debugText.add(DebugText("get__client_lh : ${ctx.client.get__client_lh()}"))
//        debugText.add(DebugText("get__client_li : ${ctx.client.get__client_li()}"))
//        debugText.add(DebugText("get__client_lm : ${ctx.client.get__client_lm()}"))
//        debugText.add(DebugText("get__client_ls : ${ctx.client.get__client_ls()}"))
//        debugText.add(DebugText("get__client_ma : ${ctx.client.get__client_ma()}"))
//        debugText.add(DebugText("get__client_mc : ${ctx.client.get__client_mc()}"))
//        debugText.add(DebugText("get__client_mf : ${ctx.client.get__client_mf()}"))
//        debugText.add(DebugText("get__client_ms : ${ctx.client.get__client_ms()}"))
//        debugText.add(DebugText("get__client_mv : ${ctx.client.get__client_mv()}"))
//        debugText.add(DebugText("get__client_mw : ${ctx.client.get__client_mw()}"))
//        debugText.add(DebugText("get__client_nb : ${ctx.client.get__client_nb()}"))
//        debugText.add(DebugText("get__client_nd : ${ctx.client.get__client_nd()}"))
//        debugText.add(DebugText("get__client_ne : ${ctx.client.get__client_ne()}"))
//        debugText.add(DebugText("get__client_ng : ${ctx.client.get__client_ng()}"))
//        debugText.add(DebugText("get__client_ni : ${ctx.client.get__client_ni()}"))
//        debugText.add(DebugText("get__client_nr : ${ctx.client.get__client_nr()}"))
//        debugText.add(DebugText("get__client_nt : ${ctx.client.get__client_nt()}"))
//        debugText.add(DebugText("get__client_nu : ${ctx.client.get__client_nu()}"))
//        debugText.add(DebugText("get__client_nz : ${ctx.client.get__client_nz()}"))
//        debugText.add(DebugText("get__client_od : ${ctx.client.get__client_od()}"))
//        debugText.add(DebugText("get__client_oe : ${ctx.client.get__client_oe()}"))
//        debugText.add(DebugText("get__client_oi : ${ctx.client.get__client_oi()}"))
//        debugText.add(DebugText("get__client_oj : ${ctx.client.get__client_oj()}"))
//        debugText.add(DebugText("get__client_on : ${ctx.client.get__client_on()}"))
//        debugText.add(DebugText("get__client_oq : ${ctx.client.get__client_oq()}"))
//        debugText.add(DebugText("get__client_ox : ${ctx.client.get__client_ox()}"))
//        debugText.add(DebugText("get__client_pd : ${ctx.client.get__client_pd()}"))
//        debugText.add(DebugText("get__client_ps : ${ctx.client.get__client_ps()}"))
//        debugText.add(DebugText("get__client_pt : ${ctx.client.get__client_pt()}"))
//        debugText.add(DebugText("get__client_py : ${ctx.client.get__client_py()}"))
//        debugText.add(DebugText("get__client_qa : ${ctx.client.get__client_qa()}"))
//        debugText.add(DebugText("get__client_qf : ${ctx.client.get__client_qf()}"))
//        debugText.add(DebugText("get__client_qu : ${ctx.client.get__client_qu()}"))
//        debugText.add(DebugText("get__client_qv : ${ctx.client.get__client_qv()}"))
//        debugText.add(DebugText("get__client_si : ${ctx.client.get__client_si()}"))
//        debugText.add(DebugText("get__client_ss : ${ctx.client.get__client_ss()}"))
//        debugText.add(DebugText("get__client_su : ${ctx.client.get__client_su()}"))
//        debugText.add(DebugText("get__ca_rb     : ${ctx.client.get__ca_rb()}"))
//        debugText.add(DebugText("get__ct_x      : ${ctx.client.get__ct_x()}"))
//        debugText.add(DebugText("get__cv_ac     : ${ctx.client.get__cv_ac()}"))
//        debugText.add(DebugText("get__cv_et     : ${ctx.client.get__cv_et()}"))
//        debugText.add(DebugText("get__ce_z      : ${ctx.client.get__ce_z()}"))
//        debugText.add(DebugText("get__ci_j      : ${ctx.client.get__ci_j()}"))
//        debugText.add(DebugText("get__cx_ae     : ${ctx.client.get__cx_ae()}"))
//        debugText.add(DebugText("get__cx_ap     : ${ctx.client.get__cx_ap()}"))
//        debugText.add(DebugText("get__cx_at     : ${ctx.client.get__cx_at()}"))
//        debugText.add(DebugText("get__cx_bb     : ${ctx.client.get__cx_bb()}"))
//        debugText.add(DebugText("get__cx_bd     : ${ctx.client.get__cx_bd()}"))
//        debugText.add(DebugText("get__cx_bm     : ${ctx.client.get__cx_bm()}"))
//        debugText.add(DebugText("get__cx_bz     : ${ctx.client.get__cx_bz()}"))
//        debugText.add(DebugText("get__cx_j      : ${ctx.client.get__cx_j()}"))
//        debugText.add(DebugText("get__cx_s      : ${ctx.client.get__cx_s()}"))
//        debugText.add(DebugText("get__ck_h      : ${ctx.client.get__ck_h()}"))
//        debugText.add(DebugText("get__ck_w      : ${ctx.client.get__ck_w()}"))
//        debugText.add(DebugText("get__dv_aw     : ${ctx.client.get__dv_aw()}"))
//        debugText.add(DebugText("get__dy_c      : ${ctx.client.get__dy_c()}"))
//        debugText.add(DebugText("get__ds_rp     : ${ctx.client.get__ds_rp()}"))
//        debugText.add(DebugText("get__du_g      : ${ctx.client.get__du_g()}"))
//        debugText.add(DebugText("get__dt_ri     : ${ctx.client.get__dt_ri()}"))
//        debugText.add(DebugText("get__ee_aq     : ${ctx.client.get__ee_aq()}"))
//        debugText.add(DebugText("get__eu_re     : ${ctx.client.get__eu_re()}"))
//        debugText.add(DebugText("get__ep_h      : ${ctx.client.get__ep_h()}"))
//        debugText.add(DebugText("get__ep_i      : ${ctx.client.get__ep_i()}"))
//        debugText.add(DebugText("get__ep_m      : ${ctx.client.get__ep_m()}"))
//        debugText.add(DebugText("get__ep_x      : ${ctx.client.get__ep_x()}"))
//        debugText.add(DebugText("get__ec_av     : ${ctx.client.get__ec_av()}"))
//        debugText.add(DebugText("get__ec_q      : ${ctx.client.get__ec_q()}"))
//        debugText.add(DebugText("get__eb_c      : ${ctx.client.get__eb_c()}"))
//        debugText.add(DebugText("get__et_m      : ${ctx.client.get__et_m()}"))
//        debugText.add(DebugText("get__fv_rn     : ${ctx.client.get__fv_rn()}"))
//        debugText.add(DebugText("get__fw_rt     : ${ctx.client.get__fw_rt()}"))
//        debugText.add(DebugText("get__gx_i      : ${ctx.client.get__gx_i()}"))
//        debugText.add(DebugText("get__gx_o      : ${ctx.client.get__gx_o()}"))
//        debugText.add(DebugText("get__gb_o      : ${ctx.client.get__gb_o()}"))
//        debugText.add(DebugText("get__gg_sm     : ${ctx.client.get__gg_sm()}"))
//        debugText.add(DebugText("get__gi_i      : ${ctx.client.get__gi_i()}"))
//        debugText.add(DebugText("get__hp_o      : ${ctx.client.get__hp_o()}"))
//        debugText.add(DebugText("get__ho_ns     : ${ctx.client.get__ho_ns()}"))
//        debugText.add(DebugText("get__hz_w      : ${ctx.client.get__hz_w()}"))
//        debugText.add(DebugText("get__ha_cq     : ${ctx.client.get__ha_cq()}"))
//        debugText.add(DebugText("get__hu_rs     : ${ctx.client.get__hu_rs()}"))
//        debugText.add(DebugText("get__hs_g      : ${ctx.client.get__hs_g()}"))
//        debugText.add(DebugText("get__hw_mx     : ${ctx.client.get__hw_mx()}"))
//        debugText.add(DebugText("get__ia_d      : ${ctx.client.get__ia_d()}"))
//        debugText.add(DebugText("get__ic_y      : ${ctx.client.get__ic_y()}"))
//        debugText.add(DebugText("get__ip_s      : ${ctx.client.get__ip_s()}"))
//        debugText.add(DebugText("get__ii_f      : ${ctx.client.get__ii_f()}"))
//        debugText.add(DebugText("get__ii_k      : ${ctx.client.get__ii_k()}"))
//        debugText.add(DebugText("get__ik_k      : ${ctx.client.get__ik_k()}"))
//        debugText.add(DebugText("get__ih_gs     : ${ctx.client.get__ih_gs()}"))
//        debugText.add(DebugText("get__ie_s      : ${ctx.client.get__ie_s()}"))
//        debugText.add(DebugText("get__js_rj     : ${ctx.client.get__js_rj()}"))
//        debugText.add(DebugText("get__kz_v      : ${ctx.client.get__kz_v()}"))
//        debugText.add(DebugText("get__lj_k      : ${ctx.client.get__lj_k()}"))
//        debugText.add(DebugText("get__lj_s      : ${ctx.client.get__lj_s()}"))
//        debugText.add(DebugText("get__lj_z      : ${ctx.client.get__lj_z()}"))
//        debugText.add(DebugText("get__lh_r      : ${ctx.client.get__lh_r()}"))
        debugText.add(DebugText("getStrings_login: ${ctx.client.getStrings_login()}"))
        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response0()}"))
        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response1()}"))
        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response2()}"))
        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response3()}"))
        debugText.add(DebugText("getLogin_loadingText: ${ctx.client.getLogin_loadingText()}"))
        debugText.add(DebugText("getStrings_login: ${ctx.client.getStrings_login()}"))
        debugText.add(DebugText("login response: ${ctx.client.get__cx_at()}"))
        debugText.add(DebugText("getLoginState: ${ctx.client.getLoginState()}"))
        debugText.add(DebugText("getLoginType().get__m(: ${ctx.client.getLoginType().get__m()}"))
        debugText.add(DebugText("getLoginType().get__n(: ${ctx.client.getLoginType().get__n()}"))
        debugText.add(DebugText("get__ab_bl     : ${ctx.client.get__ab_bl()}"))
        debugText.add(DebugText("get__bp_ah     : ${ctx.client.get__bp_ah()}"))
        debugText.add(DebugText("get__bp_k      : ${ctx.client.get__bp_k()}"))
        debugText.add(DebugText("get__bx_y      : ${ctx.client.get__bx_y()}"))
        debugText.add(DebugText("get__client_pm : ${ctx.client.get__client_pm()}"))
        debugText.add(DebugText("get__ci_c      : ${ctx.client.get__ci_c()}"))
        debugText.add(DebugText("get__cx_bh     : ${ctx.client.get__cx_bh()}"))
        debugText.add(DebugText("get__cx_bj     : ${ctx.client.get__cx_bj()}"))
        debugText.add(DebugText("get__ej_au     : ${ctx.client.get__ej_au()}"))
        debugText.add(DebugText("get__gl_bw     : ${ctx.client.get__gl_bw()}"))
        debugText.add(DebugText("get__hk_k      : ${ctx.client.get__hk_k()}"))
        debugText.add(DebugText("get__hk_z      : ${ctx.client.get__hk_z()}"))
        debugText.add(DebugText("get__hy_ac     : ${ctx.client.get__hy_ac()}"))
        debugText.add(DebugText("get__hy_ad     : ${ctx.client.get__hy_ad()}"))
        debugText.add(DebugText("get__hy_af     : ${ctx.client.get__hy_af()}"))
        debugText.add(DebugText("get__hy_ah     : ${ctx.client.get__hy_ah()}"))
        debugText.add(DebugText("get__hy_ai     : ${ctx.client.get__hy_ai()}"))
        debugText.add(DebugText("get__hy_aj     : ${ctx.client.get__hy_aj()}"))
        debugText.add(DebugText("get__hy_ak     : ${ctx.client.get__hy_ak()}"))
        debugText.add(DebugText("get__hy_al     : ${ctx.client.get__hy_al()}"))
        debugText.add(DebugText("get__hy_as     : ${ctx.client.get__hy_as()}"))
        debugText.add(DebugText("get__hy_av     : ${ctx.client.get__hy_av()}"))
        debugText.add(DebugText("get__hy_aw     : ${ctx.client.get__hy_aw()}"))
        debugText.add(DebugText("get__hy_ax     : ${ctx.client.get__hy_ax()}"))
        debugText.add(DebugText("get__hy_ay     : ${ctx.client.get__hy_ay()}"))
        debugText.add(DebugText("get__hy_az     : ${ctx.client.get__hy_az()}"))
        debugText.add(DebugText("get__hy_ba     : ${ctx.client.get__hy_ba()}"))
        debugText.add(DebugText("get__hy_bb     : ${ctx.client.get__hy_bb()}"))
        debugText.add(DebugText("get__hy_bc     : ${ctx.client.get__hy_bc()}"))
        debugText.add(DebugText("get__hy_bd     : ${ctx.client.get__hy_bd()}"))
        debugText.add(DebugText("get__hy_be     : ${ctx.client.get__hy_be()}"))
        debugText.add(DebugText("get__hy_bf     : ${ctx.client.get__hy_bf()}"))
        debugText.add(DebugText("get__hy_bg     : ${ctx.client.get__hy_bg()}"))
        debugText.add(DebugText("get__hy_bh     : ${ctx.client.get__hy_bh()}"))
        debugText.add(DebugText("get__hy_bi     : ${ctx.client.get__hy_bi()}"))
        debugText.add(DebugText("get__hy_bj     : ${ctx.client.get__hy_bj()}"))
        debugText.add(DebugText("get__hy_bk     : ${ctx.client.get__hy_bk()}"))
        debugText.add(DebugText("get__hy_bl     : ${ctx.client.get__hy_bl()}"))
        debugText.add(DebugText("get__hy_bm     : ${ctx.client.get__hy_bm()}"))
        debugText.add(DebugText("get__hy_bn     : ${ctx.client.get__hy_bn()}"))
        debugText.add(DebugText("get__hy_bo     : ${ctx.client.get__hy_bo()}"))
        debugText.add(DebugText("get__hy_bp     : ${ctx.client.get__hy_bp()}"))
        debugText.add(DebugText("get__hy_bq     : ${ctx.client.get__hy_bq()}"))
        debugText.add(DebugText("get__hy_br     : ${ctx.client.get__hy_br()}"))
        debugText.add(DebugText("get__hy_bs     : ${ctx.client.get__hy_bs()}"))
        debugText.add(DebugText("get__hy_bt     : ${ctx.client.get__hy_bt()}"))
        debugText.add(DebugText("get__hy_bu     : ${ctx.client.get__hy_bu()}"))
        debugText.add(DebugText("get__hy_bv     : ${ctx.client.get__hy_bv()}"))
        debugText.add(DebugText("get__hy_bw     : ${ctx.client.get__hy_bw()}"))
        debugText.add(DebugText("get__hy_bx     : ${ctx.client.get__hy_bx()}"))
        debugText.add(DebugText("get__hy_by     : ${ctx.client.get__hy_by()}"))
        debugText.add(DebugText("get__hy_bz     : ${ctx.client.get__hy_bz()}"))
        debugText.add(DebugText("get__hy_ca     : ${ctx.client.get__hy_ca()}"))
        debugText.add(DebugText("get__hy_cb     : ${ctx.client.get__hy_cb()}"))
        debugText.add(DebugText("get__hy_cc     : ${ctx.client.get__hy_cc()}"))
        debugText.add(DebugText("get__hy_cd     : ${ctx.client.get__hy_cd()}"))
        debugText.add(DebugText("get__hy_ce     : ${ctx.client.get__hy_ce()}"))
        debugText.add(DebugText("get__hy_cf     : ${ctx.client.get__hy_cf()}"))
        debugText.add(DebugText("get__hy_cg     : ${ctx.client.get__hy_cg()}"))
        debugText.add(DebugText("get__hy_ch     : ${ctx.client.get__hy_ch()}"))
        debugText.add(DebugText("get__hy_ci     : ${ctx.client.get__hy_ci()}"))
        debugText.add(DebugText("get__hy_cj     : ${ctx.client.get__hy_cj()}"))
        debugText.add(DebugText("get__hy_ck     : ${ctx.client.get__hy_ck()}"))
        debugText.add(DebugText("get__hy_cl     : ${ctx.client.get__hy_cl()}"))
        debugText.add(DebugText("get__hy_cm     : ${ctx.client.get__hy_cm()}"))
        debugText.add(DebugText("get__hy_cn     : ${ctx.client.get__hy_cn()}"))
        debugText.add(DebugText("get__hy_co     : ${ctx.client.get__hy_co()}"))
        debugText.add(DebugText("get__hy_cp     : ${ctx.client.get__hy_cp()}"))
        debugText.add(DebugText("get__hy_cq     : ${ctx.client.get__hy_cq()}"))
        debugText.add(DebugText("get__hy_cr     : ${ctx.client.get__hy_cr()}"))
        debugText.add(DebugText("get__hy_cs     : ${ctx.client.get__hy_cs()}"))
        debugText.add(DebugText("get__hy_ct     : ${ctx.client.get__hy_ct()}"))
        debugText.add(DebugText("get__hy_cu     : ${ctx.client.get__hy_cu()}"))
        debugText.add(DebugText("get__hy_cv     : ${ctx.client.get__hy_cv()}"))
        debugText.add(DebugText("get__hy_cw     : ${ctx.client.get__hy_cw()}"))
        debugText.add(DebugText("get__hy_cx     : ${ctx.client.get__hy_cx()}"))
        debugText.add(DebugText("get__hy_cy     : ${ctx.client.get__hy_cy()}"))
        debugText.add(DebugText("get__hy_cz     : ${ctx.client.get__hy_cz()}"))
        debugText.add(DebugText("get__hy_da     : ${ctx.client.get__hy_da()}"))
        debugText.add(DebugText("get__hy_db     : ${ctx.client.get__hy_db()}"))
        debugText.add(DebugText("get__hy_dd     : ${ctx.client.get__hy_dd()}"))
        debugText.add(DebugText("get__hy_de     : ${ctx.client.get__hy_de()}"))
        debugText.add(DebugText("get__hy_dg     : ${ctx.client.get__hy_dg()}"))
        debugText.add(DebugText("get__hy_dh     : ${ctx.client.get__hy_dh()}"))
        debugText.add(DebugText("get__hy_di     : ${ctx.client.get__hy_di()}"))
        debugText.add(DebugText("get__hy_dj     : ${ctx.client.get__hy_dj()}"))
        debugText.add(DebugText("get__hy_dk     : ${ctx.client.get__hy_dk()}"))
        debugText.add(DebugText("get__hy_dl     : ${ctx.client.get__hy_dl()}"))
        debugText.add(DebugText("get__hy_dm     : ${ctx.client.get__hy_dm()}"))
        debugText.add(DebugText("get__hy_dn     : ${ctx.client.get__hy_dn()}"))
        debugText.add(DebugText("get__hy_do     : ${ctx.client.get__hy_do()}"))
        debugText.add(DebugText("get__hy_dp     : ${ctx.client.get__hy_dp()}"))
        debugText.add(DebugText("get__hy_dq     : ${ctx.client.get__hy_dq()}"))
        debugText.add(DebugText("get__hy_dr     : ${ctx.client.get__hy_dr()}"))
        debugText.add(DebugText("get__hy_ds     : ${ctx.client.get__hy_ds()}"))
        debugText.add(DebugText("get__hy_dt     : ${ctx.client.get__hy_dt()}"))
        debugText.add(DebugText("get__hy_du     : ${ctx.client.get__hy_du()}"))
        debugText.add(DebugText("get__hy_dv     : ${ctx.client.get__hy_dv()}"))
        debugText.add(DebugText("get__hy_dw     : ${ctx.client.get__hy_dw()}"))
        debugText.add(DebugText("get__hy_dx     : ${ctx.client.get__hy_dx()}"))
        debugText.add(DebugText("get__hy_dy     : ${ctx.client.get__hy_dy()}"))
        debugText.add(DebugText("get__hy_dz     : ${ctx.client.get__hy_dz()}"))
        debugText.add(DebugText("get__hy_eb     : ${ctx.client.get__hy_eb()}"))
        debugText.add(DebugText("get__hy_ec     : ${ctx.client.get__hy_ec()}"))
        debugText.add(DebugText("get__hy_ee     : ${ctx.client.get__hy_ee()}"))
        debugText.add(DebugText("get__hy_ef     : ${ctx.client.get__hy_ef()}"))
        debugText.add(DebugText("get__hy_eg     : ${ctx.client.get__hy_eg()}"))
        debugText.add(DebugText("get__hy_eh     : ${ctx.client.get__hy_eh()}"))
        debugText.add(DebugText("get__hy_ej     : ${ctx.client.get__hy_ej()}"))
        debugText.add(DebugText("get__hy_ek     : ${ctx.client.get__hy_ek()}"))
        debugText.add(DebugText("get__hy_em     : ${ctx.client.get__hy_em()}"))
        debugText.add(DebugText("get__hy_en     : ${ctx.client.get__hy_en()}"))
        debugText.add(DebugText("get__hy_eo     : ${ctx.client.get__hy_eo()}"))
        debugText.add(DebugText("get__hy_ep     : ${ctx.client.get__hy_ep()}"))
        debugText.add(DebugText("get__hy_eq     : ${ctx.client.get__hy_eq()}"))
        debugText.add(DebugText("get__hy_er     : ${ctx.client.get__hy_er()}"))
        debugText.add(DebugText("get__hy_es     : ${ctx.client.get__hy_es()}"))
        debugText.add(DebugText("get__hy_et     : ${ctx.client.get__hy_et()}"))
        debugText.add(DebugText("get__hy_eu     : ${ctx.client.get__hy_eu()}"))
        debugText.add(DebugText("get__hy_ew     : ${ctx.client.get__hy_ew()}"))
        debugText.add(DebugText("get__hy_ex     : ${ctx.client.get__hy_ex()}"))
        debugText.add(DebugText("get__hy_ey     : ${ctx.client.get__hy_ey()}"))
        debugText.add(DebugText("get__hy_ez     : ${ctx.client.get__hy_ez()}"))
        debugText.add(DebugText("get__hy_fb     : ${ctx.client.get__hy_fb()}"))
        debugText.add(DebugText("get__hy_fc     : ${ctx.client.get__hy_fc()}"))
        debugText.add(DebugText("get__hy_ff     : ${ctx.client.get__hy_ff()}"))
        debugText.add(DebugText("get__hy_fg     : ${ctx.client.get__hy_fg()}"))
        debugText.add(DebugText("get__hy_fh     : ${ctx.client.get__hy_fh()}"))
        debugText.add(DebugText("get__hy_fl     : ${ctx.client.get__hy_fl()}"))
        debugText.add(DebugText("get__hy_fm     : ${ctx.client.get__hy_fm()}"))
        debugText.add(DebugText("get__hy_fo     : ${ctx.client.get__hy_fo()}"))
        debugText.add(DebugText("get__hy_ft     : ${ctx.client.get__hy_ft()}"))
        debugText.add(DebugText("get__hy_fu     : ${ctx.client.get__hy_fu()}"))
        debugText.add(DebugText("get__hy_ga     : ${ctx.client.get__hy_ga()}"))
        debugText.add(DebugText("get__hy_gb     : ${ctx.client.get__hy_gb()}"))
        debugText.add(DebugText("get__hy_gc     : ${ctx.client.get__hy_gc()}"))
        debugText.add(DebugText("get__hy_gd     : ${ctx.client.get__hy_gd()}"))
        debugText.add(DebugText("get__hy_ge     : ${ctx.client.get__hy_ge()}"))
        debugText.add(DebugText("get__hy_gf     : ${ctx.client.get__hy_gf()}"))
        debugText.add(DebugText("get__hy_gg     : ${ctx.client.get__hy_gg()}"))
        debugText.add(DebugText("get__hy_gh     : ${ctx.client.get__hy_gh()}"))
        debugText.add(DebugText("get__hy_gi     : ${ctx.client.get__hy_gi()}"))
        debugText.add(DebugText("get__hy_gj     : ${ctx.client.get__hy_gj()}"))
        debugText.add(DebugText("get__hy_gk     : ${ctx.client.get__hy_gk()}"))
        debugText.add(DebugText("get__hy_gl     : ${ctx.client.get__hy_gl()}"))
        debugText.add(DebugText("get__hy_gm     : ${ctx.client.get__hy_gm()}"))
        debugText.add(DebugText("get__hy_gn     : ${ctx.client.get__hy_gn()}"))
        debugText.add(DebugText("get__hy_go     : ${ctx.client.get__hy_go()}"))
        debugText.add(DebugText("get__hy_gp     : ${ctx.client.get__hy_gp()}"))
        debugText.add(DebugText("get__hy_gq     : ${ctx.client.get__hy_gq()}"))
        debugText.add(DebugText("get__hy_gr     : ${ctx.client.get__hy_gr()}"))
        debugText.add(DebugText("get__hy_gs     : ${ctx.client.get__hy_gs()}"))
        debugText.add(DebugText("get__hy_gt     : ${ctx.client.get__hy_gt()}"))
        debugText.add(DebugText("get__hy_gu     : ${ctx.client.get__hy_gu()}"))
        debugText.add(DebugText("get__hy_gv     : ${ctx.client.get__hy_gv()}"))
        debugText.add(DebugText("get__hy_gw     : ${ctx.client.get__hy_gw()}"))
        debugText.add(DebugText("get__hy_gx     : ${ctx.client.get__hy_gx()}"))
        debugText.add(DebugText("get__hy_gy     : ${ctx.client.get__hy_gy()}"))
        debugText.add(DebugText("get__hy_gz     : ${ctx.client.get__hy_gz()}"))
        debugText.add(DebugText("get__hy_hb     : ${ctx.client.get__hy_hb()}"))
        debugText.add(DebugText("get__hy_hd     : ${ctx.client.get__hy_hd()}"))
        debugText.add(DebugText("get__hy_he     : ${ctx.client.get__hy_he()}"))
        debugText.add(DebugText("get__hy_hf     : ${ctx.client.get__hy_hf()}"))
        debugText.add(DebugText("get__hy_hh     : ${ctx.client.get__hy_hh()}"))
        debugText.add(DebugText("get__hy_hi     : ${ctx.client.get__hy_hi()}"))
        debugText.add(DebugText("get__hy_hj     : ${ctx.client.get__hy_hj()}"))
        debugText.add(DebugText("get__hy_hk     : ${ctx.client.get__hy_hk()}"))
        debugText.add(DebugText("get__hy_hm     : ${ctx.client.get__hy_hm()}"))
        debugText.add(DebugText("get__hy_hn     : ${ctx.client.get__hy_hn()}"))
        debugText.add(DebugText("get__hy_hp     : ${ctx.client.get__hy_hp()}"))
        debugText.add(DebugText("get__hy_hw     : ${ctx.client.get__hy_hw()}"))
        debugText.add(DebugText("get__hy_hx     : ${ctx.client.get__hy_hx()}"))
        debugText.add(DebugText("get__hy_hy     : ${ctx.client.get__hy_hy()}"))
        debugText.add(DebugText("get__hy_ib     : ${ctx.client.get__hy_ib()}"))
        debugText.add(DebugText("get__hy_ie     : ${ctx.client.get__hy_ie()}"))
        debugText.add(DebugText("get__hy_if     : ${ctx.client.get__hy_if()}"))
        debugText.add(DebugText("get__hy_ig     : ${ctx.client.get__hy_ig()}"))
        debugText.add(DebugText("get__hy_ih     : ${ctx.client.get__hy_ih()}"))
        debugText.add(DebugText("get__hy_ij     : ${ctx.client.get__hy_ij()}"))
        debugText.add(DebugText("get__hy_ik     : ${ctx.client.get__hy_ik()}"))
        debugText.add(DebugText("get__hy_il     : ${ctx.client.get__hy_il()}"))
        debugText.add(DebugText("get__hy_im     : ${ctx.client.get__hy_im()}"))
        debugText.add(DebugText("get__hy_in     : ${ctx.client.get__hy_in()}"))
        debugText.add(DebugText("get__hy_ir     : ${ctx.client.get__hy_ir()}"))
        debugText.add(DebugText("get__hy_is     : ${ctx.client.get__hy_is()}"))
        debugText.add(DebugText("get__hy_it     : ${ctx.client.get__hy_it()}"))
        debugText.add(DebugText("get__hy_iu     : ${ctx.client.get__hy_iu()}"))
        debugText.add(DebugText("get__hy_iv     : ${ctx.client.get__hy_iv()}"))
        debugText.add(DebugText("get__hy_ix     : ${ctx.client.get__hy_ix()}"))
        debugText.add(DebugText("get__hy_iy     : ${ctx.client.get__hy_iy()}"))
        debugText.add(DebugText("get__hy_iz     : ${ctx.client.get__hy_iz()}"))
        debugText.add(DebugText("get__hy_ja     : ${ctx.client.get__hy_ja()}"))
        debugText.add(DebugText("get__hy_jb     : ${ctx.client.get__hy_jb()}"))
        debugText.add(DebugText("get__hy_jc     : ${ctx.client.get__hy_jc()}"))
        debugText.add(DebugText("get__hy_jd     : ${ctx.client.get__hy_jd()}"))
        debugText.add(DebugText("get__hy_je     : ${ctx.client.get__hy_je()}"))
        debugText.add(DebugText("get__hy_jf     : ${ctx.client.get__hy_jf()}"))
        debugText.add(DebugText("get__hy_jg     : ${ctx.client.get__hy_jg()}"))
        debugText.add(DebugText("get__hy_jh     : ${ctx.client.get__hy_jh()}"))
        debugText.add(DebugText("get__hy_ji     : ${ctx.client.get__hy_ji()}"))
        debugText.add(DebugText("get__hy_jj     : ${ctx.client.get__hy_jj()}"))
        debugText.add(DebugText("get__hy_jk     : ${ctx.client.get__hy_jk()}"))
        debugText.add(DebugText("get__hy_jl     : ${ctx.client.get__hy_jl()}"))
        debugText.add(DebugText("get__hy_jm     : ${ctx.client.get__hy_jm()}"))
        debugText.add(DebugText("get__hy_jn     : ${ctx.client.get__hy_jn()}"))
        debugText.add(DebugText("get__hy_jo     : ${ctx.client.get__hy_jo()}"))
        debugText.add(DebugText("get__hy_jp     : ${ctx.client.get__hy_jp()}"))
        debugText.add(DebugText("get__hy_jq     : ${ctx.client.get__hy_jq()}"))
        debugText.add(DebugText("get__hy_jr     : ${ctx.client.get__hy_jr()}"))
        debugText.add(DebugText("get__hy_js     : ${ctx.client.get__hy_js()}"))
        debugText.add(DebugText("get__hy_jt     : ${ctx.client.get__hy_jt()}"))
        debugText.add(DebugText("get__hy_ju     : ${ctx.client.get__hy_ju()}"))
        debugText.add(DebugText("get__hy_jv     : ${ctx.client.get__hy_jv()}"))
        debugText.add(DebugText("get__hy_jw     : ${ctx.client.get__hy_jw()}"))
        debugText.add(DebugText("get__hy_jx     : ${ctx.client.get__hy_jx()}"))
        debugText.add(DebugText("get__hy_jy     : ${ctx.client.get__hy_jy()}"))
        debugText.add(DebugText("get__hy_jz     : ${ctx.client.get__hy_jz()}"))
        debugText.add(DebugText("get__hy_ka     : ${ctx.client.get__hy_ka()}"))
        debugText.add(DebugText("get__hy_kb     : ${ctx.client.get__hy_kb()}"))
        debugText.add(DebugText("get__hy_kc     : ${ctx.client.get__hy_kc()}"))
        debugText.add(DebugText("get__hy_kd     : ${ctx.client.get__hy_kd()}"))
        debugText.add(DebugText("get__hy_ke     : ${ctx.client.get__hy_ke()}"))
        debugText.add(DebugText("get__hy_kh     : ${ctx.client.get__hy_kh()}"))
        debugText.add(DebugText("get__hy_kk     : ${ctx.client.get__hy_kk()}"))
        debugText.add(DebugText("get__hy_kl     : ${ctx.client.get__hy_kl()}"))
        debugText.add(DebugText("get__hy_km     : ${ctx.client.get__hy_km()}"))
        debugText.add(DebugText("get__hy_ko     : ${ctx.client.get__hy_ko()}"))
        debugText.add(DebugText("get__hy_kp     : ${ctx.client.get__hy_kp()}"))
        debugText.add(DebugText("get__hy_ks     : ${ctx.client.get__hy_ks()}"))
        debugText.add(DebugText("get__hy_kt     : ${ctx.client.get__hy_kt()}"))
        debugText.add(DebugText("get__hy_ku     : ${ctx.client.get__hy_ku()}"))
        debugText.add(DebugText("get__hy_kw     : ${ctx.client.get__hy_kw()}"))
        debugText.add(DebugText("get__hy_kx     : ${ctx.client.get__hy_kx()}"))
        debugText.add(DebugText("get__hy_m      : ${ctx.client.get__hy_m()}"))
        debugText.add(DebugText("get__hy_n      : ${ctx.client.get__hy_n()}"))
        debugText.add(DebugText("get__hy_w      : ${ctx.client.get__hy_w()}"))
        debugText.add(DebugText("get__hy_aq     : ${ctx.client.get__hy_aq()}"))



//        debugText.add(DebugText("clientData.loginState :${ctx.client.get__a}"))


        val yBase = 70
        var x = 50
        var y = yBase
        var bannedY = 10
        var bannedX = 50
        val savedFont = g.font
        g.font = Font("Consolas", Font.PLAIN, 10)
        debugText.forEachIndexed { index, debugText ->
            g.color = Color.ORANGE

            g.drawString(debugText.text, x, y)
            //Loginto a banned account and we can get this result
            if(debugText.text.contains("12")){
                g.drawString(debugText.text, bannedX, bannedY)
                bannedY+= 15
            }
            y += 15
            if(index > 0 && index % 40 == 0){
                y = yBase
                x += 250
            }
        }
        g.font = savedFont
    }


}
