package com.p3achb0t.scripts.paint.debug

import com.p3achb0t.api.Context
import com.p3achb0t.api.LoginResponse
import com.p3achb0t.api.wrappers.utils.Calculations
import java.awt.Color
import java.awt.Font
import java.awt.Graphics



fun drawClientDebugText(g: Graphics, ctx: Context) {

    val debugText = arrayListOf<DebugText>()
    if (true) {

        g.color = Color.white
        debugText.add(DebugText("get__h_rq      : ${ctx.client.get__h_rq()}"))
        debugText.add(DebugText("get__o_rm      : ${ctx.client.get__o_rm()}"))
        debugText.add(DebugText("get__t_b       : ${ctx.client.get__t_b()}"))
        debugText.add(DebugText("get__t_mh      : ${ctx.client.get__t_mh()}"))
        debugText.add(DebugText("get__v_ga      : ${ctx.client.get__v_ga()}"))
        debugText.add(DebugText("get__x_gl      : ${ctx.client.get__x_gl()}"))
        debugText.add(DebugText("get__a_eu      : ${ctx.client.get__a_eu()}"))
        debugText.add(DebugText("get__u_rg      : ${ctx.client.get__u_rg()}"))
        debugText.add(DebugText("get__f_j       : ${ctx.client.get__f_j()}"))
        debugText.add(DebugText("get__ay_cr     : ${ctx.client.get__ay_cr()}"))
        debugText.add(DebugText("get__ay_cg     : ${ctx.client.get__ay_cg()}"))
        debugText.add(DebugText("get__ay_cj     : ${ctx.client.get__ay_cj()}"))
        debugText.add(DebugText("get__ay_co     : ${ctx.client.get__ay_co()}"))
        debugText.add(DebugText("get__ay_ct     : ${ctx.client.get__ay_ct()}"))
        debugText.add(DebugText("get__ay_cw     : ${ctx.client.get__ay_cw()}"))
        debugText.add(DebugText("get__ac_bn     : ${ctx.client.get__ac_bn()}"))
        debugText.add(DebugText("get__aq_t      : ${ctx.client.get__aq_t()}"))
        debugText.add(DebugText("get__aq_b      : ${ctx.client.get__aq_b()}"))
        debugText.add(DebugText("get__aq_e      : ${ctx.client.get__aq_e()}"))
        debugText.add(DebugText("get__aq_o      : ${ctx.client.get__aq_o()}"))
        debugText.add(DebugText("get__aq_v      : ${ctx.client.get__aq_v()}"))
        debugText.add(DebugText("get__bf_ry     : ${ctx.client.get__bf_ry()}"))
        debugText.add(DebugText("get__bg_iq     : ${ctx.client.get__bg_iq()}"))
        debugText.add(DebugText("get__bi_b      : ${ctx.client.get__bi_b()}"))
        debugText.add(DebugText("get__bs_rp     : ${ctx.client.get__bs_rp()}"))
        debugText.add(DebugText("get__client_tm : ${ctx.client.get__client_tm()}"))
        debugText.add(DebugText("get__client_bg : ${ctx.client.get__client_bg()}"))
        debugText.add(DebugText("get__client_co : ${ctx.client.get__client_co()}"))
        debugText.add(DebugText("get__client_cz : ${ctx.client.get__client_cz()}"))
        debugText.add(DebugText("get__client_dh : ${ctx.client.get__client_dh()}"))
        debugText.add(DebugText("get__client_dn : ${ctx.client.get__client_dn()}"))
        debugText.add(DebugText("get__client_ej : ${ctx.client.get__client_ej()}"))
        debugText.add(DebugText("get__client_es : ${ctx.client.get__client_es()}"))
        debugText.add(DebugText("get__client_ev : ${ctx.client.get__client_ev()}"))
        debugText.add(DebugText("get__client_fv : ${ctx.client.get__client_fv()}"))
        debugText.add(DebugText("get__client_fz : ${ctx.client.get__client_fz()}"))
        debugText.add(DebugText("get__client_gc : ${ctx.client.get__client_gc()}"))
        debugText.add(DebugText("get__client_gf : ${ctx.client.get__client_gf()}"))
        debugText.add(DebugText("get__client_gk : ${ctx.client.get__client_gk()}"))
        debugText.add(DebugText("get__client_gp : ${ctx.client.get__client_gp()}"))
        debugText.add(DebugText("get__client_gs : ${ctx.client.get__client_gs()}"))
        debugText.add(DebugText("get__client_gy : ${ctx.client.get__client_gy()}"))
        debugText.add(DebugText("get__client_hc : ${ctx.client.get__client_hc()}"))
        debugText.add(DebugText("get__client_he : ${ctx.client.get__client_he()}"))
        debugText.add(DebugText("get__client_hl : ${ctx.client.get__client_hl()}"))
        debugText.add(DebugText("get__client_ho : ${ctx.client.get__client_ho()}"))
        debugText.add(DebugText("get__client_hp : ${ctx.client.get__client_hp()}"))
        debugText.add(DebugText("get__client_hq : ${ctx.client.get__client_hq()}"))
        debugText.add(DebugText("get__client_ht : ${ctx.client.get__client_ht()}"))
        debugText.add(DebugText("get__client_hu : ${ctx.client.get__client_hu()}"))
        debugText.add(DebugText("get__client_hv : ${ctx.client.get__client_hv()}"))
        debugText.add(DebugText("get__client_ia : ${ctx.client.get__client_ia()}"))
        debugText.add(DebugText("get__client_ie : ${ctx.client.get__client_ie()}"))
        debugText.add(DebugText("get__client_if : ${ctx.client.get__client_if()}"))
        debugText.add(DebugText("get__client_ij : ${ctx.client.get__client_ij()}"))
        debugText.add(DebugText("get__client_ik : ${ctx.client.get__client_ik()}"))
        debugText.add(DebugText("get__client_ip : ${ctx.client.get__client_ip()}"))
        debugText.add(DebugText("get__client_ir : ${ctx.client.get__client_ir()}"))
        debugText.add(DebugText("get__client_iv : ${ctx.client.get__client_iv()}"))
        debugText.add(DebugText("get__client_iw : ${ctx.client.get__client_iw()}"))
        debugText.add(DebugText("get__client_jc : ${ctx.client.get__client_jc()}"))
        debugText.add(DebugText("get__client_jm : ${ctx.client.get__client_jm()}"))
        debugText.add(DebugText("get__client_jo : ${ctx.client.get__client_jo()}"))
        debugText.add(DebugText("get__client_jp : ${ctx.client.get__client_jp()}"))
        debugText.add(DebugText("get__client_jv : ${ctx.client.get__client_jv()}"))
        debugText.add(DebugText("get__client_kb : ${ctx.client.get__client_kb()}"))
        debugText.add(DebugText("get__client_kd : ${ctx.client.get__client_kd()}"))
        debugText.add(DebugText("get__client_kp : ${ctx.client.get__client_kp()}"))
        debugText.add(DebugText("get__client_lb : ${ctx.client.get__client_lb()}"))
        debugText.add(DebugText("get__client_ll : ${ctx.client.get__client_ll()}"))
        debugText.add(DebugText("get__client_lz : ${ctx.client.get__client_lz()}"))
        debugText.add(DebugText("get__client_me : ${ctx.client.get__client_me()}"))
        debugText.add(DebugText("get__client_mg : ${ctx.client.get__client_mg()}"))
        debugText.add(DebugText("get__client_mn : ${ctx.client.get__client_mn()}"))
        debugText.add(DebugText("get__client_mq : ${ctx.client.get__client_mq()}"))
        debugText.add(DebugText("get__client_mv : ${ctx.client.get__client_mv()}"))
        debugText.add(DebugText("get__client_mx : ${ctx.client.get__client_mx()}"))
        debugText.add(DebugText("get__client_mz : ${ctx.client.get__client_mz()}"))
        debugText.add(DebugText("get__client_nb : ${ctx.client.get__client_nb()}"))
        debugText.add(DebugText("get__client_nk : ${ctx.client.get__client_nk()}"))
        debugText.add(DebugText("get__client_nl : ${ctx.client.get__client_nl()}"))
        debugText.add(DebugText("get__client_np : ${ctx.client.get__client_np()}"))
        debugText.add(DebugText("get__client_nu : ${ctx.client.get__client_nu()}"))
        debugText.add(DebugText("get__client_nw : ${ctx.client.get__client_nw()}"))
        debugText.add(DebugText("get__client_nx : ${ctx.client.get__client_nx()}"))
        debugText.add(DebugText("get__client_oa : ${ctx.client.get__client_oa()}"))
        debugText.add(DebugText("get__client_od : ${ctx.client.get__client_od()}"))
        debugText.add(DebugText("get__client_of : ${ctx.client.get__client_of()}"))
        debugText.add(DebugText("get__client_og : ${ctx.client.get__client_og()}"))
        debugText.add(DebugText("get__client_ok : ${ctx.client.get__client_ok()}"))
        debugText.add(DebugText("get__client_ol : ${ctx.client.get__client_ol()}"))
        debugText.add(DebugText("get__client_oo : ${ctx.client.get__client_oo()}"))
        debugText.add(DebugText("get__client_oq : ${ctx.client.get__client_oq()}"))
        debugText.add(DebugText("get__client_ov : ${ctx.client.get__client_ov()}"))
        debugText.add(DebugText("get__client_ow : ${ctx.client.get__client_ow()}"))
        debugText.add(DebugText("get__client_oy : ${ctx.client.get__client_oy()}"))
        debugText.add(DebugText("get__client_ps : ${ctx.client.get__client_ps()}"))
        debugText.add(DebugText("get__client_pu : ${ctx.client.get__client_pu()}"))
        debugText.add(DebugText("get__client_py : ${ctx.client.get__client_py()}"))
        debugText.add(DebugText("get__client_qj : ${ctx.client.get__client_qj()}"))
        debugText.add(DebugText("get__client_qq : ${ctx.client.get__client_qq()}"))
        debugText.add(DebugText("get__client_rx : ${ctx.client.get__client_rx()}"))
        debugText.add(DebugText("get__client_sx : ${ctx.client.get__client_sx()}"))
        debugText.add(DebugText("get__client_sz : ${ctx.client.get__client_sz()}"))
        debugText.add(DebugText("get__client_tk : ${ctx.client.get__client_tk()}"))
        debugText.add(DebugText("get__bc_t      : ${ctx.client.get__bc_t()}"))
        debugText.add(DebugText("get__cm_n      : ${ctx.client.get__cm_n()}"))
        debugText.add(DebugText("get__cm_rk     : ${ctx.client.get__cm_rk()}"))
        debugText.add(DebugText("get__ce_cs     : ${ctx.client.get__ce_cs()}"))
        debugText.add(DebugText("get__cc_aj     : ${ctx.client.get__cc_aj()}"))
        debugText.add(DebugText("get__cc_av     : ${ctx.client.get__cc_av()}"))
        debugText.add(DebugText("get__cc_ax     : ${ctx.client.get__cc_ax()}"))
        debugText.add(DebugText("get__cc_bf     : ${ctx.client.get__cc_bf()}"))
        debugText.add(DebugText("get__cc_bi     : ${ctx.client.get__cc_bi()}"))
        debugText.add(DebugText("get__cc_bj     : ${ctx.client.get__cc_bj()}"))
        debugText.add(DebugText("get__cc_bp     : ${ctx.client.get__cc_bp()}"))
        debugText.add(DebugText("get__cc_m      : ${ctx.client.get__cc_m()}"))
        debugText.add(DebugText("get__cc_o      : ${ctx.client.get__cc_o()}"))
        debugText.add(DebugText("get__cs_n      : ${ctx.client.get__cs_n()}"))
        debugText.add(DebugText("get__cs_w      : ${ctx.client.get__cs_w()}"))
        debugText.add(DebugText("get__cw_an     : ${ctx.client.get__cw_an()}"))
        debugText.add(DebugText("get__cv_h      : ${ctx.client.get__cv_h()}"))
        debugText.add(DebugText("get__dw_k      : ${ctx.client.get__dw_k()}"))
        debugText.add(DebugText("get__dw_v      : ${ctx.client.get__dw_v()}"))
        debugText.add(DebugText("get__dn_rr     : ${ctx.client.get__dn_rr()}"))
        debugText.add(DebugText("get__dy_ef     : ${ctx.client.get__dy_ef()}"))
        debugText.add(DebugText("get__dv_ar     : ${ctx.client.get__dv_ar()}"))
        debugText.add(DebugText("get__dk_ab     : ${ctx.client.get__dk_ab()}"))
        debugText.add(DebugText("get__ee_eo     : ${ctx.client.get__ee_eo()}"))
        debugText.add(DebugText("get__ea_tl     : ${ctx.client.get__ea_tl()}"))
        debugText.add(DebugText("get__ed_gv     : ${ctx.client.get__ed_gv()}"))
        debugText.add(DebugText("get__ev_ni     : ${ctx.client.get__ev_ni()}"))
        debugText.add(DebugText("get__es_o      : ${ctx.client.get__es_o()}"))
        debugText.add(DebugText("get__es_rd     : ${ctx.client.get__es_rd()}"))
        debugText.add(DebugText("get__eg_in     : ${ctx.client.get__eg_in()}"))
        debugText.add(DebugText("get__ex_z      : ${ctx.client.get__ex_z()}"))
        debugText.add(DebugText("get__eu_t      : ${ctx.client.get__eu_t()}"))
        debugText.add(DebugText("get__fn_l      : ${ctx.client.get__fn_l()}"))
        debugText.add(DebugText("get__fn_z      : ${ctx.client.get__fn_z()}"))
        debugText.add(DebugText("get__fs_te     : ${ctx.client.get__fs_te()}"))
        debugText.add(DebugText("get__fv_x      : ${ctx.client.get__fv_x()}"))
        debugText.add(DebugText("get__gs_k      : ${ctx.client.get__gs_k()}"))
        debugText.add(DebugText("get__gk_ak     : ${ctx.client.get__gk_ak()}"))
        debugText.add(DebugText("get__gz_aa     : ${ctx.client.get__gz_aa()}"))
        debugText.add(DebugText("get__gz_p      : ${ctx.client.get__gz_p()}"))
        debugText.add(DebugText("get__gm_b      : ${ctx.client.get__gm_b()}"))
        debugText.add(DebugText("get__gm_l      : ${ctx.client.get__gm_l()}"))
        debugText.add(DebugText("get__gm_q      : ${ctx.client.get__gm_q()}"))
        debugText.add(DebugText("get__hd_m      : ${ctx.client.get__hd_m()}"))
        debugText.add(DebugText("get__hh_eh     : ${ctx.client.get__hh_eh()}"))
        debugText.add(DebugText("get__hh_i      : ${ctx.client.get__hh_i()}"))
        debugText.add(DebugText("get__hm_z      : ${ctx.client.get__hm_z()}"))
        debugText.add(DebugText("get__hk_b      : ${ctx.client.get__hk_b()}"))
        debugText.add(DebugText("get__hv_nm     : ${ctx.client.get__hv_nm()}"))
        debugText.add(DebugText("get__he_gb     : ${ctx.client.get__he_gb()}"))
        debugText.add(DebugText("get__hc_l      : ${ctx.client.get__hc_l()}"))
        debugText.add(DebugText("get__hc_q      : ${ctx.client.get__hc_q()}"))
        debugText.add(DebugText("get__im_v      : ${ctx.client.get__im_v()}"))
        debugText.add(DebugText("get__jg_o      : ${ctx.client.get__jg_o()}"))
        debugText.add(DebugText("get__jp_aj     : ${ctx.client.get__jp_aj()}"))
        debugText.add(DebugText("get__ju_c      : ${ctx.client.get__ju_c()}"))
        debugText.add(DebugText("get__ju_e      : ${ctx.client.get__ju_e()}"))
        debugText.add(DebugText("get__je_il     : ${ctx.client.get__je_il()}"))
        debugText.add(DebugText("get__kl_p      : ${ctx.client.get__kl_p()}"))
        debugText.add(DebugText("get__kr_rf     : ${ctx.client.get__kr_rf()}"))
        debugText.add(DebugText("get__kf_a      : ${ctx.client.get__kf_a()}"))
        debugText.add(DebugText("get__od_c      : ${ctx.client.get__od_c()}"))
        debugText.add(DebugText("get__od_h      : ${ctx.client.get__od_h()}"))
        debugText.add(DebugText("get__od_o      : ${ctx.client.get__od_o()}"))
        debugText.add(DebugText("get__ou_c      : ${ctx.client.get__ou_c()}"))
        debugText.add(DebugText("get__ot_g      : ${ctx.client.get__ot_g()}"))
        ///////////-------------Strings --------------- ///////////////////
//        debugText.add(DebugText("getStrings_login: ${ctx.client.getStrings_login()}"))
//        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response0()}"))
//        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response1()}"))
//        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response2()}"))
//        debugText.add(DebugText("getLogin_response0: ${ctx.client.getLogin_response3()}"))
//        debugText.add(DebugText("getLogin_loadingText: ${ctx.client.getLogin_loadingText()}"))
//        debugText.add(DebugText("getStrings_login: ${ctx.client.getStrings_login()}"))
////        debugText.add(DebugText("login response: ${ctx.client.get__cx_at()}"))
//        debugText.add(DebugText("getLoginState: ${ctx.client.getLoginState()}"))
//        debugText.add(DebugText("getLoginType().get__m(: ${ctx.client.getLoginType().get__t()}"))
//        debugText.add(DebugText("getLoginType().get__n(: ${ctx.client.getLoginType().get__e()}"))
//        debugText.add(DebugText("get__ax_ba     : ${ctx.client.get__ax_ba()}"))
//        debugText.add(DebugText("get__bo_b      : ${ctx.client.get__bo_b()}"))
//        debugText.add(DebugText("get__client_ps : ${ctx.client.get__client_ps()}"))
//        debugText.add(DebugText("get__client_s  : ${ctx.client.get__client_s()}"))
//        debugText.add(DebugText("get__bz_ag     : ${ctx.client.get__bz_ag()}"))
//        debugText.add(DebugText("get__ci_r      : ${ctx.client.get__ci_r()}"))
//        debugText.add(DebugText("get__cj_bc     : ${ctx.client.get__cj_bc()}"))
//        debugText.add(DebugText("get__cj_bg     : ${ctx.client.get__cj_bg()}"))
//        debugText.add(DebugText("get__ff_ah     : ${ctx.client.get__ff_ah()}"))
//        debugText.add(DebugText("get__hn_b      : ${ctx.client.get__hn_b()}"))
//        debugText.add(DebugText("get__hn_f      : ${ctx.client.get__hn_f()}"))
//        debugText.add(DebugText("get__he_aa     : ${ctx.client.get__he_aa()}"))
//        debugText.add(DebugText("get__he_ad     : ${ctx.client.get__he_ad()}"))
//        debugText.add(DebugText("get__he_ae     : ${ctx.client.get__he_ae()}"))
//        debugText.add(DebugText("get__he_ag     : ${ctx.client.get__he_ag()}"))
//        debugText.add(DebugText("get__he_aj     : ${ctx.client.get__he_aj()}"))
//        debugText.add(DebugText("get__he_al     : ${ctx.client.get__he_al()}"))
//        debugText.add(DebugText("get__he_am     : ${ctx.client.get__he_am()}"))
//        debugText.add(DebugText("get__he_an     : ${ctx.client.get__he_an()}"))
//        debugText.add(DebugText("get__he_ap     : ${ctx.client.get__he_ap()}"))
//        debugText.add(DebugText("get__he_aq     : ${ctx.client.get__he_aq()}"))
//        debugText.add(DebugText("get__he_as     : ${ctx.client.get__he_as()}"))
//        debugText.add(DebugText("get__he_at     : ${ctx.client.get__he_at()}"))
//        debugText.add(DebugText("get__he_aw     : ${ctx.client.get__he_aw()}"))
//        debugText.add(DebugText("get__he_ax     : ${ctx.client.get__he_ax()}"))
//        debugText.add(DebugText("get__he_ba     : ${ctx.client.get__he_ba()}"))
//        debugText.add(DebugText("get__he_bb     : ${ctx.client.get__he_bb()}"))
//        debugText.add(DebugText("get__he_bc     : ${ctx.client.get__he_bc()}"))
//        debugText.add(DebugText("get__he_bd     : ${ctx.client.get__he_bd()}"))
//        debugText.add(DebugText("get__he_be     : ${ctx.client.get__he_be()}"))
//        debugText.add(DebugText("get__he_bf     : ${ctx.client.get__he_bf()}"))
//        debugText.add(DebugText("get__he_bg     : ${ctx.client.get__he_bg()}"))
//        debugText.add(DebugText("get__he_bh     : ${ctx.client.get__he_bh()}"))
//        debugText.add(DebugText("get__he_bi     : ${ctx.client.get__he_bi()}"))
//        debugText.add(DebugText("get__he_bj     : ${ctx.client.get__he_bj()}"))
//        debugText.add(DebugText("get__he_bk     : ${ctx.client.get__he_bk()}"))
//        debugText.add(DebugText("get__he_bl     : ${ctx.client.get__he_bl()}"))
//        debugText.add(DebugText("get__he_bm     : ${ctx.client.get__he_bm()}"))
//        debugText.add(DebugText("get__he_bn     : ${ctx.client.get__he_bn()}"))
//        debugText.add(DebugText("get__he_bo     : ${ctx.client.get__he_bo()}"))
//        debugText.add(DebugText("get__he_bp     : ${ctx.client.get__he_bp()}"))
//        debugText.add(DebugText("get__he_bq     : ${ctx.client.get__he_bq()}"))
//        debugText.add(DebugText("get__he_br     : ${ctx.client.get__he_br()}"))
//        debugText.add(DebugText("get__he_bs     : ${ctx.client.get__he_bs()}"))
//        debugText.add(DebugText("get__he_bt     : ${ctx.client.get__he_bt()}"))
//        debugText.add(DebugText("get__he_bu     : ${ctx.client.get__he_bu()}"))
//        debugText.add(DebugText("get__he_bv     : ${ctx.client.get__he_bv()}"))
//        debugText.add(DebugText("get__he_bw     : ${ctx.client.get__he_bw()}"))
//        debugText.add(DebugText("get__he_bx     : ${ctx.client.get__he_bx()}"))
//        debugText.add(DebugText("get__he_by     : ${ctx.client.get__he_by()}"))
//        debugText.add(DebugText("get__he_bz     : ${ctx.client.get__he_bz()}"))
//        debugText.add(DebugText("get__he_c      : ${ctx.client.get__he_c()}"))
//        debugText.add(DebugText("get__he_ca     : ${ctx.client.get__he_ca()}"))
//        debugText.add(DebugText("get__he_cb     : ${ctx.client.get__he_cb()}"))
//        debugText.add(DebugText("get__he_cc     : ${ctx.client.get__he_cc()}"))
//        debugText.add(DebugText("get__he_cd     : ${ctx.client.get__he_cd()}"))
//        debugText.add(DebugText("get__he_ce     : ${ctx.client.get__he_ce()}"))
//        debugText.add(DebugText("get__he_cf     : ${ctx.client.get__he_cf()}"))
//        debugText.add(DebugText("get__he_cg     : ${ctx.client.get__he_cg()}"))
//        debugText.add(DebugText("get__he_ch     : ${ctx.client.get__he_ch()}"))
//        debugText.add(DebugText("get__he_ci     : ${ctx.client.get__he_ci()}"))
//        debugText.add(DebugText("get__he_cj     : ${ctx.client.get__he_cj()}"))
//        debugText.add(DebugText("get__he_ck     : ${ctx.client.get__he_ck()}"))
//        debugText.add(DebugText("get__he_cl     : ${ctx.client.get__he_cl()}"))
//        debugText.add(DebugText("get__he_cm     : ${ctx.client.get__he_cm()}"))
//        debugText.add(DebugText("get__he_cn     : ${ctx.client.get__he_cn()}"))
//        debugText.add(DebugText("get__he_co     : ${ctx.client.get__he_co()}"))
//        debugText.add(DebugText("get__he_cp     : ${ctx.client.get__he_cp()}"))
//        debugText.add(DebugText("get__he_cq     : ${ctx.client.get__he_cq()}"))
//        debugText.add(DebugText("get__he_cr     : ${ctx.client.get__he_cr()}"))
//        debugText.add(DebugText("get__he_cs     : ${ctx.client.get__he_cs()}"))
//        debugText.add(DebugText("get__he_ct     : ${ctx.client.get__he_ct()}"))
//        debugText.add(DebugText("get__he_cu     : ${ctx.client.get__he_cu()}"))
//        debugText.add(DebugText("get__he_cv     : ${ctx.client.get__he_cv()}"))
//        debugText.add(DebugText("get__he_cw     : ${ctx.client.get__he_cw()}"))
//        debugText.add(DebugText("get__he_cx     : ${ctx.client.get__he_cx()}"))
//        debugText.add(DebugText("get__he_cy     : ${ctx.client.get__he_cy()}"))
//        debugText.add(DebugText("get__he_cz     : ${ctx.client.get__he_cz()}"))
//        debugText.add(DebugText("get__he_da     : ${ctx.client.get__he_da()}"))
//        debugText.add(DebugText("get__he_db     : ${ctx.client.get__he_db()}"))
//        debugText.add(DebugText("get__he_dc     : ${ctx.client.get__he_dc()}"))
//        debugText.add(DebugText("get__he_dd     : ${ctx.client.get__he_dd()}"))
//        debugText.add(DebugText("get__he_df     : ${ctx.client.get__he_df()}"))
//        debugText.add(DebugText("get__he_dg     : ${ctx.client.get__he_dg()}"))
//        debugText.add(DebugText("get__he_dh     : ${ctx.client.get__he_dh()}"))
//        debugText.add(DebugText("get__he_di     : ${ctx.client.get__he_di()}"))
//        debugText.add(DebugText("get__he_dj     : ${ctx.client.get__he_dj()}"))
//        debugText.add(DebugText("get__he_dk     : ${ctx.client.get__he_dk()}"))
//        debugText.add(DebugText("get__he_dl     : ${ctx.client.get__he_dl()}"))
//        debugText.add(DebugText("get__he_dm     : ${ctx.client.get__he_dm()}"))
//        debugText.add(DebugText("get__he_dn     : ${ctx.client.get__he_dn()}"))
//        debugText.add(DebugText("get__he_do     : ${ctx.client.get__he_do()}"))
//        debugText.add(DebugText("get__he_dp     : ${ctx.client.get__he_dp()}"))
//        debugText.add(DebugText("get__he_dq     : ${ctx.client.get__he_dq()}"))
//        debugText.add(DebugText("get__he_dr     : ${ctx.client.get__he_dr()}"))
//        debugText.add(DebugText("get__he_ds     : ${ctx.client.get__he_ds()}"))
//        debugText.add(DebugText("get__he_dt     : ${ctx.client.get__he_dt()}"))
//        debugText.add(DebugText("get__he_du     : ${ctx.client.get__he_du()}"))
//        debugText.add(DebugText("get__he_dv     : ${ctx.client.get__he_dv()}"))
//        debugText.add(DebugText("get__he_dx     : ${ctx.client.get__he_dx()}"))
//        debugText.add(DebugText("get__he_dy     : ${ctx.client.get__he_dy()}"))
//        debugText.add(DebugText("get__he_dz     : ${ctx.client.get__he_dz()}"))
//        debugText.add(DebugText("get__he_e      : ${ctx.client.get__he_e()}"))
//        debugText.add(DebugText("get__he_ea     : ${ctx.client.get__he_ea()}"))
//        debugText.add(DebugText("get__he_eb     : ${ctx.client.get__he_eb()}"))
//        debugText.add(DebugText("get__he_ec     : ${ctx.client.get__he_ec()}"))
//        debugText.add(DebugText("get__he_ed     : ${ctx.client.get__he_ed()}"))
//        debugText.add(DebugText("get__he_ef     : ${ctx.client.get__he_ef()}"))
//        debugText.add(DebugText("get__he_eh     : ${ctx.client.get__he_eh()}"))
//        debugText.add(DebugText("get__he_ei     : ${ctx.client.get__he_ei()}"))
//        debugText.add(DebugText("get__he_ej     : ${ctx.client.get__he_ej()}"))
//        debugText.add(DebugText("get__he_ek     : ${ctx.client.get__he_ek()}"))
//        debugText.add(DebugText("get__he_em     : ${ctx.client.get__he_em()}"))
//        debugText.add(DebugText("get__he_en     : ${ctx.client.get__he_en()}"))
//        debugText.add(DebugText("get__he_eo     : ${ctx.client.get__he_eo()}"))
//        debugText.add(DebugText("get__he_ep     : ${ctx.client.get__he_ep()}"))
//        debugText.add(DebugText("get__he_eq     : ${ctx.client.get__he_eq()}"))
//        debugText.add(DebugText("get__he_er     : ${ctx.client.get__he_er()}"))
//        debugText.add(DebugText("get__he_et     : ${ctx.client.get__he_et()}"))
//        debugText.add(DebugText("get__he_eu     : ${ctx.client.get__he_eu()}"))
//        debugText.add(DebugText("get__he_ew     : ${ctx.client.get__he_ew()}"))
//        debugText.add(DebugText("get__he_ex     : ${ctx.client.get__he_ex()}"))
//        debugText.add(DebugText("get__he_ey     : ${ctx.client.get__he_ey()}"))
//        debugText.add(DebugText("get__he_ez     : ${ctx.client.get__he_ez()}"))
//        debugText.add(DebugText("get__he_fa     : ${ctx.client.get__he_fa()}"))
//        debugText.add(DebugText("get__he_fc     : ${ctx.client.get__he_fc()}"))
//        debugText.add(DebugText("get__he_fg     : ${ctx.client.get__he_fg()}"))
//        debugText.add(DebugText("get__he_fh     : ${ctx.client.get__he_fh()}"))
//        debugText.add(DebugText("get__he_fk     : ${ctx.client.get__he_fk()}"))
//        debugText.add(DebugText("get__he_fl     : ${ctx.client.get__he_fl()}"))
//        debugText.add(DebugText("get__he_fm     : ${ctx.client.get__he_fm()}"))
//        debugText.add(DebugText("get__he_fu     : ${ctx.client.get__he_fu()}"))
//        debugText.add(DebugText("get__he_fv     : ${ctx.client.get__he_fv()}"))
//        debugText.add(DebugText("get__he_fz     : ${ctx.client.get__he_fz()}"))
//        debugText.add(DebugText("get__he_ga     : ${ctx.client.get__he_ga()}"))
//        debugText.add(DebugText("get__he_gb     : ${ctx.client.get__he_gb()}"))
//        debugText.add(DebugText("get__he_gc     : ${ctx.client.get__he_gc()}"))
//        debugText.add(DebugText("get__he_gd     : ${ctx.client.get__he_gd()}"))
//        debugText.add(DebugText("get__he_ge     : ${ctx.client.get__he_ge()}"))
//        debugText.add(DebugText("get__he_gf     : ${ctx.client.get__he_gf()}"))
//        debugText.add(DebugText("get__he_gg     : ${ctx.client.get__he_gg()}"))
//        debugText.add(DebugText("get__he_gh     : ${ctx.client.get__he_gh()}"))
//        debugText.add(DebugText("get__he_gi     : ${ctx.client.get__he_gi()}"))
//        debugText.add(DebugText("get__he_gj     : ${ctx.client.get__he_gj()}"))
//        debugText.add(DebugText("get__he_gk     : ${ctx.client.get__he_gk()}"))
//        debugText.add(DebugText("get__he_gl     : ${ctx.client.get__he_gl()}"))
//        debugText.add(DebugText("get__he_gm     : ${ctx.client.get__he_gm()}"))
//        debugText.add(DebugText("get__he_gn     : ${ctx.client.get__he_gn()}"))
//        debugText.add(DebugText("get__he_go     : ${ctx.client.get__he_go()}"))
//        debugText.add(DebugText("get__he_gp     : ${ctx.client.get__he_gp()}"))
//        debugText.add(DebugText("get__he_gq     : ${ctx.client.get__he_gq()}"))
//        debugText.add(DebugText("get__he_gr     : ${ctx.client.get__he_gr()}"))
//        debugText.add(DebugText("get__he_gs     : ${ctx.client.get__he_gs()}"))
//        debugText.add(DebugText("get__he_gt     : ${ctx.client.get__he_gt()}"))
//        debugText.add(DebugText("get__he_gu     : ${ctx.client.get__he_gu()}"))
//        debugText.add(DebugText("get__he_gv     : ${ctx.client.get__he_gv()}"))
//        debugText.add(DebugText("get__he_gw     : ${ctx.client.get__he_gw()}"))
//        debugText.add(DebugText("get__he_gx     : ${ctx.client.get__he_gx()}"))
//        debugText.add(DebugText("get__he_gy     : ${ctx.client.get__he_gy()}"))
//        debugText.add(DebugText("get__he_gz     : ${ctx.client.get__he_gz()}"))
//        debugText.add(DebugText("get__he_hb     : ${ctx.client.get__he_hb()}"))
//        debugText.add(DebugText("get__he_hd     : ${ctx.client.get__he_hd()}"))
//        debugText.add(DebugText("get__he_he     : ${ctx.client.get__he_he()}"))
//        debugText.add(DebugText("get__he_hf     : ${ctx.client.get__he_hf()}"))
//        debugText.add(DebugText("get__he_hg     : ${ctx.client.get__he_hg()}"))
//        debugText.add(DebugText("get__he_hh     : ${ctx.client.get__he_hh()}"))
//        debugText.add(DebugText("get__he_hj     : ${ctx.client.get__he_hj()}"))
//        debugText.add(DebugText("get__he_hk     : ${ctx.client.get__he_hk()}"))
//        debugText.add(DebugText("get__he_hl     : ${ctx.client.get__he_hl()}"))
//        debugText.add(DebugText("get__he_hn     : ${ctx.client.get__he_hn()}"))
//        debugText.add(DebugText("get__he_hq     : ${ctx.client.get__he_hq()}"))
//        debugText.add(DebugText("get__he_hv     : ${ctx.client.get__he_hv()}"))
//        debugText.add(DebugText("get__he_hy     : ${ctx.client.get__he_hy()}"))
//        debugText.add(DebugText("get__he_hz     : ${ctx.client.get__he_hz()}"))
//        debugText.add(DebugText("get__he_ia     : ${ctx.client.get__he_ia()}"))
//        debugText.add(DebugText("get__he_ic     : ${ctx.client.get__he_ic()}"))
//        debugText.add(DebugText("get__he_ie     : ${ctx.client.get__he_ie()}"))
//        debugText.add(DebugText("get__he_if     : ${ctx.client.get__he_if()}"))
//        debugText.add(DebugText("get__he_ig     : ${ctx.client.get__he_ig()}"))
//        debugText.add(DebugText("get__he_ih     : ${ctx.client.get__he_ih()}"))
//        debugText.add(DebugText("get__he_ii     : ${ctx.client.get__he_ii()}"))
//        debugText.add(DebugText("get__he_ij     : ${ctx.client.get__he_ij()}"))
//        debugText.add(DebugText("get__he_ik     : ${ctx.client.get__he_ik()}"))
//        debugText.add(DebugText("get__he_im     : ${ctx.client.get__he_im()}"))
//        debugText.add(DebugText("get__he_in     : ${ctx.client.get__he_in()}"))
//        debugText.add(DebugText("get__he_io     : ${ctx.client.get__he_io()}"))
//        debugText.add(DebugText("get__he_ip     : ${ctx.client.get__he_ip()}"))
//        debugText.add(DebugText("get__he_iq     : ${ctx.client.get__he_iq()}"))
//        debugText.add(DebugText("get__he_it     : ${ctx.client.get__he_it()}"))
//        debugText.add(DebugText("get__he_iu     : ${ctx.client.get__he_iu()}"))
//        debugText.add(DebugText("get__he_ix     : ${ctx.client.get__he_ix()}"))
//        debugText.add(DebugText("get__he_iy     : ${ctx.client.get__he_iy()}"))
//        debugText.add(DebugText("get__he_ja     : ${ctx.client.get__he_ja()}"))
//        debugText.add(DebugText("get__he_jb     : ${ctx.client.get__he_jb()}"))
//        debugText.add(DebugText("get__he_jc     : ${ctx.client.get__he_jc()}"))
//        debugText.add(DebugText("get__he_jd     : ${ctx.client.get__he_jd()}"))
//        debugText.add(DebugText("get__he_je     : ${ctx.client.get__he_je()}"))
//        debugText.add(DebugText("get__he_jf     : ${ctx.client.get__he_jf()}"))
//        debugText.add(DebugText("get__he_jg     : ${ctx.client.get__he_jg()}"))
//        debugText.add(DebugText("get__he_jh     : ${ctx.client.get__he_jh()}"))
//        debugText.add(DebugText("get__he_ji     : ${ctx.client.get__he_ji()}"))
//        debugText.add(DebugText("get__he_jj     : ${ctx.client.get__he_jj()}"))
//        debugText.add(DebugText("get__he_jk     : ${ctx.client.get__he_jk()}"))
//        debugText.add(DebugText("get__he_jl     : ${ctx.client.get__he_jl()}"))
//        debugText.add(DebugText("get__he_jm     : ${ctx.client.get__he_jm()}"))
//        debugText.add(DebugText("get__he_jn     : ${ctx.client.get__he_jn()}"))
//        debugText.add(DebugText("get__he_jo     : ${ctx.client.get__he_jo()}"))
//        debugText.add(DebugText("get__he_jp     : ${ctx.client.get__he_jp()}"))
//        debugText.add(DebugText("get__he_jq     : ${ctx.client.get__he_jq()}"))
//        debugText.add(DebugText("get__he_jr     : ${ctx.client.get__he_jr()}"))
//        debugText.add(DebugText("get__he_js     : ${ctx.client.get__he_js()}"))
//        debugText.add(DebugText("get__he_jt     : ${ctx.client.get__he_jt()}"))
//        debugText.add(DebugText("get__he_ju     : ${ctx.client.get__he_ju()}"))
//        debugText.add(DebugText("get__he_jv     : ${ctx.client.get__he_jv()}"))
//        debugText.add(DebugText("get__he_jw     : ${ctx.client.get__he_jw()}"))
//        debugText.add(DebugText("get__he_jx     : ${ctx.client.get__he_jx()}"))
//        debugText.add(DebugText("get__he_jy     : ${ctx.client.get__he_jy()}"))
//        debugText.add(DebugText("get__he_jz     : ${ctx.client.get__he_jz()}"))
//        debugText.add(DebugText("get__he_ka     : ${ctx.client.get__he_ka()}"))
//        debugText.add(DebugText("get__he_kd     : ${ctx.client.get__he_kd()}"))
//        debugText.add(DebugText("get__he_ke     : ${ctx.client.get__he_ke()}"))
//        debugText.add(DebugText("get__he_kf     : ${ctx.client.get__he_kf()}"))
//        debugText.add(DebugText("get__he_kg     : ${ctx.client.get__he_kg()}"))
//        debugText.add(DebugText("get__he_ki     : ${ctx.client.get__he_ki()}"))
//        debugText.add(DebugText("get__he_kk     : ${ctx.client.get__he_kk()}"))
//        debugText.add(DebugText("get__he_kl     : ${ctx.client.get__he_kl()}"))
//        debugText.add(DebugText("get__he_km     : ${ctx.client.get__he_km()}"))
//        debugText.add(DebugText("get__he_ko     : ${ctx.client.get__he_ko()}"))
//        debugText.add(DebugText("get__he_kt     : ${ctx.client.get__he_kt()}"))
//        debugText.add(DebugText("get__he_ku     : ${ctx.client.get__he_ku()}"))
//        debugText.add(DebugText("get__he_kv     : ${ctx.client.get__he_kv()}"))
//        debugText.add(DebugText("get__he_kw     : ${ctx.client.get__he_kw()}"))
//        debugText.add(DebugText("get__he_kx     : ${ctx.client.get__he_kx()}"))
//        debugText.add(DebugText("get__he_kz     : ${ctx.client.get__he_kz()}"))
//        debugText.add(DebugText("get__he_t      : ${ctx.client.get__he_t()}"))
//        debugText.add(DebugText("get__he_ai     : ${ctx.client.get__he_ai()}"))
//        debugText.add(DebugText("get__jd_bb     : ${ctx.client.get__jd_bb()}"))




//        debugText.add(DebugText("clientData.loginState :${ctx.client.get__a}"))


        val yBase = 70
        var x = 50
        var y = yBase
        var bannedY = 10
        var bannedX = 50
        val savedFont = g.font
        g.font = Font("Consolas", Font.PLAIN, 10)
        debugText.forEachIndexed { index, debugText ->
            g.color = Color.ORANGE

            g.drawString(debugText.text, x, y)
            //Loginto a banned account and we can get this result
            if(debugText.text.contains("12")){
                g.drawString(debugText.text, bannedX, bannedY)
                bannedY+= 15
            }
            y += 15
            if(index > 0 && index % 40 == 0){
                y = yBase
                x += 250
            }
        }
        g.font = savedFont
    }


}
