package com.p3achb0t.hook_interfaces

interface Client : GameShell {
    fun getAccountStatus(): Int
    fun getBaseX(): Int
    fun getBaseY(): Int
    fun getCameraPitch(): Int
    fun getCameraX(): Int
    fun getCameraY(): Int
    fun getCameraYaw(): Int
    fun getCameraZ(): Int
    fun getCanvas(): Any
    fun getClanMembersHandler(): ClanMemberHandler
    fun getClickModifier(): Int
    fun getCollisionMaps(): Array<CollisionMap>
    fun getCrosshairColor(): Int
    fun getCurrentWorld(): Int
    fun getDestinationX(): Int
    fun getDestinationY(): Int
    fun getExperience(): IntArray
    fun getFps(): Any
    fun getGameCycle(): Int
    fun getGameSettings(): IntArray
    fun getGameSocket(): Any
    fun getGameState(): Int
    fun getGrandExchangeItems(): Array<GrandExchangeItem>
    fun getGroundItemList(): Array<Array<Array<LinkedList>>>
    fun getGroundItemModelCache(): Cache
    fun getHintArrowNPCIndex(): Any
    fun getHintArrowPlayerIndex(): Any
    fun getHintArrowType(): Any
    fun getHintArrowX(): Any
    fun getHintArrowY(): Any
    fun getHintArrowZ(): Any
    fun getHost(): String
    fun getIdleTime(): Int
    fun getIsSpellSelected(): Boolean
    fun getIsWorldSelectorOpen(): Boolean
    fun getItemTable(): HashTable
    fun getKeyboard(): Keyboard
    fun getLastAction(): Long
    fun getLastActionDifference(): Long
    fun getLastActionDifferenceMod(): Long
    fun getLastActionTime(): Long
    fun getLastActionTimeMod(): Long
    fun getLastButtonClick(): Int
    fun getLastButtonClickModA(): Int
    fun getLastButtonClickModM(): Int
    fun getLastClickModifier(): Int
    fun getLastClickModifierModA(): Int
    fun getLastClickModifierModM(): Int
    fun getLastClickX(): Int
    fun getLastClickY(): Int
    fun getLevel(): IntArray
    fun getLocalNPCs(): Array<Npc>
    fun getLocalPlayer(): Player
    fun getLoginState(): Int
    fun getLowestAvailableCameraPitch(): Int
    fun getMapAngle(): Int
    fun getMenuActions(): Array<String>
    fun getMenuCount(): Int
    fun getMenuHeight(): Int
    fun getMenuOpcodes(): IntArray
    fun getMenuOptions(): Array<String>
    fun getMenuShiftClick(): BooleanArray
    fun getMenuVariable(): IntArray
    fun getMenuVisible(): Boolean
    fun getMenuWidth(): Int
    fun getMenuX(): Int
    fun getMenuXInteractions(): IntArray
    fun getMenuY(): Int
    fun getMenuYInteractions(): IntArray
    fun getMessage0(): String
    fun getMessage1(): String
    fun getMessage2(): String
    fun getMessageContainer(): Any
    fun getMouse(): Mouse
    fun getNpcCompositeCache(): Cache
    fun getNpcModelCache(): Cache
    fun getObjectCompositeCache(): Cache
    fun getObjectModelCache(): Cache
    fun getPassword(): String
    fun getPlane(): Int
    fun getPlayerIndex(): Int
    fun getPlayerModelCache(): Cache
    fun getPlayers(): Array<Player>
    fun getProjectiles(): LinkedList
    fun getRealLevel(): IntArray
    fun getRegion(): Region
    fun getSelectedItemID(): Int
    fun getSelectedItemIndex(): Int
    fun getSelectedItemName(): String
    fun getSelectedSpellName(): String
    fun getSelectionState(): Int
    fun getSettings(): IntArray
    fun getSettingsObject(): SettingsClass
    fun getSocialHandler(): SocialHandler
    fun getSocketWrapper(): SocketWrapper
    fun getTileHeights(): Array<Array<IntArray>>
    fun getTileSettings(): Array<Array<ByteArray>>
    fun getUsername(): String
    fun getVarps(): Any
    fun getWidgetBoundsX(): IntArray
    fun getWidgetBoundsY(): IntArray
    fun getWidgetHeights(): IntArray
    fun getWidgetModelCache(): Cache
    fun getWidgetNodes(): HashTable
    fun getWidgetWidths(): IntArray
    fun getWidgets(): Array<Array<Widget>>
    fun getWorlds(): Array<World>
    fun getZoom(): Any
    fun getZoomExact(): Int
}
